### ISSUE TITLE
Data Matrix detection issue

### ISSUE THREAD

**Issue by Surya140** [zxing-cpp/zxing-cpp#146]
![test](https://user-images.githubusercontent.com/68555757/87957468-efe39f80-cacd-11ea-9eca-77707af70b60.png)
When the data matrix is present at the right side of the image the detector fails to detect the data matrix.

**Comment by axxel** [comment]
Does the mentioned commit fix your problem? (it successfully decodes your example now.)

**Comment by Surya140** [comment]
I am checking with few more samples. Will get back to you in case of any further issues. Thanks for the help.

**Comment by axxel** [comment]
Very good. Please note the comment I left with the commit. It is trivial to construct a sample that still fails.

**Comment by Surya140** [comment]
![internetSample2](https://user-images.githubusercontent.com/68555757/88502946-bd660500-cfed-11ea-9526-065f9a2c5492.PNG)

No data matrix is been detected in the above image.

**Comment by Surya140** [comment]
Hello, any updates or help for this issue.

**Comment by axxel** [comment]
Your last sample is pretty much exactly what I meant with my 'trivial to construct' comment above. Note, the current library does not support detecting multiple codes, yet. I intent to fix both limitations, it is just a matter of spare time and priority. Would it help you at all if the library would detect a single one of the 4 symbols? And: is that a real-world sample of yours or a constructed one to show the issue?

**Comment by Surya140** [comment]
Hi, I understand that the library does not support multiple detection yet. Its fine for now if the library detects one but at whatever location it is. I am also modifying the code to detect multiple codes in an image. Added support for QR Code already and it works pretty much good.

The sample was just snipped from the google image search to check the code.

With DataMatrix and Aztec code, it looks there is some issues in detecting one code at a time too.

**Comment by axxel** [comment]
Interesting. For the multi-QRCode support you took the approach that upstream has taken I assume?

I outlined or hinted at my ideas to support that in #138. If there are only QRCodes you are interested in than that is slower than the upstream approach but it would work for every combination of 2D codes. Also be "warned" that I am about to pretty much replace the current `QRDetector` code (in case yours is based on that).

Regarding Aztec support: The current approach to detect the symbols is pretty limited. I have some ideas on how to improve that.

If you have issues with single DataMatrix symbols (apart from the one mentioned here), please let me know.

**Comment by Surya140** [comment]
"After one is found, mask out the data from the BitMatrix where the code was detected and simply look again." I guess this is your suggestion. I collect all the Possible centers from `FinderPatternFinder::Find` and then group the markers.

Nothing related to single DataMatrix, it would be helpful if you could suggest your ideas to improve the detection regarding Aztec and also for the image posted here.

**Comment by axxel** [comment]
After completing my QRDetector stuff I finally came around to work on this. If you want to try it out, you need to comment out a line (see commit message above). I did some performance tuning but am not happy with the results, yet. Hence it is still disabled.

The QRDetector rewrite will require you to modify your `FinderPatternFinder::Find` based code, but the upside is: what I believe what you probably have done is now (partly) implemented upstream.

About my ideas regarding the Aztec detector: basically use the new `ConcentricPattern` code from the QRDetector rewrite and apply it there as well. This should allow to detect the symbol with an arbitrary rotation. But that is not going to be a 2-line change...

**Comment by axxel** [comment]
Stale issue cleanup: when compiled in c++20 mode, 3 of the 4 DM symbols above are now detected (the lower right seems just a little too low on resolution). So this is as fixed as it will get.
