### ISSUE TITLE
Support for inverted symbols (white on black)

### ISSUE THREAD

**Issue by axxel** [zxing-cpp/zxing-cpp#172]
As @neycyanshi correctly pointed out in #167 inverted codes are not handled inside ZXing at the moment (for none of the formats). It is rather trivial for a client application that needs that feature to implement it outside of ZXing by calling `ReadBarcode` twice and the second time simply invert the input image. There are more performant possibilities if done inside and specific to the different implementation characteristics.

A quick and dirty solution to get the functionality into ZXing would be to do the inversion inside `ReadBarcode` based on a new `DecodingHints` flag.

**Comment by overriden-sfdd** [comment]
I'm not sure if I should post it in this thread, but I have a sample with a strange color scheme. Back is light brown and the text is black. I know that we can use thresholding with the big threshold value. Is there a way to decode such case not relying on heuristic preprocessing?
![2](https://user-images.githubusercontent.com/47534862/126989498-28e71ddc-4655-4273-a2b3-37a29ee415a1.jpg)

**Comment by axxel** [comment]
@overriden-sfdd this has nothing to do with inversion (white on black) but shows another limitation of the `GlobalHistogramBinarizer`. Please delete this comment and post it as a new issue. Suggested Title: 'Improve 1D barcode detection with noisy input'.

**Comment by axxel** [comment]
Triggered by #387 I thought a little more about this and came to the conclusion that I don't know enough about the use case that is supposed to be supported here. The naive approach is obviously the above: try everything with and without inverted input. That is rather expensive in terms of performance.

What I am questioning is the use-case of inverted linear barcodes. It seems to me that those are simply non-existent in terms of the standards? Inverted QR Codes are obviously a thing and so is inverted DataMatrix (#173). I would suggest to limit this feature to symbologies that actually support that and hence occur in the wild and not waste implementation and processing time on stuff that is never used.

If someone has an inverted input due to technical reasons and everything needs to be inverted back per se, then they shall fix that outside of the lib in my opinion.

May I pull in @gitlost and @oehhar s expertise once again? Anyone else has a stake in the matter?

**Comment by gitlost** [comment]
The symbologies known to me that support "reflectance reversal" are Aztec Code, Data Matrix, DotCode, Han Xin Code, Grid Matrix and QR Code (including Micro QR Code & rMQR), so i.e. matrix symbols, no linear or stacked symbols.

Of the left-out matrix symbologies, the MaxiCode standard doesn't mention it. It's not mentioned in the Aztec Runes annex either, but the assumption should probably be that it is supported for Aztec Runes.

**Comment by axxel** [comment]
@gitlost thanks for your input and confirmation of my belief that looking for 'inverted' linear codes is a waste of time/resources. You did not mention one other matrix code (PDF417) maybe because it technically actually is a stacked linear one. The way it is implemented here, it falls in the matrix code category, though.

So, anyone disagreeing with the idea of looking only for 'inverted' symbols whose specification allows for them?

That would inform the API in my opinion in the following way: contrary to my ideas expressed in #387 about having something like `DecodeHints::tryInvert(InversionMode)` with options like `No|Yes|Only` which would allow to make the library look only for inverted symbols, this is not obviously the best idea in my opinion anymore and a simple `tryInvert(bool)` flag might be the better choice.

@markusfisch expressed the desire to have an `only` mode for performance reasons, presumably mainly because the naive approach would double the runtime. But a) this will not be the case if implemented properly and b) the case where you know that you are only interested in say inverted QRCodes and want to completely spare the cost of testing for normal ones, you can always invert your image beforehand and do that virtually as fast as a simple memcopy of the image. In my opinion this would be too much of a niche use case to complicate the API with yet another enum.

**Comment by axxel** [comment]
@markusfisch the performance penalty of the `tryInvert` flag in the demo app is virtually unnoticeable on my phone.

@parallaxe @davesworking: you may want to add a `tryInvert` flag to the iOS wrapper as I did for the android one. See also the comment in above commit.

**Comment by markusfisch** [comment]
@axxel That's great 👍 I just did some tests on some of my devices and the difference is actually negligible. Well done! And thanks for the quick solution!

**Comment by parallaxe** [comment]
@axxel Yes, I added it already and will create a pull request within the next week.
