### ISSUE TITLE
Python bindings without numpy?

### ISSUE THREAD

**Issue by dainnilsson** [zxing-cpp/zxing-cpp#283]
Hi!

Numpy is a pretty huge dependency (~40MB, mostly due to openblas) that I'd like to avoid. Looking at the API, the `read_barcode` function takes an image in either PIL or numpy format.

Does this mean the requirement on numpy could be made optional when using PIL?

**Comment by axxel** [comment]
That is a good question. I suggest you modify the `setup.py` file by removing the line `install_requires=["numpy"],`, build it yourself and see what happens. We added the PIL interface later, so it might be just a relic of the past.

**Comment by dainnilsson** [comment]
I'm a bit out of my wheelhouse here, are there any build instructions available? I've looked at the Github Actions workflows, but I'm afraid I'm a bit lost when it comes to C++ and cmake.

**Comment by dainnilsson** [comment]
Thanks, I had tried that, but it wasn't working. It would only give me `Unknown CMake command "pybind11_add_module"`. I tested some more and figured out that it works the very first time the command is run, but not for subsequent runs, unless you delete the `build/` directory first.

Now with that solved, I built anew with `numpy` removed from setup.py. The build succeeded, and `pip list` showed zxingcpp installed, without numpy. However, when running a simple test script it fails:

```
Traceback (most recent call last):
  File "/...path omitted.../qrtest.py", line 6, in <module>
    res = zxingcpp.read_barcode(img, formats=zxingcpp.BarcodeFormat.QRCode)
ModuleNotFoundError: No module named 'numpy'
```

For reference, here's the full test script I'm running:
```python
from PIL import Image
import zxingcpp


with Image.open("qr.png") as img:
    res = zxingcpp.read_barcode(img, formats=zxingcpp.BarcodeFormat.QRCode)
print(res.text)
```

Any ideas for further steps to try out?

**Comment by axxel** [comment]
The first issue is solved (I stumbled upon this just recently as well: https://github.com/nu-book/zxing-cpp/commit/8db14eeead45e0f1961532f55061d5e4dd0f78be#commitcomment-66424239).

I believe it should be possible to do this without loading numpy since we really only need access to the dimension and the data pointer to the buffer. I guess asking the pybind11 community how to achieve that would be a possible next step.

**Comment by axxel** [comment]
Are you still interested in working on this? Any updates from your side? (Asking because I'd like to make a release soonish...)

**Comment by dainnilsson** [comment]
Sorry for the lack up updates! I'm still interested in finding a solution to the issue, but outside of testing stuff I'm afraid I'm not able to contribute much.

**Comment by axxel** [comment]
You could reach out to the pybind11 community and ask there. That would help make progress, I guess.

**Comment by axxel** [comment]
I asked the pybind11 community a couple months ago but got no reply: https://github.com/pybind/pybind11/discussions/4093

**Comment by axxel** [comment]
I stumbled upon relevant information in the pybind11 doc about the [buffer protocol](https://pybind11.readthedocs.io/en/stable/advanced/pycpp/numpy.html#buffer-protocol) which at least does not require to use the `py::array_t` class to access opencv matrices. PIL objects do not conform to that protocol (it seems), but apparently [__array_interface__](https://subscription.packtpub.com/book/big-data-and-business-intelligence/9781849518925/4/ch04lvl1sec40/using-the-array-interface) would be a means to get somewhere. Even if that is solved, there still needs to be a replacement for the `write_barcode()` return type. The following diff at least works for reading OpenCV matrices:

```patch
@@ -47,10 +47,11 @@ auto read_barcodes_impl(py::object _image, const BarcodeFormats& formats, bool t
 		.setBinarizer(binarizer)
 		.setIsPure(is_pure)
 		.setMaxNumberOfSymbols(max_number_of_symbols)
 		.setEanAddOnSymbol(ean_add_on_symbol);
 	const auto _type = std::string(py::str(py::type::of(_image)));
+	py::buffer buffer;
 	Image image;
 	ImageFormat imgfmt = ImageFormat::None;
 	try {
 		if (_type.find("PIL.") != std::string::npos) {
 			_image.attr("load")();
@@ -65,33 +66,43 @@ auto read_barcodes_impl(py::object _image, const BarcodeFormats& formats, bool t
 				// Unsupported mode in ImageFormat. Let's do conversion to L mode with PIL.
 				_image = _image.attr("convert")("L");
 				imgfmt = ImageFormat::Lum;
 			}
 		}
-		image = _image.cast<Image>();
+		buffer = _image.cast<py::buffer>();
 #if PYBIND11_VERSION_HEX > 0x02080000 // py::raise_from is available starting from 2.8.0
 	} catch (py::error_already_set &e) {
 		py::raise_from(e, PyExc_TypeError, ("Could not convert " + _type + " to numpy array.").c_str());
 		throw py::error_already_set();
 #endif
 	} catch (...) {
 		throw py::type_error("Could not convert " + _type + " to numpy array. Expecting a PIL Image or numpy array.");
 	}
-	const auto height = narrow_cast<int>(image.shape(0));
-	const auto width = narrow_cast<int>(image.shape(1));
-	const auto channels = image.ndim() == 2 ? 1 : narrow_cast<int>(image.shape(2));
+
+	/* Request a buffer descriptor from Python */
+	py::buffer_info info = buffer.request();
+
+	if (info.format != py::format_descriptor<uint8_t>::format())
+		throw py::type_error("Incompatible format: expected a uint8_t array.");
+
+	if (info.ndim != 2 && info.ndim != 3)
+		throw py::type_error("Incompatible buffer dimension.");
+
+	const auto height = narrow_cast<int>(info.shape[0]);
+	const auto width = narrow_cast<int>(info.shape[1]);
+	const auto channels = info.ndim == 2 ? 1 : narrow_cast<int>(info.shape[2]);
 	if (imgfmt == ImageFormat::None) {
 		// Assume grayscale or BGR image depending on channels number
 		if (channels == 1)
 			imgfmt = ImageFormat::Lum;
 		else if (channels == 3)
 			imgfmt = ImageFormat::BGR;
 		else
 			throw py::value_error("Unsupported number of channels for numpy array: " + std::to_string(channels));
 	}
 
-	const auto bytes = image.data();
+	const auto bytes = static_cast<uint8_t*>(info.ptr);
 	return ReadBarcodes({bytes, width, height, imgfmt, width * channels, channels}, hints);
 }
 
 std::optional<Result> read_barcode(py::object _image, const BarcodeFormats& formats, bool try_rotate, bool try_downscale,
 								   TextMode text_mode, Binarizer binarizer, bool is_pure, EanAddOnSymbol ean_add_on_symbol)
```

**Comment by EchterAgo** [comment]
If anyone wants to try it, check out https://github.com/zxing-cpp/zxing-cpp/pull/615 for a way to completely remove the numpy requirement. What changes is the `write_barcode` return type, you might need to convert it to an image differently, for example `Image.frombuffer("L", img.shape, img)` for a `PIL.Image` or `QImage(bytes(img), img.shape[0], img.shape[1], img.shape[0], QImage.Format_Grayscale8)` for `PyQt5.QtGui.QImage`. We could also change `write_barcode` to return a type that has `__array_interface__` if that is more useful.

**Comment by dainnilsson** [comment]
I can confirm that when building this from master this now works for my use-case, and no longer requires numpy :tada:
Thanks for your work on this! Is there a planned time-frame for when this will be available in a released version?

**Comment by axxel** [comment]
@dainnilsson thanks for your feedback. To answer your question: no, I don't have a planned time-frame for the next release. Looking at the last two, it looks like at most another 3-4 months ;-).

**Comment by dainnilsson** [comment]
Ok, thanks for replying! I'll look into building from source in the meantime.
