### ISSUE TITLE
ZXing-cpp merges nearby 1D barcodes into one if they have exact same content

### ISSUE THREAD

**Issue by duanqn** [zxing-cpp/zxing-cpp#367]
Tested on v1.3.0.
I don't have any samples that I can share at the current moment. Sorry. But I suspect this is related to de-duplication of 1D barcodes.

**Comment by axxel** [comment]
> But I suspect this is related to de-duplication of 1D barcodes.

Yes it is. There is a simple heuristic used to de-duplicate the symbols. The parameters could be tuned if something slightly more accurate could be found but there are always going to be counter examples that break the heuristic.

**Comment by duanqn** [comment]
> The parameters could be tuned if something slightly more accurate could be found but there are always going to be counter examples that break the heuristic.

Yes, but I believe some cases can be avoided.
<img width="661" alt="multi-code" src="https://user-images.githubusercontent.com/21275667/182755585-58bfa9ac-2921-4651-b4b5-7b9b273aab70.png">

Results with ZXing-cpp (e0b55812e8403d591339f89ddffbd16db40fcb3d)
![multi-code_visualize](https://user-images.githubusercontent.com/21275667/182755599-8e69e5da-5ba9-4037-8981-b5374320a2b6.png)

I don't know enough details about this heuristic method, but I feel this case can be handled relatively easily.
