### ISSUE TITLE
Add more scan line angles for 1D barcodes?

### ISSUE THREAD

**Issue by duanqn** [zxing-cpp/zxing-cpp#369]
My understanding of the current 1D barcode detector is that it scans through vertical and horizontal lines to find the barcode patterns. Some barcodes cannot be detected by ZXing-cpp because there is no vertical / horizontal line that intersects with all bars. This can happen if the 1D barcode is not tall enough and is rotated in an angle like 30 degrees.

To catch more 1D barcodes, is it possible to add 45 degrees and 135 degrees into our scan lines? I understand there will be a performance cost. If it is possible to do so, maybe we can make them optional features which are controlled under `DecoderHints`.

**Comment by axxel** [comment]
That would certainly be possible but it will still not be enough to truly make the library work rotation independent and the gain of additional detections might not be worth the effort? What is your estimate how much more samples in percent that will discover? Maybe 25% of the currently missing ones?

**Comment by duanqn** [comment]
Yes it's still not rotation-independent. If you have other ideas that can make it rotation-independent then that's definitely better than my idea :)

> What is your estimate how much more samples in percent that will discover?

I don't have a number. It really depends on the data distribution. 

One thing that comes to my mind -- If we add 45 and 135 degrees, then the results may have duplications with 0 and 90 degrees, and we need another round of de-duplication work.
