### ISSUE TITLE
1.4.0 dylibs not generated on Mac platforms

### ISSUE THREAD

**Issue by davesworking** [zxing-cpp/zxing-cpp#375]
We recently changed from 1.3.0 to 1.4.0. On the Mac platforms, the dylibs are not generated for version 1.4.0. CMake log shows:

`Linking CXX shared library ZXing.framework/ZXing`

Is this correct? Is there a way to generate dylibs?

Thanks!
Dave

**Comment by axxel** [comment]
I was not aware of any change that would cause/explain a different behavior with regards to dylibs between 1.3 and 1.4. I checked the diff (`git diff v1.3.0 v1.4.0 core/CMakeLists.txt`) and that does not explain it either to me. There has been a change _after_ 1.4.0 that might be affecting that, though (see `if(APPLE)` block in #337).

Bottom line: no idea what is going on here and I can't dive deeper into that, since I don't have a mac setup.

**Comment by davesworking** [comment]
The if(APPLE) block was the issue. I commented it out. Thanks!

**Comment by axxel** [comment]
So linking against the Framework is not an option for you? I'd like to prevent more issue reports like this before releasing 2.0. Do we need a configurable option to switch between dylib and framework generation? @markusfisch any comment on that?

**Comment by davesworking** [comment]
The comment I received from our developer was : "We _could_ use the current framework build of zxing but it's significantly harder than the usual headers+dylib"

**Comment by markusfisch** [comment]
Well, I have to forward this question to @ChristianNorbertBraun who did the iOS wrapper.

**Comment by axxel** [comment]
@markusfisch right. Sorry for somehow confusing you, too. very unprofessional... ;-/

**Comment by markusfisch** [comment]
@axxel No problem, after all we work for the same company and I already pinged him to have a look 😉

**Comment by parallaxe** [comment]
As co-author of the ios-wrapper and in deputy of Chris: @davesworking We don't see how and why a framework should be harder to use than headers+dylib in anyway, let alone *significantly*. Frameworks bundle the binary, headers, modulemap and more in a standardised way and are the standard to distribute libraries on Apple Systems.

Can you please elaborate on the problems?

**Comment by davesworking** [comment]
sorry, I am still fairly new to the company so I don't know what process the Developers use to include libraries. I don't have insight into what is more difficult. I am building the dylibs now and everything is fine. Thanks!

**Comment by axxel** [comment]
If I was convinced that there is a valid use-case for the non-framework version, we could add a cmake `BUILD_...` option to make it configurable. As of today, I'm not ;). So if you feel your problem is solved and you don't have anything else to contribute, please close the issue.
