### ISSUE TITLE
Failed to clone repository: 'https://git.code.sf.net/p/libzueci/code'

### ISSUE THREAD

**Issue by bestpower** [zxing-cpp/zxing-cpp#377]
When I clean the android project and rebuild, the AS output that:
```
CMake Error at zueci-subbuild/zueci-populate-prefix/tmp/zueci-populate-gitclone.cmake:31 (message):
Failed to clone repository: 'https://git.code.sf.net/p/libzueci/code'
```
This "zxing_add_package(zueci zueci https://git.code.sf.net/p/libzueci/code master)" cmake cmd run failed.

My pc internet has no problems, and I try to open the "https://git.code.sf.net/p/libzueci/code" address in browser, but it tips no safe address and open with no safe type, it shows a game address.
Seemingly, the "https://git.code.sf.net/p/libzueci/code" website is attacked?

How to fix it?
Can libzueci offline libraries be provided in this peoject?

**Comment by axxel** [comment]
Interesting observation. I just tried `git clone https://git.code.sf.net/p/libzueci/code` on my machine and it works just fine. Maybe it was a temporary issue?

@gitlost do you have any prior SourceForge experience that might be relevant here?

**Comment by gitlost** [comment]
I haven't no, would doubt very much it's a SourceForge issue. Looks to me like something is doing things to urls on this particular machine.

**Comment by axxel** [comment]
So, looks more like @bestpower's machine got hacked? I might actually end up copying the libzueci code into this repo but would rather avoid it. This particular issue is not convincing enough for me.

**Comment by bestpower** [comment]
The "https://git.code.sf.net/p/libzueci/code" is very instable, today this fail situation has already occurred many times, so I recommend to save the this library source file or the compiled library file directly in this project.

**Comment by gitlost** [comment]
Ok I have noticed that SourceForge can be slow at times and very occasionally fail so maybe depending on where you are this is a bigger problem (the getting redirected to a gaming site is machine-specific I would guess).

**Comment by Neyasbit** [comment]
I have the same problem, but the thing is, I don't have the `zxingcpp/build/outputs/aar/zxingcpp-release.aar` file yet. Since I'm making `$./gradlew :zxingcpp:assembleRelease` for the first time, where else can I get it?
