### ISSUE TITLE
False positive barcode within another barcode

### ISSUE THREAD

**Issue by mbaros100** [zxing-cpp/zxing-cpp#391]
![Constitution_QR](https://user-images.githubusercontent.com/8537079/186756901-3eef0b3d-dd57-49a6-8d1c-8f42b466ddb2.png)

**Comment by axxel** [comment]
That is an interesting/unusual case. There simply happens to be a valid Codabar pattern embedded within the QRCode. The question is, how to deal with that, or what is your expectation?

One could argue that finding one code within another is always wrong but then there are examples like [this](https://github.com/zxing-cpp/zxing-cpp/blob/master/test/samples/qrcode-2/16.png) with two valid QRCodes.
