### ISSUE TITLE
Exception: BitSource::readBits: out of range

### ISSUE THREAD

**Issue by mbaros100** [zxing-cpp/zxing-cpp#404]
![Micro_QR_Example svg](https://user-images.githubusercontent.com/8537079/189129486-dba87dc7-eed9-4121-80d1-009866e9c345.png)

**Comment by axxel** [comment]
To me it looks like this symbol contains invalid data (according to the specification). It has a bytes segment with the context "Example" and then follows a numeric segment with supposedly 24 digits but only 3 bits left in the stream. Now the question is: is this really invalid (which would mean the proper way to deal with this is to return an error) or is my understanding of the spec wrong.

Where did you get this from? Can you show me any online barcode detector that can detect this (I've tried several and all failed)?

This might be the same issue as #392, although there it seems to show up with DataMatrix input?
