### ISSUE TITLE
TextUtfEncodingTest.ToUtf8AngleEscape unittest fails

### ISSUE THREAD

**Issue by PureTryOut** [zxing-cpp/zxing-cpp#405]
```
[----------] 1 test from TextUtfEncodingTest
[ RUN      ] TextUtfEncodingTest.ToUtf8AngleEscape
/home/bart/Documents/Git/alpine/aports/community/zxing-cpp/src/zxing-cpp-1.4.0/test/unit/TextUtfEncodingTest.cpp:22: Failure
Expected equality of these values:
  ToUtf8(L"\u00B6\u0416", angleEscape)
    Which is: "\xC2\xB6\xD0\x96"
    As Text: "¶Ж"
  "<U+B6><U+0416>"
/home/bart/Documents/Git/alpine/aports/community/zxing-cpp/src/zxing-cpp-1.4.0/test/unit/TextUtfEncodingTest.cpp:26: Failure
Expected equality of these values:
  ToUtf8(L"\u2602", angleEscape)
    Which is: "\xE2\x98\x82"
    As Text: "☂"
  "<U+2602>"
/home/bart/Documents/Git/alpine/aports/community/zxing-cpp/src/zxing-cpp-1.4.0/test/unit/TextUtfEncodingTest.cpp:46: Failure
Expected equality of these values:
  ToUtf8(L"\xFFEF", angleEscape)
    Which is: "\xEF\xBF\xAF"
    As Text: "￯"
  "<U+FFEF>"
[  FAILED  ] TextUtfEncodingTest.ToUtf8AngleEscape (0 ms)
[----------] 1 test from TextUtfEncodingTest (0 ms total)
```

This is with zxing-cpp 1.4.0 and (if it matters) Musl libc.

**Comment by axxel** [comment]
1) Can you let me know the compiler incl. version and platform you are using?
2) Can you also test current HEAD?

**Comment by PureTryOut** [comment]
The compiler is gcc 12.1.1. Not sure what you mean with platform but this is on Alpine Linux, x86_64.

I can not test current HEAD as it needs zueci for that and the link in the CMakeLists.txt file just leads to a 404.

**Comment by gitlost** [comment]
musl does a mickey-mouse version of `is_wgraph()` (via `is_wspace()` and in particular `is_wprint()` see - https://git.musl-libc.org/cgit/musl/tree/src/ctype/iswprint.c) so U+00B6, U+0416, U+2602, U+FFEF etc. will be considered non-graphical.

(The non-portability of `is_wgraph()` and locales is the reason I went to the over-the-top trouble of doing [ZXCType.cpp](https://github.com/gitlost/zxing-cpp/blob/cc6b667edd7be2eb42e6726070215aa67e8441eb/core/src/ZXCType.cpp) in the "diagnostics2" branch, which I might try submitting to musl one day to see what they say...)

**Comment by axxel** [comment]
Thanks @gitlost for your insight! I'm not a fan of duplicating libc functionality to fix "buggy" system implementation of those. I'd suggest to simply disable the affected tests when built on libmusl. If that is not easily possible, then maybe simply disable them for all as this is in no way a critical functionality anyway.

About the 404: is that the same or related to the issue that has been discussed in #377?

**Comment by gitlost** [comment]
Re 404 wouldn't have thought so but don't know, but given the issues that have arisen I'd be inclined to just embed the libzueci source...

**Comment by PureTryOut** [comment]
> About the 404

Yeah, might be. It's not unreliable for me though, it just _never_ works.

> I'd suggest to simply disable the affected tests when built on libmusl. If that is not easily possible

I don't know of any easy way. With CMake I can do `ctest -E "test to skip"` but the test failing here is part of the larger "UnitTest" ctest target. I can either disable _all_ tests in "UnitTest" or none of them, as far as I know.

**Comment by axxel** [comment]
I was hoping for a preprocessor macro but the musl-people apparently think that this would be bad: https://www.openwall.com/lists/musl/2013/03/29/13. :-/. I'll disable the affected tests. But I'll not backport that to 1.4.

I'll continue the discussion on how to deal best with the libzueci dependency in another place.

**Comment by axxel** [comment]
Thanks @gitlost for pointing to the musl implementation. Given the problems with locales in general on iOS (#417), I'm inclined to get away from them altogether, just as you did in your branch. But as far as I understand it, the situation is as follows:
 1) our use-case for iswgraph does not require it map exactly to any standard document as long as we avoid the 'loss' of characters due to them not being visible on screen
 2) to make sure there is indeed an exact mapping, we are actually dependent on the platform?
 3) your assessment that _U+00B6, U+0416, U+2602, U+FFEF etc. will be considered non-graphical_ by the musl implementation is wrong (tested with compiler explorer)

This makes me think the easiest / smallest fix that satisfies our needs would be to simply use the musl implementation.

**Comment by gitlost** [comment]
Hi yes using the musl implementation (as is or adjusted to be a bit better) sounds like an excellent idea.

Re 2. sorry not getting your meaning here.

Re 3. I see, apologies, just another one of my code-reading "guesses".
