### ISSUE TITLE
Barcodes cannot be recognized

### ISSUE THREAD

**Issue by duanqn** [zxing-cpp/zxing-cpp#411]
Hi, can anyone help with these images? I debugged the binarization results but they look OK. I'm wondering why these barcodes cannot be recognized. Are they not standard-conformant?

![UPCdiag](https://user-images.githubusercontent.com/21275667/190376717-5e5491d9-7bd1-4c6b-9940-b88c9240c94a.png)
![images](https://user-images.githubusercontent.com/21275667/190376742-81f6a559-e96e-48c2-aeb7-df4cd3f54bf1.png)

**Comment by axxel** [comment]
The first image is simply invalid. There is a white line above the '5' missing. Compare with https://barcode.tec-it.com/en/UPCA?data=012345678905

The second image would need just a little bit more resolution. Interestingly, if I scan it with my phone running the android demo off my monitor, it sometimes is able to decode it.
