### ISSUE TITLE
Cannot detect multiple DataMatrix symbols

### ISSUE THREAD

**Issue by liuyl07** [zxing-cpp/zxing-cpp#412]
I compiled the master branch with the commit https://github.com/zxing-cpp/zxing-cpp/commit/698a7c534bfe5537e4ecbf64a2b3e82416f279b0

It is good to decode each of the two datamatrix in the image if we separate them and feed it into ZXingReader.exe
![8_datamatrix](https://user-images.githubusercontent.com/15646535/190993318-b3896dc5-6c66-4e58-8b3d-e071e4b4bc9e.png)

However, ZXingReader.exe only decodes one of them when we feed the above image into the program.

![image](https://user-images.githubusercontent.com/15646535/190993736-9b64e343-487c-4210-bbbb-c85e67808504.png)

**Comment by duanqn** [comment]
See #386

**Comment by liuyl07** [comment]
@duanqn Thanks! It is indeed a duplicate question :)

**Comment by liuyl07** [comment]
Closing this ticket since it is duplicated

**Comment by axxel** [comment]
I reopen this issue to help other people find the information and hopefully not open the next duplicate. It is indeed an 'open' issue in this sense.

**Comment by axxel** [comment]
Never mind. Decided it makes more sens to reopen #386 as that contains the actual info on how to work around the problem.
