### ISSUE TITLE
DMDetector: Avoid duplicate pEdge in traceStep()

### ISSUE THREAD

**Issue by liuyl07** [zxing-cpp/zxing-cpp#414]
Below shows how pEdge is computed
![image](https://user-images.githubusercontent.com/15646535/191160363-cbfd0d15-5b78-4220-9ab9-98e97dedff31.png)

Suppose maxStepSize = 1, breadth iterates from 0 to 1

1. When breadth = 1, i can be **0, 1, 2**
2. When breadth = 2, i can be **0, 1, 2**, 3, 4

It looks to me that the value of i corresponding to a larger breadth value contains those corresponding to a smaller breadth value. Here is a concrete example.
![image](https://user-images.githubusercontent.com/15646535/191161113-d0a70b1a-a69d-422b-89b4-6a33a0af651b.png)

**Comment by axxel** [comment]
Nice spotting. This does indeed some work that it would not need to. That said, I quickly hacked it to not do that and it makes absolutely no measurable difference, so I don't see the value of making the code more complicated to understand if it gains us nothing. Do you have a particular issue with this? Did you find this while trying to fix another issue?

**Comment by liuyl07** [comment]
@axxel This repository is lucky to have people like you who respond positively and friendly :)

I found this repeatability phenomena by learning the DataMatrix detection and decoding process under step by step. 

I think it is okay to keep it as is if no obvious performance drops

**Comment by axxel** [comment]
Thanks for the kind words. You do this inspection just out of curiosity?

**Comment by liuyl07** [comment]
@axxel Yes, simply out of curiosity for the moment in case later we need to custom/improve some of its internal logics for our projects.
