### ISSUE TITLE
A problem about Incomplete location of databar code

### ISSUE THREAD

**Issue by zepingWww** [zxing-cpp/zxing-cpp#416]
When I scaned the databar code, it could decode it but it couldn't get an accurate location which maybe only provide an incomplete location. Could the zxing provide an accurate location for  the databar code?

**Comment by axxel** [comment]
Could you please provide an example image that shows the issue you are having and also describe what you expect compared to what you get?

**Comment by axxel** [comment]
Without further input from the OP, I'll close this ticket.
