### ISSUE TITLE
Exception on iOS when converting string to HRI

### ISSUE THREAD

**Issue by CoPrez** [zxing-cpp/zxing-cpp#417]
When running ZXing-cpp on an iOS device I fount that an exception is being thrown from the EscapeNonGraphical function when it calls `std::locale utf8Loc("en_US.UTF-8")` ([here](https://github.com/zxing-cpp/zxing-cpp/blob/baffb890f214cba6ba5f0c2d6d63cce8d376b60b/core/src/Utf.cpp#L222)). The exception thrown is "collate_byname<char>::collate_byname failed to construct for en_US.UTF-8". My suspicion is that the iOS platform does not provide the locale that it's trying to access.

The issue can be reproduced by scanning this barcode with default decoder hints:
![image](https://user-images.githubusercontent.com/40213616/192044050-c65903f3-cb4c-471a-a498-13ef9f7ad553.png)

**Comment by axxel** [comment]
Can you test what happens if you simply remove the `"en_US.UTF-8"` parameter?
