### ISSUE TITLE
Detector outputs wrong location for the PDF417 format

### ISSUE THREAD

**Issue by ptc-sothomas** [zxing-cpp/zxing-cpp#426]
While trying out zxing version 1.4 and latest HEAD, I noticed that sometimes PDF417 detector outputs wrong location of the barcode. The below frames are part of a video. So let me post one good frame where location is output correctly and three different frames where the location and rotation were output incorrectly.
Input frames:-
1. PDF417_Good1
![PDF417_Good1](https://user-images.githubusercontent.com/24896321/196693308-1b2efed8-1bad-467b-b0c3-3e2df61a0f60.png)
2. PDF417_problem1
![PDF417_problem1](https://user-images.githubusercontent.com/24896321/196693334-5682863a-a6dd-4a1c-8b63-206abdf4e1a5.png)
3. PDF417_problem2
![PDF417_problem2](https://user-images.githubusercontent.com/24896321/196693379-7bddf3b6-8fa8-46ac-8be7-5d4ee3414d64.png)
4. PDF417_problem3
![PDF417_problem3](https://user-images.githubusercontent.com/24896321/196693397-d5240c0e-e222-4d05-a0bd-522dc133665d.png)
Output images and log files:-
1. PDF417_Good1
[PDF417_Good1_out.txt](https://github.com/zxing-cpp/zxing-cpp/files/9820527/PDF417_Good1_out.txt):-
![PDF417_Good1_out](https://user-images.githubusercontent.com/24896321/196693777-1d8e2202-9fe7-4902-88df-c5ed356aae74.png)
2. PDF417_problem1
[PDF417_problem1_log.txt](https://github.com/zxing-cpp/zxing-cpp/files/9820530/PDF417_problem1_log.txt)
![PDF417_problem1_out](https://user-images.githubusercontent.com/24896321/196693881-e426e1b9-be4e-4248-a439-2fdf3d3fda8f.png)
3. PDF417_problem2
[PDF417_problem2_log.txt](https://github.com/zxing-cpp/zxing-cpp/files/9820533/PDF417_problem2_log.txt)
![PDF417_problem2_out](https://user-images.githubusercontent.com/24896321/196693905-56cdb1a1-d53b-43a9-84d9-85c526c10b70.png)
4. PDF417_problem3
[PDF417_problem3_log.txt](https://github.com/zxing-cpp/zxing-cpp/files/9820534/PDF417_problem3_log.txt)
![PDF417_problem3_out](https://user-images.githubusercontent.com/24896321/196693928-872a16b4-4a3f-4bb7-b5e6-f513de0bce56.png)

Frames `PDF417_Good1` and `PDF417_problem1` are adjacent frames where former got correct output and the latter got incorrect location and rotation for the code. 
In frames `PDF417_problem2` and `PDF417_problem3` , the output images would contain two outputs in each frames, where one is correct and other is incorrect in terms of location and rotation of the barcode

**Comment by axxel** [comment]
Thanks for doing the work of properly reporting this issue.
