### ISSUE TITLE
Some flipped/mirrored QRCode images couldn't be decoded

### ISSUE THREAD

**Issue by bestpower** [zxing-cpp/zxing-cpp#428]
I have tested some qrcode images, and find that flipped/mirrored QRCode images which text contains "0" couldn't be decoded, such as 
1234567890、0123456789、1234506789
[qrcode_origin_flip_test.zip](https://github.com/zxing-cpp/zxing-cpp/files/9828711/qrcode_origin_flip_test.zip)

But other qrcode images flipped/mirrored QRCode images which text no contains "0" could be decoded.
So zxing cpp project codes about qrcode decoder perhaps exist some bugs, please help to analyze and solve, thank you!

**Comment by axxel** [comment]
Thanks for reporting this. I believe the issue had nothing to do with whether or not there was a '0' in the string, therefore I changed the title.

**Comment by bestpower** [comment]
I pulled the newest codes and test, this bug has been solved, thank you very much!
