### ISSUE TITLE
decode chinese garbled for QR code

### ISSUE THREAD

**Issue by liangxiaowei00** [zxing-cpp/zxing-cpp#430]
Take an example,my QR code contains "你好" zxing decoding result is
\xe6\xa2\x81\xe5\xb0\x8f\xe4\xbc\x9f， how to fix this?,thank you.

**Comment by axxel** [comment]
Please provide the image of the QR code with the issue.

**Comment by duanqn** [comment]
I suspect it's encoded with non-UTF8 encodings, e.g. GB2312.

**Comment by liangxiaowei00** [comment]
> Please provide the image of the QR code with the issue.

thank you for your reply。
I use a non-utf-8 encoding mode ，so Chinese characters cannot be recognized

**Comment by axxel** [comment]
You can pass the character set to `ReadBarcodes` via the `DecodingHints` if you know it in advance. The encoding should ideally be recognized automatically. If I had access to the sample image, I could check if there is some issue to be fixed.

**Comment by liangxiaowei00** [comment]
> You can pass the character set to `ReadBarcodes` via the `DecodingHints` if you know it in advance. The encoding should ideally be recognized automatically. If I had access to the sample image, I could check if there is some issue to be fixed.
hi,axxel,
thank you for your reply again。
it is solved.
