### ISSUE TITLE
Missing ReadBarcodes() function in vcpkg 1.3.0

### ISSUE THREAD

**Issue by JaviBite** [zxing-cpp/zxing-cpp#431]
Hello!

I see since 1.3.0 version there is multiple-barcode support, however Im using this lib with vcpkg and that package doesn't include the ReadBarcodes() function, could you update it?

Thank you!

**Comment by axxel** [comment]
Thanks for pointing this out. I have nothing to do with the vcpkg preparation, though. Maybe @duanqn can say something about that (given that I saw his name mentioned [here](https://github.com/microsoft/vcpkg/commits/master/ports/nu-book-zxing-cpp)).

**Comment by duanqn** [comment]
Ah yes, I bumped the version to 1.3.0 on vcpkg side. (Keen observation BTW 🙂)
I didn't do anything special though, so the code should be exactly the same as tag v1.3.0. Give me some time and I can do some investigation.

Maybe it's better to also open an issue on vcpkg side if this can be a platform-specific issue.

**Comment by duanqn** [comment]
Also maybe it's time to bump to 1.4.0...

**Comment by axxel** [comment]
> Also maybe it's time to bump to 1.4.0...

Sure, go ahead. I will not engage in the vcpkg repository. I also don't understand how the `ReadBarcodes()` function could not be included in this package. Maybe there is an issue on the users side and he is actually using an older vcpkg version?

**Comment by duanqn** [comment]
> It seems it's happening that, in my vcpkg.json im not setting any version, I was assuming it will get the lastest, i tryed to specify >= 1.3.0 but I'm still getting 1.2.0 ...

If that's the case, it looks like a vcpkg issue rather than a ZXing-cpp issue. I would suggest opening an issue on vcpkg side.

**Comment by JaviBite** [comment]
Well I got it fixed! (cache stuff) im closing this
Thank you!!

**Comment by duanqn** [comment]
> Also maybe it's time to bump to 1.4.0...

Done through https://github.com/microsoft/vcpkg/pull/27705 😎
