### ISSUE TITLE
Current 1.4.0 release not installable via pip in Python 3.11

### ISSUE THREAD

**Issue by cbm755** [zxing-cpp/zxing-cpp#436]
I had previous filed #429, which is technically fixed: `main` builds fine.

But `pip install zxing-cpp` currently fails:
  - there is no wheel
  - so it tries to download the 1.4.0.tar.gz and that fails b/c of #429.

**Comment by cbm755** [comment]
For contrast, on Python 3.10 there is a wheel.
```
# pip install zxing-cpp
Defaulting to user installation because normal site-packages is not writeable
Collecting zxing-cpp
  Using cached zxing_cpp-1.4.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (964 kB)
Requirement already satisfied: numpy in /usr/lib64/python3.10/site-packages (from zxing-cpp) (1.22.0)
Installing collected packages: zxing-cpp
Successfully installed zxing-cpp-1.4.0
```

- - - -
It is also possible to build without the `.whl` on Python 3.10, although for me some tests failed (I didn't really dig into it b/c the wheel works fine)
```
# pip install zxing-cpp==1.4.0 --verbose --no-binary :all:
```

**Comment by axxel** [comment]
As established in #429 version 1.4 does not build on python 3.11 because of the pybind dependency. Hence, there is also no wheel for 3.11 released for 1.4. `pip install zxing-cpp` will only start working on pyhton 3.11 after the next zxing-cpp release. Unfortunately, I'm rather busy at the moment and can't promise an immediate release.

**Comment by axxel** [comment]
2.0.0 wheels are not uploaded to pypi.org for python 3.9, 3.10 and 3.11.

**Comment by cbm755** [comment]
"now uploaded".

Thanks for the fix, I confirm it works.

**Comment by axxel** [comment]
> "now uploaded".

Ahh, how much difference this one letter can make :). (fixed in my comment). Thanks for testing and confirming.
