### ISSUE TITLE
Get raw data from datamatrix code

### ISSUE THREAD

**Issue by goodbooroondook** [zxing-cpp/zxing-cpp#439]
Hello!

Is it possible to get raw data without any modification from results after decoding?

For example:,
Original code data: <(FNC1)>0108691234567890211323424679<(FNC1)>1707011910X2512061322,
Decoded data: ]d20108691234567890211323424679<(GS)>1707011910X2512061322.

Yes, this modification happen according standard, but it would be useful to keep information about original data for some tasks.

As I can see in DMDecoder.cpp, all FNC symbols are replacing (first by special modifier ]d2, next by GS symbol).

One way is modify source code to keep original data, but maybe there are some settings for output data format which can help?

Best regards

**Comment by oehhar** [comment]
Dear goodbooroondook,
thank you for the question. What you call "raw data" may not be represented as a string.
The returned data is already the raw data.
What you observe in the code is an intermediate byte level, which is then transformed to the raw data.
For Data Matrix, you may get the Codewords, which give you full control and information. But the path to the raw data is quite far, as there are a couple of modes and subencodings involved. The same is true for QR code. To get an easy picture, you may look to Code128, where the possibilities are still limmited, but you already have not representable codewords like FNC1 to FNC4.
Take care,
Harald

**Comment by axxel** [comment]
The 'rawest' data you can extract from the library (current HEAD revision) is if you look at `Result::bytes()`. What you would see there is '0108691234567890211323424679<(GS)>1707011910X2512061322' where '<(GS)>' is the single byte with the value 29. That is the per definition the content of the symbol. If you want to get access to some 'random intermediate' bits, you'll have to modify the library yourself.
