### ISSUE TITLE
Questions about ThresholdBinarizer

### ISSUE THREAD

**Issue by duanqn** [zxing-cpp/zxing-cpp#442]
Hi I've been reading the code of ThresholdBinarizer and there are something I cannot understand. I would appreciate it if  anyone could provide some guidance.
1. I think the `getPatternRow` function of `ThresholdBinarizer` has some issues and the pattern row may not add up to width / height of the original image. I have prepared a fix at #441 .
2. It seems that `ThresholdBinarizer` is only working on the green channel of the original image? Why do we want this behaviour? (Other binarizers convert image to black/white in https://github.com/zxing-cpp/zxing-cpp/blob/master/core/src/ReadBarcode.cpp#L95)

**Comment by axxel** [comment]
ad 1: Thanks for the patch. You were right, there was an issue when reading a rotated pattern row.

ad 2: That is correct and I wanted this behavior to make the code fast. The main application of this binarizer is the 'pure' situation where you have some clean/generated input (usually strictly black/white) and there it is a substantial waste of cpu cycles to do an RGB -> Grey conversion first.

**Comment by duanqn** [comment]
Got it. Thanks.
