### ISSUE TITLE
Hanging while reading micro QR code

### ISSUE THREAD

**Issue by lindaluomsft** [zxing-cpp/zxing-cpp#443]
Sometimes, while scanning a micro QR code while aztec and micro QR code reading is enabled, the code will hang for a while. 
It seems that the code hangs while trying to determine whether the micro QR code is an aztec code. From a little digging, this while loop was suspicious: https://github.com/zxing-cpp/zxing-cpp/blob/master/core/src/aztec/AZDetector.cpp#:~:text=while%20(next%20%3D%20FindAztecCenterPattern(next)%2C%20next.isValid())%20%7B

These are a couple micro QR code that I observed the behavior with:
![abcMicroQR](https://user-images.githubusercontent.com/92536524/203661395-2f33fb47-6d11-4794-8609-6afd6a9a5cdc.gif)
![twoMicroQR](https://user-images.githubusercontent.com/92536524/203661399-5667f560-11f1-40f4-8050-4a4ceab9aca8.gif)

Any work around ideas? We considered adding a timeout, but it seems to make the aztec scanner less reliable. Thanks!

**Comment by axxel** [comment]
I can not reproduce any issue with either of the two images. Can you provide a command line based on the `ZXingReader` binary that shows the problem with the current HEAD revision?

**Comment by lindaluomsft** [comment]
Hi,
We captured some images to help repro the issue caused when scanning a micro QR code while aztec code reading is enabled. I've attached an image of a micro QR code that my mobile device's camera recorded when it started hanging (named microQR_repro). When running this through the ZXingReader sample app in a debug build, the assert here went off: https://github.com/zxing-cpp/zxing-cpp/blob/698a7c534bfe5537e4ecbf64a2b3e82416f279b0/core/src/RegressionLine.h#:~:text=assert(l1.isValid()%20%26%26%20l2.isValid())%3B

We then ran the ZXingReader sample app on a release build (to get around the assert()) and ran a comparison between a micro QR code image (that had showed strange behavior, named microQR_repro) compared to a code128 image (that always ran reliably, named code128_control). Since we previously observed that the code would hang while determining whether a micro QR code was an Aztec code, we recorded how long it took the Aztec reader to determine that the images were not Aztec codes.
Running the microQR_repro image took 170 milliseconds to recognize that there was no Aztec code and 28 milliseconds for the code128_control image. (These times were retrieved by using commands like: `time ./ZXingReader -format Aztec ~/testImage.bmp`)
Further, we recorded the actual time spent during scanning, and the aztec scanner spent 138 milliseconds to determine the microQR_repro image was not an Aztec code, versus the code128_control image which only took 9 milliseconds. 
It seems concerning that the microQR_repro image hits the assert mentioned in RegressionLine.h as well as experiences slower processing times, but hopefully what I've provided can help repro the issue. We're also on a branch of zxing that branched off at commit baffb89 if that's helpful as well.

![microQR_repro](https://user-images.githubusercontent.com/92536524/205212492-61ef3d28-8566-462b-925b-c55cc7f2be32.png)
![code128_control](https://user-images.githubusercontent.com/92536524/205212491-b677e2cb-a800-421a-bf1d-c71db5963a01.png)

**Comment by axxel** [comment]
Can you confirm that HEAD fixes your issue?

**Comment by lindaluomsft** [comment]
Yes, I confirmed that switching to HEAD, the hanging issue disappeared. Occasionally it is a little slow to pick up a micro QR code, but overall it seems that the main issue has been resolved. Thanks, and apologies for the delayed response!
