### ISSUE TITLE
Question about zueci.h

### ISSUE THREAD

**Issue by siddi2022** [zxing-cpp/zxing-cpp#445]
Compilation Error: TextDecoder.cpp prompts that zeuci.h is missing. It is a three-party library that zxing depends on. Do I need to download it? I can't find zeuci.h online.

**Comment by duanqn** [comment]
It should be automatically downloaded here https://github.com/zxing-cpp/zxing-cpp/blob/master/core/CMakeLists.txt#L8

**Comment by siddi2022** [comment]
zxing_add_package(zueci zueci https://git.code.sf.net/p/libzueci/code master)
I cannot open the website https://git.code.sf.net/p/libzueci/code.

**Comment by duanqn** [comment]
Me neither. Probably should let @axxel take a look.

**Comment by siddi2022** [comment]
Thank you. It has been compiled successfully with code here: 
https://github.com/zxing/zxing/tree/00f634024ceeee591f54e6984ea7dd666fab22ae/cpp

**Comment by axxel** [comment]
If I access https://git.code.sf.net/p/libzueci/code in my web browser, I get a blank page. Maybe you guys interpret that as an error. What is important is that git cloning that url works. Please try `git clone https://git.code.sf.net/p/libzueci/code` on a console. This works here without an issue.

This sourceforge based sub-project inclusion will be replaced by something less troublesome (did not have the time, yet...)

@siddi2022 the code from the link you provided is something completely different. It is a very outdated original c++ port of the Java code.
