### ISSUE TITLE
[hacking] unreadable code.

### ISSUE THREAD

**Issue by zander** [zxing-cpp/zxing-cpp#450]
Hello,

I'm trying to use your project in my application and noticed some "TODOs" in the Qt file: `ZXingQtReader.h`

Since I know how to solve them, I thought it would be a nice half an hour project to do so.

Quickly I noticed that you use some weird construction called ZX_PROPERTY using a pre-processor hack. Not just in the example, but also in `core/src/DecodeHints.h` for instance.

I ended up giving up, the code is unreadable and can not be followed by a C++ developer of 30 years (me).

What is the problem with just writing out the boilerplate (or use the QtCreator IDE which makes them for you) in order for the result to be simple, standard and readable, cpp?

ps. I tried to figure out what in `ZXingQtReader.cpp` on line `.setFormats(BarcodeFormat::Any)` 
that "Any" refers to.

**Comment by axxel** [comment]
> Since I know how to solve them...

I'd love to hear how to solve them.



> I ended up giving up, the code is unreadable and can not be followed by a C++ developer of 30 years (me).

Sorry to hear that.

> What is the problem with just writing out the boilerplate

The problem is that the code becomes less readable and less maintainable (by me) then.

> I tried to figure out what in `ZXingQtReader.cpp` on line `.setFormats(BarcodeFormat::Any)`
> that "Any" refers to.

`setFormats()` sets a filter and passing it `Any` means "find any symbol, whatever format it may have".

**Comment by zander** [comment]
> The problem is that the code becomes less readable and less maintainable (by me) then.

You find extremely simple getters and setters using only plain-simple CPP hard to read? Well, ok...

**Comment by zander** [comment]
https://cplusplus.com/doc/tutorial/preprocessor/

> Because preprocessor replacements happen before any C++ syntax check, macro definitions can be a tricky feature. But, be careful: **code that relies heavily on complicated macros become less readable**, since the syntax expected is on many occasions different from the normal expressions programmers expect in C++.
