### ISSUE TITLE
QRCode and error correction level 

### ISSUE THREAD

**Issue by FalsinSoft** [zxing-cpp/zxing-cpp#456]
Hi

May I know why the error correction level is changed in this way in case of QRCode?

```
auto QRCodeEccLevel = [&](QRCode::Writer& writer, int eccLevel) {
     writer.setErrorCorrectionLevel(static_cast<QRCode::ErrorCorrectionLevel>(--eccLevel / 2));
};
```

This inside the MultiFormatWriter.cpp file, function encode(). Since error correction level are in the range from 0 to 3 this code always modify the requested error correction level param different from original one by downgrade it. Is there a particular reasons for this or is a bug?
Thank you

**Comment by FalsinSoft** [comment]
Hi

However this is the definition of qrcode error correction levels inside the file QRErrorCorrectionLevel.h as follow:

enum class ErrorCorrectionLevel
{
	Low,     // L = ~7 % correction
	Medium,  // M = ~15% correction
	Quality, // Q = ~25% correction
	High,    // H = ~30% correction
	Invalid, // denotes in invalid/unknown value
};

Compiler assign 0 to Low and progressively to other level until High that is 3. This mean the range is from 0 to 3 and with the "downgrade" change reported in the first post the result is each request of qtcode from Low to High return always the Low qrcode version (this is the reasons I noted the problem).

**Comment by axxel** [comment]
The API you are using does not take `ErrorCorrectionLevel` but `int` in the range 0..8. The bug is in your code.

**Comment by FalsinSoft** [comment]
Probably I didn't understand correctly how to use the library. I need to generate a QRCode with error level Q and this is my code:

```
ZXing::MultiFormatWriter qrCodeWriter(ZXing::BarcodeFormat::QRCode);
qrCodeWriter.setEccLevel(ZXing::QRCode::ErrorCorrectionLevel::Quality);
qrCodeWriter.setEncoding(ZXing::CharacterSet::UTF8);
qrCodeWriter.setMargin(0);
qrCodeWriter.encode("qrcode content text example", 512, 512));

```
This code generate the problem in topic. Is there something wrong on it?

**Comment by axxel** [comment]
I know it is not straight forward and the fact that an enum is silently cast to an int is contributing the problem. The correct way to get what you want is:
```
qrCodeWriter.setEccLevel(6);
```

**Comment by FalsinSoft** [comment]
Ok, I got it. So correction level are H=8, Q=6, M=4 and L=2.
Thank you and sorry for the issue opened without real reasons
