### ISSUE TITLE
INT_MAX, INT_MIN

### ISSUE THREAD

**Issue by pictview** [zxing-cpp/zxing-cpp#461]
When building on Linux, we get INT_MAX and INT_MIN used in Result.cpp unresolved.
I would suggest to add #include <climits> to Result.cpp.

**Comment by axxel** [comment]
Those symbols are not used anywhere in the whole project (in current HEAD). Can you provide the whole error message including the file and line number?

**Comment by pictview** [comment]
Eh, my bad. These symbols are actually used in our custom modification :-(
I am sorry, please disregard.
