### ISSUE TITLE
various pattern for detect pattern

### ISSUE THREAD

**Issue by KwangSon** [zxing-cpp/zxing-cpp#466]
Hi all, thanks for this good quality of codes.

I want to know that Is it ok to make PR for various pattern for anchor(detect pattern or eye frame shape).
It seem this repo only allowed standard QR code generation.

like,
https://www.qrcode-monkey.com/

**Comment by axxel** [comment]
Thanks for your offer to contribute. I'm currently not interested in adding this functionality. That has two reasons:
1) The standard explicitly specifies how those finder patterns are to be rendered. I had trouble trying to modify the detector such that it also works with non-standard input. I don't want to encourage people in generating even more non-standard symbols.
2) The generator part will likely be replaced with a new backend based on the zint project (see #332). So any changes to the current code in that part would get lost then.

**Comment by KwangSon** [comment]
Thanks for good information. all solved.
