### ISSUE TITLE
Barcode not recognized

### ISSUE THREAD

**Issue by duanqn** [zxing-cpp/zxing-cpp#479]
Hi, I need help with one of my barcode images. It looks clean but cannot be recognized by ZXing-cpp. I don't know what standard it is. Could someone provide some insights?

![0](https://user-images.githubusercontent.com/21275667/211522574-6b3fd042-4e4e-4136-9e47-8db9cefc823d.png)

**Comment by duanqn** [comment]
Another image:
![1](https://user-images.githubusercontent.com/21275667/211525474-c7748772-3b54-4611-8cfe-c65a96f01231.png)

Thanks in advance~

**Comment by axxel** [comment]
Those seem to be Code128 symbols with insufficient resolution / pixel gracing. It is basically the same issue as discussed in your earlier PDF sample [here](https://github.com/zxing-cpp/zxing-cpp/issues/454#issuecomment-1338796691). The code is simply invalid.

**Comment by duanqn** [comment]
Got it. Thank you.
I have another sample though. I think there's no pixel grazing in this image. It should be a Code128 of "X000FXCF67". I generated the code with Zint and all the bars look OK. It still cannot be recognized with ZXing-cpp.
![0](https://user-images.githubusercontent.com/21275667/211727588-a3485fe4-1bc7-41bf-925e-e48878f20553.png)

**Comment by duanqn** [comment]
Another one... sorry for bothering with so many images at once. It should be a Code 128 of "MCD181800" but I can't generate the same bars with Zint. Is the code invalid or is it due to something else?
![0](https://user-images.githubusercontent.com/21275667/211740714-ce66b34d-2f34-4cad-a927-6e9fb1d98bd9.png)

**Comment by duanqn** [comment]
Here is another image. I cannot recognize this with ZXing, but another scanner app on my phone can scan it and reports its content as "]C1ES5300001". I'm confused because I don't know where this "]C1" comes from. The code is Code128.

![2](https://user-images.githubusercontent.com/21275667/211751295-5efb29c9-0da9-4bf1-8139-8b438367510e.png)

**Comment by oehhar** [comment]
The "]C1" is the symbology ID. It is a mandatory part of the returned data and should always be there.
It tells you, that Code 128 without GS1 or other features were scanned.

**Comment by duanqn** [comment]
Thank you Harald. Does that mean I should include the "]C1" in the data when I'm generating the barcode too? If I does this, Zint gives me something completely different:
![image](https://user-images.githubusercontent.com/21275667/211754620-d32b3b1c-97e5-4a20-8491-86050b0e8e17.png)

Without "]C1", the generated code is closer to what I have but still different:
![image](https://user-images.githubusercontent.com/21275667/211754747-8daae98f-c5f2-43ca-a074-b16e0905c16f.png)

**Comment by oehhar** [comment]
No. This is not data. The fact, that you generate a Code128 (-b parameter of zint) will generate this information.
The scanner should always add a prefix consting of

- "]" : fix data
- c : A character identifying the symbology. Examples are C: Code128, A:Code39, q: QR-Code
- m: a character giving additional information. In this case, there is a "1", which indicates a GS1 code.

I verified the code. It is a GS1-128 (as identified by the modifier).

If you have used zint, then the GS1 mode was activated. But zint will not allow you to create this data, as it is invalid following GS1 rules.

The difference between Code128 and GS1-128 is, that the first character of the codeword stream encoded is a "FNC1" "character". This "fnc1" will modify the symbology ID and change it from"]C0" to "]C1".

Sorry, complicated...

Take care,
Harald

**Comment by oehhar** [comment]
Yes. To my knowledge, zxing-cpp can verify GS1 data and may invalidate this code.

The code is complicated, as mostly, you do not recognize, that there is GS1 mode included.
Most scanners are configured to just output data. And then, you dont see the difference, as GS1 mode only modifies the Symbology ID. Due to that, it is recommended to always activate the output of a symbology ID.

**Comment by axxel** [comment]
> X000FXCF67

The problem is the shadow on the left side. the GlobalHistogramBinarizer finds a threshold of around 160. With a manual value of 85 hacked into the code it works. There is room for improvement in this corner.

> MCD181800

The code seems invalid to me:  the small black lines are just too small, e.g. the first 3 bars/spaces are supposed to have the ratio 2:1:1 while in this code they are 4:4:1.

> ES5300001

works just fine here with `ZXingReader`:
```
Text:       "ES5300001"
Bytes:      45 53 35 33 30 30 30 30 31
Format:     Code128
Identifier: ]C1
Content:    GS1
HasECI:     false
Position:   33x10 297x10 297x54 33x54 
Rotation:   0 deg
IsMirrored: false
IsInverted: false
Lines:      45
```

**Comment by duanqn** [comment]
Thanks a lot axxel, I wish I knew as much about barcodes as you guys!

> The problem is the shadow on the left side. the GlobalHistogramBinarizer finds a threshold of around 160. With a manual value of 85 hacked into the code it works. There is room for improvement in this corner.

Does the threshold for GlobalHistogramBinarizer apply to the entire image, or just a horizontal line? If it applies to the entire image, then I guess a workaround is to binarize this image manually, and then feed the Lum format data into ZXing-cpp?

**Comment by duanqn** [comment]
I hate to further bother you guys, but I have another image and I need some expert knowledge...

![0](https://user-images.githubusercontent.com/21275667/211784901-8156e634-1231-4b3b-a0d8-081a6961dc66.png)

 I did some research and learned that Code 128 subtype A starts with this pattern
![image](https://user-images.githubusercontent.com/21275667/211785193-d5b3141b-2f26-4e08-a571-f203e579862d.png)
where the width ratio is 2:1:1:4:1 for the first bars & gaps. But in the image, the first gap is narrower than the bar to the right of it. So I guess this is another example of pixel grazing right? The black bars appears thicker and occupies some space of the white area.

**Comment by axxel** [comment]
> Does the threshold for GlobalHistogramBinarizer apply to the entire image, or just a horizontal line?

just one line. but here this line is dark on the left and bright on the right. You may very well do a binarization with some other algorithm beforehand and then feed the result to `zxing-cpp` and get a valid scan in this case.

> I was testing with the web demo

I see, that demo is totally outdated at the moment.

> I have another image and I need some expert knowledge...

That also decodes just fine with 2.0.

> But in the image, the first gap is narrower than the bar to the right of it.

Yes, but up to a certain limit, this is not an issue. In fact my recent improvement of the code128 decoder that I added last week improved the detection rate in this context significantly. But as stated in #437 there is more work to be done.

**Comment by duanqn** [comment]
> I see, that demo is totally outdated at the moment.

Got it. I have switched to using the ZXingReader program built from master branch (commit 1df2b291349b64a5b966b527142522873a690939).

I have a few PDF417 codes that looks OK but cannot be recognized

![0](https://user-images.githubusercontent.com/21275667/212017955-0a69b5fc-8649-4d7e-b96f-7399fd3d5936.png)
-------------------------------
![1](https://user-images.githubusercontent.com/21275667/212021271-5ca7633e-1bc7-4dee-a2a7-673db4022e07.png)
-------------------------------
![1](https://user-images.githubusercontent.com/21275667/212025040-c501b725-d51d-4ca1-82aa-6a74c8b5bec2.png)


I would greatly appreciate it if anyone could provide some valuable insights. Thanks!

**Comment by duanqn** [comment]
I also have a curious sample of Code 128. The first half of the code looks like a valid Code128 of "31891774", and it is mirrored after that (perhaps to enable 2-way scanning).
Currently, ZXing-cpp does not find any barcode. The bars look pretty valid and I wonder if ZXing-cpp is misled by the mirroring.

![1](https://user-images.githubusercontent.com/21275667/212028122-ba7f863c-cf7f-48cc-bbb6-c35cd1ab6fd8.png)
<img width="162" alt="image" src="https://user-images.githubusercontent.com/21275667/212028203-700fef3a-51b8-42c5-8e7a-1ca6dedf700c.png">
