### ISSUE TITLE
Code 128 with insufficient quiet zone fails to decode in pure mode

### ISSUE THREAD

**Issue by vkrause** [zxing-cpp/zxing-cpp#480]
The attached sample decodes in normal mode but fails in pure mode. I suspect that's related to the insufficient quiet zone, as extending that manually makes it work.

One can of course argue that this is a bug in the input data rather than ZXing (and I'd not disagree), reporting this here nevertheless based on the discussion in https://github.com/zxing-cpp/zxing-cpp/discussions/470#discussioncomment-4614300.

![code128-insufficient-quiet-zone](https://user-images.githubusercontent.com/629750/211608362-cf072777-7004-4a94-a2c1-9cbc028b18a4.png)

**Comment by axxel** [comment]
If I process this with `ZXingReader -format code128 -ispure` it decodes just fine. Sure you got the write sample?

**Comment by vkrause** [comment]
You are right of course, I should have checked that before rather than relying on our code and jumping to conclusion from seeing that toggling the "is pure" setting in our diagnostic tool made a difference. Turned out to be an embarrassingly simple issue in our code... I'm very sorry about the noise!

**Comment by axxel** [comment]
Glad I could be of help :). Does this mean, you don't have any samples left that currently don't work with HEAD?

**Comment by vkrause** [comment]
Correct, all the remaining ones turned out to be bugs on our side.
