### ISSUE TITLE
2.0.0 does not provide wheels for Python 3.8

### ISSUE THREAD

**Issue by cbm755** [zxing-cpp/zxing-cpp#488]
I'm building on Ubuntu 20.04 which still has Python 3.8, and I notice it builds from source.  

Is that intentional?  See https://pypi.org/project/zxing-cpp/2.0.0/#files where only Python 3.9 -- 3.11 are shown.

Relatedly, what is the minimum supported Python version?

**Comment by axxel** [comment]
> Is that intentional?

Yes. At some point in the past I made the (more or less informed decision) that shipping wheels for the most recent 3 python versions would be the way to go. I see how that is annoying if you are an Ubuntu LTS user.

> Relatedly, what is the minimum supported Python version?

That is a good question. It is basically dependent on what pybind11 thinks about this matter. I would imagine that 3.0 still works but I have no clue. That said, `setup.py` actually `python_requires=">=3.6"`. But I don't remember where that number comes from.

**Comment by cbm755** [comment]
thanks for confirming that 3.8 is in principle supported.

I guess nothing else to do here, so closing.
