### ISSUE TITLE
CTest fails on Ubuntu 20.04 build with gcc 10

### ISSUE THREAD

**Issue by StenBone** [zxing-cpp/zxing-cpp#496]
Tests within *TextUtfEncodingTest.cpp* fail when running CTest. Only tests within that one file.

System info:

> NAME="Ubuntu"
> VERSION="20.04.4 LTS (Focal Fossa)"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Ubuntu 20.04.4 LTS"
> VERSION_ID="20.04"
> HOME_URL="https://www.ubuntu.com/"
> SUPPORT_URL="https://help.ubuntu.com/"
> BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
> PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
> VERSION_CODENAME=focal
> UBUNTU_CODENAME=focal
> g++ (Ubuntu 10.3.0-1ubuntu1\~20.04) 10.3.0
> gcc (Ubuntu 10.3.0-1ubuntu1\~20.04) 10.3.0

zxing-cpp info:

> Built from "v1.4.0" tag, commit f89db69e34543c508f80e807535dab3012eea7ad.

Unit Tests Logs:

> [----------] 1 test from TextUtfEncodingTest
> [ RUN      ] TextUtfEncodingTest.ToUtf8AngleEscape
> /root/.conan/1.43/.conan/data/zxing-cpp/1.4.0-1/aligntech/stable/source/src/test/unit/TextUtfEncodingTest.cpp:30: Failure
> Expected equality of these values:
>   std::setlocale(0, __null)
>     Which is: "C"
>   "en_US.UTF-8"
> /root/.conan/1.43/.conan/data/zxing-cpp/1.4.0-1/aligntech/stable/source/src/test/unit/TextUtfEncodingTest.cpp:36: Failure
> Expected equality of these values:
>   ToUtf8(L"\u00B6\u0416", angleEscape)
>     Which is: "<U+B6><U+0416>"
>   "¶Ж"
>     Which is: "\xC2\xB6\xD0\x96"
>     As Text: "¶Ж"
> /root/.conan/1.43/.conan/data/zxing-cpp/1.4.0-1/aligntech/stable/source/src/test/unit/TextUtfEncodingTest.cpp:38: Failure
> Expected equality of these values:
>   ToUtf8(L"\u2602", angleEscape)
>     Which is: "<U+2602>"
>   "☂"
>     Which is: "\xE2\x98\x82"
>     As Text: "☂"
> /root/.conan/1.43/.conan/data/zxing-cpp/1.4.0-1/aligntech/stable/source/src/test/unit/TextUtfEncodingTest.cpp:47: Failure
> Expected equality of these values:
>   ToUtf8(L"\u0100", angleEscape)
>     Which is: "<U+0100>"
>   "Ā"
>     Which is: "\xC4\x80"
>     As Text: "Ā"
> /root/.conan/1.43/.conan/data/zxing-cpp/1.4.0-1/aligntech/stable/source/src/test/unit/TextUtfEncodingTest.cpp:48: Failure
> Expected equality of these values:
>   ToUtf8(L"\u1000", angleEscape)
>     Which is: "<U+1000>"
>   "က"
>     Which is: "\xE1\x80\x80"
>     As Text: "က"
> /root/.conan/1.43/.conan/data/zxing-cpp/1.4.0-1/aligntech/stable/source/src/test/unit/TextUtfEncodingTest.cpp:51: Failure
> Expected equality of these values:
>   ToUtf8(L"\uFFFD", angleEscape)
>     Which is: "<U+FFFD>"
>   "�"
>     Which is: "\xEF\xBF\xBD"
>     As Text: "�"
> /root/.conan/1.43/.conan/data/zxing-cpp/1.4.0-1/aligntech/stable/source/src/test/unit/TextUtfEncodingTest.cpp:57: Failure
> Expected equality of these values:
>   ToUtf8(L"\U00010000", angleEscape)
>     Which is: "<U+10000>"
>   "𐀀"
>     Which is: "\xF0\x90\x80\x80"
>     As Text: "𐀀"
> [  FAILED  ] TextUtfEncodingTest.ToUtf8AngleEscape (0 ms)
> [----------] 1 test from TextUtfEncodingTest (0 ms total)

From what I can see tests that define the correct output directly with the actual UTF-8 character fail, whereas tests which define the character with the "<U+XXXX>" format do not. 
"𐀀" vs "<U+00010000>"

**Comment by axxel** [comment]
It seems to me, this is basically the same issue as discussed in #405. There was also another discussion somewhere with a similar subject and there the problem was a missing `en_US.UTF-8` locale on the system. Please note that this issue is fixed either way in 2.0 (and will not be backported to 1.4).

I noticed that you seem to be building this via the conan package manager. Which conan package version did you try to build? They provide a "2.0" package now, but unfortunately there is a bug in their package metadata, see [my PR](https://github.com/conan-io/conan-center-index/pull/15357) which is currently stuck it seems.

**Comment by StenBone** [comment]
Appreciate the swift response @axxel! I am using Conan version 1.43.2.

**Comment by StenBone** [comment]
We determined that the problem was caused by our build environment not having any locales configured. After installing “locales-all/focal-updates 2.31-0ubuntu9.9 amd64” and running “sudo dpkg-reconfigure locales”, the unit tests now pass without error. I will close this issue.

**Comment by axxel** [comment]
Good to hear.

> I am using Conan version 1.43.2.

I was not referring to the version of Conan but the version of the zxing-cpp package of Conan (see [here](https://github.com/conan-io/conan-center-index/blob/master/recipes/zxing-cpp/config.yml))

I have no idea how Conan works but assume that you can select the package version independent of the Conan version.

**Comment by StenBone** [comment]
My apologies, we are using "1.4.0" of zxing-cpp.

**Comment by axxel** [comment]
So you deliberately chose to use 1.4.0? May I ask why?
