### ISSUE TITLE
No stack guard for Windows?

### ISSUE THREAD

**Issue by duanqn** [zxing-cpp/zxing-cpp#502]
I noticed that the CMakeLists.txt overrides default compiler options on Windows to disable the stack guard (/GS-).
I understand that this can give us performance benefits, but the security aspect is also important to some users. Also, we don't override the stack guard config when compiling on other OS / platforms. It creates some inconsistency.

Can we make this switch optional?

**Comment by duanqn** [comment]
I made a PR at #503 . Feel free to change the name of the CMake option. I can't come up with a good one.

**Comment by axxel** [comment]
I personally do not particularly care about the windows builds. Those settings all have been originally introduced by @huycn. Do you have an opinion on the matter? I'd actually rather use the compiler default setting (enable the stack guard) than to introduce another build option.

**Comment by duanqn** [comment]
> Do you have an opinion on the matter?

I also prefer to enable the stack guard.

**Comment by axxel** [comment]
@huycn What do you say? Do you remember why you chose this set of options?

While we are at it: are those manual `CXX_FLAGS` for windows really a good idea?
```
if (MSVC)
    option (LINK_CPP_STATICALLY "MSVC only, link standard library statically (/MT and /MTd)" OFF)

    add_definitions (-DUNICODE -D_UNICODE -D_CRT_SECURE_NO_WARNINGS)
    set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /MP")
    set (CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} /Oi /GS-")
    set (CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} /Oi /GS-")
    if (LINK_CPP_STATICALLY)
        set (CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} /MT")
        set (CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} /MT")
        set (CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} /MTd")
        set (CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} /MTd")
    endif()
endif()
```

I had quick look at the /Oi option: that can certainly be dropped as it is implicit in /O2, which I assume is the default for a release build?

Also the static linking options are aparrently set as follows nowerdays (starting with cmake version 3.15, which I am happy to set as a minimum): `set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")`
