### ISSUE TITLE
C++20 char8_t detection (core/src/Utf.cpp)

### ISSUE THREAD

**Issue by omascia** [zxing-cpp/zxing-cpp#515]
May I suggest changing this, in the beginning of file core/src/Utf.cpp:

``` c++
// TODO: c++20 has char8_t
#if __cplusplus <= 201703L
using char8_t = uint8_t;
#endif
```

into this :
``` c++
// C++20 has type char8_t and the macro __cpp_char8_t is predefined.
#if !defined(__cpp_char8_t)
using char8_t = uint8_t;
#endif
```

**Comment by axxel** [comment]
May I ask why you would want to change this?

**Comment by omascia** [comment]
char8_t as a predefined type has been introduced by C++20.
At the same time, C++20 introduces many feature-test macros, among which __cpp_char8_t, to confirm availability of char8_t as a predefined type. So, compiling on a C++17 environnement should not have __cpp_char8_t defined.
I find it cleaner than comparing for <= 201703 which people have to remember being the "release" date of C++17.
The comment I wrote before the test should not even be needed, the test self describes the intent: "if cpp does not provide char8_t we supply it".

**Comment by axxel** [comment]
So your argument for a change is basically of cosmetic nature, right? In theory I would agree with you but there were some annoying issues in the past where the NDK did advertise c++17 support but then not properly provide the feature macros it was supposed to. That experience is making me hesitant...

**Comment by omascia** [comment]
Then I understand your hesitation, the matter is nothing really important : it can be left as is.

I talked with a co-worker on our Windows team (and with experience with Visual Studio) this morning. He confirmed the following: without intentionally adding a compiler switch (/Zc:__cplusplus), the value of __cplusplus is hardcoded at 199711, no matter what language level is chosen.  Apparently [Microsoft did it on (their) purpose:](https://developercommunity.visualstudio.com/t/-cplusplus-always-199711/1445222#TPIN-N1445753)

Generally, testing for versions (<, >, <=, ...) is always weaker than testing for features avail/not-avail. No code should ever test "Am I being compiled as C++17 or else?" but rather test "Is this feature available or not?".  And I get you agree with that, except that you got caught before (NDK at some point in time).

So I guess anybody using VisualStudio, in C++20 mode or C++23 quite soon, will quickly understand how to adjust the #ifdef __cplusplus or add their own compiler required switch to get it to report a more compliant value. My friend and co-worker says we probably should not bother with that. :)

**Comment by axxel** [comment]
> without intentionally adding a compiler switch (/Zc:__cplusplus), the value of __cplusplus is hardcoded at 199711

Ah, remember having heard that before. So this proposed change is indeed not merely cosmetic at all but will fix a broken build (msvc + c++20)? I see two options:

a) make the change you proposed
b) add the `/Zc` flag when building with msvc

I'm inclined to go for option b) as it will prevent me from running into this issue at another time. From my understanding a c++17 conforming compiler is required to define `__cplusplus == 201703L`. Would that immediately fix your problem or would you still require option a?

**Comment by omascia** [comment]
Well... If MS decided to keep __cplusplus hardcoded by default at 199711 because not doing so, "it broke many third-party libraries", I suppose it is meaningful in their galaxy and not requiring users of Visual Studio to add /Zc:__cplusplus would be better (assuming people actually compiling ZXing code by themselves).

For the build procedure of ZXing itself using MS compilers, I would go the route you suggest of adding /Zc:__cplusplus.

Others can surely find the issue and fix it locally if they do the work of compiling the code as part of their own building procedure, and not stand-alone then linked.

**Comment by duanqn** [comment]
@axxel , would you recommend setting `/Zc:__cplusplus` in CMakeLists.txt of this repo?

**Comment by duanqn** [comment]
Nevermind... I just found out it had been fixed already.
