### ISSUE TITLE
DataBar can cause a failed `lineCount == 1` assertion

### ISSUE THREAD

**Issue by ptc-brainer** [zxing-cpp/zxing-cpp#516]
I encountered an issue where the detection of a PDF417 returned a lineCount of 0 for a barcode that slightly overlaps with the image border. Subsequently, [this](https://github.com/zxing-cpp/zxing-cpp/blob/1f64d0961477bc056830fab758a3d3c39d115446/core/src/Result.cpp#L145) assertion is hit in debug builds, (or builds with assertions enabled). 

I don't know if this check is too strict or if the lineCount extraction in PDF417 is not working properly, but the combination of both causes this behaviour. 

The following image hits this assertion in the ZXingReader app:
![frame_00113 color](https://user-images.githubusercontent.com/69149788/219069593-935cb706-327f-4f7e-a1e8-c4317f4db026.png)

**Comment by axxel** [comment]
Thanks for reporting this issue. I can reproduce the failed assertion you mentioned but it has nothing to do with the PDF417 symbol but the DataBar symbol. How did you come to this conclusion? What where the `ZXingReader` command line parameters you used?

**Comment by ptc-brainer** [comment]
Thanks for replying, I used the default settings in the ZXingReader example app (was able to verify this on MacOS and Windows). 
I suspected the PDF417 type because of the output of the ZXingReader app in Release mode showed that it had lineCount set to zero (Always print out the line count): 

```
Text:       "5901234123457"
Bytes:      35 39 30 31 32 33 34 31 32 33 34 35 37
Format:     EAN-13
Identifier: ]E0
Content:    Text
HasECI:     false
Position:   567x767 567x419 392x415 392x762 
Rotation:   -90 deg
IsMirrored: false
IsInverted: false
Lines:      61
Country:    PL

Text:       "00075678164125"
Bytes:      30 30 30 37 35 36 37 38 31 36 34 31 32 35
Format:     DataBar
Identifier: ]e0
Content:    Text
HasECI:     false
Position:   884x792 884x572 887x368 887x590 
Rotation:   -90 deg
IsMirrored: false
IsInverted: false
Lines:      2

Text:       "00075678164125"
Bytes:      30 30 30 37 35 36 37 38 31 36 34 31 32 35
Format:     DataBar
Identifier: ]e0
Content:    Text
HasECI:     false
Position:   890x792 890x575 1010x371 1010x593 
Rotation:   -90 deg
IsMirrored: false
IsInverted: false
Lines:      40

Text:       "(01)90614141000015(3202)000150"
Bytes:      30 31 39 30 36 31 34 31 34 31 30 30 30 30 31 35 33 32 30 32 30 30 30 31 35 30
Format:     DataBarExpanded
Identifier: ]e0
Content:    GS1
HasECI:     false
Position:   1343x950 1343x754 1424x350 1424x555 
Rotation:   -90 deg
IsMirrored: false
IsInverted: false
Lines:      6

Text:       "(01)90614141000015(3202)000150"
Bytes:      30 31 39 30 36 31 34 31 34 31 30 30 30 30 31 35 33 32 30 32 30 30 30 31 35 30
Format:     DataBarExpanded
Identifier: ]e0
Content:    GS1
HasECI:     false
Position:   1343x950 1343x754 1367x350 1367x554 
Rotation:   -90 deg
IsMirrored: false
IsInverted: false
Lines:      2

Text:       "Wikipedia"
Bytes:      57 69 6B 69 70 65 64 69 61
Format:     PDF417
Identifier: ]L2
Content:    Text
HasECI:     false
Position:   46x1071 46x775 182x780 187x1079 
Rotation:   -90 deg
IsMirrored: false
IsInverted: false
EC Level:   2
Lines:      0
```

**Comment by ptc-brainer** [comment]
Thanks for fixing this!
