### ISSUE TITLE
can't compile with Android Studio [CXX1405]

### ISSUE THREAD

**Issue by francoisnicolas** [zxing-cpp/zxing-cpp#524]
Can't build with Android Studio Electric Eel | 2022.1.1   with Gradle JDK 11 version 11.0.15
Here is the error messages :

failed
:app:createDebugVariantModel
:app:preBuild
:app:preDebugBuild
:app:mergeDebugNativeDebugMetadata
:zxingcpp:preBuild
:zxingcpp:preDebugBuild
:zxingcpp:compileDebugAidl
:app:compileDebugAidl
:zxingcpp:packageDebugRenderscript
:app:compileDebugRenderscript
:app:dataBindingMergeDependencyArtifactsDebug
:app:generateDebugResValues
:app:generateDebugResources
:zxingcpp:compileDebugRenderscript
:zxingcpp:generateDebugResValues
:zxingcpp:generateDebugResources
:zxingcpp:packageDebugResources
:app:mergeDebugResources
:app:generateDebugBuildConfig
:zxingcpp:writeDebugAarMetadata
:app:mapDebugSourceSetPaths
:app:createDebugCompatibleScreenManifests
:app:extractDeepLinksDebug
:zxingcpp:extractDeepLinksDebug
:zxingcpp:processDebugManifest
:zxingcpp:compileDebugLibraryResources
:zxingcpp:parseDebugLocalResources
:app:checkDebugAarMetadata
:zxingcpp:generateDebugBuildConfig
:zxingcpp:javaPreCompileDebug
:app:javaPreCompileDebug
:app:mergeDebugShaders
:app:compileDebugShaders
:app:generateDebugAssets
:zxingcpp:mergeDebugShaders
:zxingcpp:compileDebugShaders
:zxingcpp:generateDebugAssets
:zxingcpp:packageDebugAssets
:app:mergeDebugAssets
:app:compressDebugAssets
:app:processDebugJavaRes
:zxingcpp:processDebugJavaRes
:app:checkDebugDuplicateClasses
:app:processDebugMainManifest
:app:processDebugManifest
:app:processDebugManifestForPackage
:zxingcpp:generateDebugRFile
:app:desugarDebugFileDependencies
:app:dataBindingGenBaseClassesDebug
:app:mergeExtDexDebug
:app:mergeDebugJniLibFolders
:zxingcpp:compileDebugKotlin
:zxingcpp:configureCMakeRelWithDebInfo[arm64-v8a]
[CXX1405] error when building with cmake using G:\zxing-cpp-master\zxing-cpp-      <---------------------------------------
master\wrappers\android\zxingcpp\src\main\cpp\CMakeLists.txt: -- Detecting C compiler ABI info
:zxingcpp:compileDebugJavaWithJavac
:zxingcpp:bundleLibCompileToJarDebug
:zxingcpp:bundleLibResDebug
:zxingcpp:bundleLibRuntimeToDirDebug
:app:processDebugResources
:zxingcpp:mergeDebugJniLibFolders
:app:validateSigningDebug
:app:writeDebugAppMetadata
:app:writeDebugSigningConfigVersions
:app:mergeLibDexDebug
:app:compileDebugKotlin
:app:compileDebugJavaWithJavac
:app:mergeDebugJavaResource
:app:dexBuilderDebug
:app:mergeProjectDexDebug
[CXX1405] error when building with cmake using G:\zxing-cpp-master\zxing-cpp-         <---------------------------------------
master\wrappers\android\zxingcpp\src\main\cpp\CMakeLists.txt: -- Detecting C compiler ABI info

**Comment by axxel** [comment]
The error message you provided tells me nothing more than "it did not work". I would need something more specific to be able to help you.

**Comment by francoisnicolas** [comment]
Here, are the 2 lines in the compile window, where gradle says that there are error
[CXX1405] error when building with cmake using G:\zxing-cpp-master\zxing-cpp-
[CXX1405] error when building with cmake using G:\zxing-cpp-master\zxing-cpp- 
What is le version of android studio you use, and in project :
 android gradle version ?
gradle version ?

**Comment by axxel** [comment]
I noticed those 2 lines but they don't tell me anything about the cause the error. The "CXX1405" string hints at an issue with your cmake installation but I'm not sure. Which cmake version are you using?

I've used Android Studio 21.xx.xx until now. I just upgraded to 2022.1.1 Patch 2 and it still compiles fine. Then I upgraded the Android gradle plugin from 7.3.1 to version 7.4.2. which also upgraded gradle to 7.5. Still everything compiles just fine.

**Comment by francoisnicolas** [comment]
Yesterday I tried to compile with Android Studio.
I have read the README and installed JDK

https://www.oracle.com/java/technologies/downloads/#jdk19-windows

I go in this directory :  G:\zxing-cpp-master\zxing-cpp-master\wrappers\android>
and typed :  ./gradlew :zxingcpp:assembleRelease
I get these errors
PS G:\zxing-cpp-master\zxing-cpp-master\wrappers\android> ./gradlew :zxingcpp:assembleRelease

> Task :zxingcpp:configureCMakeRelWithDebInfo[arm64-v8a] FAILED
C/C++: CMake Error at C:/Users/auror/AppData/Local/Android/Sdk/cmake/3.22.1/share/cmake-3.22/Modules/CMakeTestCCompiler.cmake:69 (message):
C/C++:   The C compiler
C/C++:     "C:/Users/auror/AppData/Local/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe"
C/C++:   is not able to compile a simple test program.
C/C++:   It fails with the following output:
C/C++:     Change Dir: G:/zxing-cpp-master/zxing-cpp-master/wrappers/android/zxingcpp/.cxx/RelWithDebInfo/4z4y243u/arm64-v8a/CMakeFiles/CMakeTmp
C/C++:
C/C++:     Run Build Command(s):C:\Users\auror\AppData\Local\Android\Sdk\cmake\3.22.1\bin\ninja.exe cmTC_1e77b && [1/2] Building C object CMakeFiles/cmTC_1e77b.dir/testCCompiler.c.o
C/C++:     [2/2] Linking C executable cmTC_1e77b
C/C++:     FAILED: cmTC_1e77b
C/C++:     cmd.exe /C "cd . && C:\Users\auror\AppData\Local\Android\Sdk\ndk\23.1.7779620\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe --target=aarch64-none-linux-android21 --sysroot=C:/Users/auror/AppData/Local/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/windows-x86_64/sysroot -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fexceptions  -O2 -g -DNDEBUG -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--fatal-warnings -Qunused-arguments -Wl,--no-undefined  -Wl,--gc-sections CMakeFiles/cmTC_1e77b.dir/testCCompiler.c.o -o cmTC_1e77b  -latomic -lm && cd ."
C/C++:     ld: error: cannot open output file cmTC_1e77b: Function not implemented
C/C++:     clang: error: linker command failed with exit code 1 (use -v to see invocation)
C/C++:     ninja: build stopped: subcommand failed.
C/C++:
C/C++:
C/C++:
C/C++:   CMake will not be able to correctly generate this project.
C/C++: Call Stack (most recent call first):
C/C++:   CMakeLists.txt:2 (project)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':zxingcpp:configureCMakeRelWithDebInfo[arm64-v8a]'.
> [CXX1429] error when building with cmake using G:\zxing-cpp-master\zxing-cpp-master\wrappers\android\zxingcpp\src\main\cpp\CMakeLists.txt: -- Android: Targeting API '21' with architecture 'arm64', ABI 'arm64-v8a', and processor 'aarch64'
  -- Android: Selected unified Clang toolchain
  -- The C compiler identification is Clang 12.0.8
  -- The CXX compiler identification is Clang 12.0.8
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - failed
  -- Check for working C compiler: C:/Users/auror/AppData/Local/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
  -- Check for working C compiler: C:/Users/auror/AppData/Local/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe - broken
  -- Configuring incomplete, errors occurred!
  See also "G:/zxing-cpp-master/zxing-cpp-master/wrappers/android/zxingcpp/.cxx/RelWithDebInfo/4z4y243u/arm64-v8a/CMakeFiles/CMakeOutput.log".
  See also "G:/zxing-cpp-master/zxing-cpp-master/wrappers/android/zxingcpp/.cxx/RelWithDebInfo/4z4y243u/arm64-v8a/CMakeFiles/CMakeError.log".

  C++ build system [configure] failed while executing:
      @echo off
      "C:\\Users\\auror\\AppData\\Local\\Android\\Sdk\\cmake\\3.22.1\\bin\\cmake.exe" ^
        "-HG:\\zxing-cpp-master\\zxing-cpp-master\\wrappers\\android\\zxingcpp\\src\\main\\cpp" ^
        "-DCMAKE_SYSTEM_NAME=Android" ^
        "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON" ^
        "-DCMAKE_SYSTEM_VERSION=21" ^
        "-DANDROID_PLATFORM=android-21" ^
        "-DANDROID_ABI=arm64-v8a" ^
        "-DCMAKE_ANDROID_ARCH_ABI=arm64-v8a" ^
        "-DANDROID_NDK=C:\\Users\\auror\\AppData\\Local\\Android\\Sdk\\ndk\\23.1.7779620" ^
        "-DCMAKE_ANDROID_NDK=C:\\Users\\auror\\AppData\\Local\\Android\\Sdk\\ndk\\23.1.7779620" ^
        "-DCMAKE_TOOLCHAIN_FILE=C:\\Users\\auror\\AppData\\Local\\Android\\Sdk\\ndk\\23.1.7779620\\build\\cmake\\android.toolchain.cmake" ^
        "-DCMAKE_MAKE_PROGRAM=C:\\Users\\auror\\AppData\\Local\\Android\\Sdk\\cmake\\3.22.1\\bin\\ninja.exe" ^
        "-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=G:\\zxing-cpp-master\\zxing-cpp-master\\wrappers\\android\\zxingcpp\\build\\intermediates\\cxx\\RelWithDebInfo\\4z4y243u\\obj\\arm64-v8a" ^
        "-DCMAKE_RUNTIME_OUTPUT_DIRECTORY=G:\\zxing-cpp-master\\zxing-cpp-master\\wrappers\\android\\zxingcpp\\build\\intermediates\\cxx\\RelWithDebInfo\\4z4y243u\\obj\\arm64-v8a" ^
        "-BG:\\zxing-cpp-master\\zxing-cpp-master\\wrappers\\android\\zxingcpp\\.cxx\\RelWithDebInfo\\4z4y243u\\arm64-v8a" ^
        -GNinja ^
        "-DCMAKE_BUILD_TYPE=RelWithDebInfo"
    from G:\zxing-cpp-master\zxing-cpp-master\wrappers\android\zxingcpp
  CMake Error at C:/Users/auror/AppData/Local/Android/Sdk/cmake/3.22.1/share/cmake-3.22/Modules/CMakeTestCCompiler.cmake:69 (message):
    The C compiler

      "C:/Users/auror/AppData/Local/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe"

    is not able to compile a simple test program.

    It fails with the following output:

      Change Dir: G:/zxing-cpp-master/zxing-cpp-master/wrappers/android/zxingcpp/.cxx/RelWithDebInfo/4z4y243u/arm64-v8a/CMakeFiles/CMakeTmp

      Run Build Command(s):C:\Users\auror\AppData\Local\Android\Sdk\cmake\3.22.1\bin\ninja.exe cmTC_1e77b && [1/2] Building C object CMakeFiles/cmTC_1e77b.dir/testCCompiler.c.o
      [2/2] Linking C executable cmTC_1e77b
      FAILED: cmTC_1e77b
      cmd.exe /C "cd . && C:\Users\auror\AppData\Local\Android\Sdk\ndk\23.1.7779620\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe --target=aarch64-none-linux-android21 --sysroot=C:/Users/auror/AppData/Local/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/windows-x86_64/sysroot -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fexceptions  -O2 -g -DNDEBUG -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--fatal-warnings -Qunused-arguments -Wl,--no-undefined  -Wl,--gc-sections CMakeFiles/cmTC_1e77b.dir/testCCompiler.c.o -o cmTC_1e77b  -latomic -lm && cd ."
      ld: error: cannot open output file cmTC_1e77b: Function not implemented
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      ninja: build stopped: subcommand failed.





    CMake will not be able to correctly generate this project.
  Call Stack (most recent call first):
    CMakeLists.txt:2 (project)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
1 actionable task: 1 executed
PS G:\zxing-cpp-master\zxing-cpp-master\wrappers\android>

---------------------
Perhaps a bug in my Android Studio installation

I have tried to add opencv in a project. It fails and android studio stop working,
 I completly deleted android studio, and re-installed it
Perhaps the new installation doesn't work

**Comment by axxel** [comment]
This error log tells me that your problem is not related to zxing-cpp itself. It basically says your compiler/linker is not working, or rather cmake is not able to compile a simple test program. The most specific line seems to be this one:
```
 ld: error: cannot open output file cmTC_1e77b: Function not implemented
```

I'm afraid, I have no advice for you in this situation. Nothing other than use the search engine of your choice to find a solution for your problem.
