### ISSUE TITLE
Memory overflow for rare images

### ISSUE THREAD

**Issue by chrhenning** [zxing-cpp/zxing-cpp#525]
Thank you so much for this awesome repository.

I found rare cases in which the Python library (`zxing-cpp==2.0.0`) can enter an infinite loop during barcode reading and ultimately cause a memory overflow (and thus a crash of the Python interpreter).

For instance, the following image would lead to such a case (images are attached below)

<img width="187" alt="image" src="https://user-images.githubusercontent.com/18127458/222918987-87343c93-7b5b-4e80-afbb-8c1c8f3307a5.png">

```python
import numpy as np
import zxingcpp

with open('/Users/christianhenning/Downloads/zxingcpp_mem_overflow_1.npy', 'rb') as f:
    img = np.load(f)

zxingcpp.read_barcodes(img, zxingcpp.BarcodeFormat.DataMatrix, binarizer=zxingcpp.BoolCast)
```

Here are some example images that cause the problem: [zxingcpp_mem_overflow.zip](https://github.com/zxing-cpp/zxing-cpp/files/10889202/zxingcpp_mem_overflow.zip)

**Comment by axxel** [comment]
I can confirm that something is broken with the 2.0.0 python module. Trying to debug this, I noticed that the current HEAD revision does not exhibit the problem (with a locally build python module). Can you confirm this? Can you convert your `npy` file to a png and reproduce the problem with the current HEAD revision of the `ZXingReader` tool?

**Comment by axxel** [comment]
Here is a set of python module binaries from current HEAD. Maybe that could also help you in confirm that the current HEAD does not exhibit the issue you reported: https://github.com/zxing-cpp/zxing-cpp/suites/11746968082/artifacts/612002288

**Comment by chrhenning** [comment]
Hey, sorry for the late response. 

> Trying to debug this, I noticed that the current HEAD revision does not exhibit the problem (with a locally build python module). 

If I didn't do anything wrong when installing the current HEAD, then the problem persists on the current HEAD revision.

> Can you convert your npy file to a png and reproduce the problem with the current HEAD revision of the ZXingReader tool?

Once I convert the images to PNG and read them from file, the problem disappears. Though, the image content has obviously been manipulated through the conversion to PNG.

```python
img = cv2.imread('/Users/christianhenning/Downloads/zxingcpp_mem_overflow_2.png')
zxingcpp.read_barcodes(img, zxingcpp.BarcodeFormat.DataMatrix, binarizer=zxingcpp.BoolCast)
```

Here are the PNG file

![zxingcpp_mem_overflow_1](https://user-images.githubusercontent.com/18127458/227593170-9571385a-d724-4581-934d-1bc9c2304985.png)

![zxingcpp_mem_overflow_2](https://user-images.githubusercontent.com/18127458/227593224-cd5f1393-e6a9-4117-9e0c-ef202c4b7f00.png)

FYI I installed the current head as follows: Deleting my current installation of `zxing-cpp`, downloading `zxing-cpp-2.0.0.tar.gz` from the link you provided and then installed the package as follows inside the extracted tar.gz folder:

```
python setup.py install 
```

**Comment by axxel** [comment]
I double checked with the linked artifacts.zip:
 * if I install the wheel for my system from that zip via `pip install zxing_cpp-2.0.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl` it works
 * if I build the module via `python setup.py install` from the `zxing-cpp-2.0.0.tar.gz` as you did, it also works
 * if I remove all those and simply install the 2.0.0 release from pypi.org via `pip install zxing-cpp` it fails

You are executing this on a mac (it seems) instead of a Linux machine, that might somehow be responsible for the difference. Or you are executing the wrong code. Could you maybe try to install the pre-build version from that artifact.zip and test that?

**Comment by chrhenning** [comment]
Hey,


sorry, you are right, I must have done something wrong yesterday.

Yes, I'm working on a Mac M1. The rebuild wheels didn't work for me, that's why I installed the package via `python setup.py install`, which yields 

> Installed /Users/christianhenning/miniconda3/envs/acore/lib/python3.10/site-packages/zxing_cpp-2.0.0-py3.10-macosx-11.1-arm64.egg

<img width="1266" alt="image" src="https://user-images.githubusercontent.com/18127458/227718713-f7123cb0-2c5f-4715-bcc0-6336fdea48d8.png">

I just tested with the `npy` files, and the memory overflow disappeared. Thanks :)

**Comment by axxel** [comment]
That is very good to hear. I took your input as a trigger to add support for building macos arm64 python binaries to the CI system. Would you please do me the favor and check if the new [artifacts.zip](https://github.com/zxing-cpp/zxing-cpp/suites/11807710820/artifacts/616366865) contains a working binary wheel for you?

Please note that I also changed the [default build mode to c++20](f4998ca908185c07a3f66284c3815d08517b5965) which improves DataMatrix support but comes at a noticeable performance cost.

**Comment by chrhenning** [comment]
Hey, thank you!

Unfortunately, it doesn't run out-of-the-box:

<img width="1728" alt="Screenshot 2023-03-26 at 12 14 59" src="https://user-images.githubusercontent.com/18127458/227769227-5c4a9323-2374-40ff-a59a-5a664d3e30ad.png">

This is the error message I get upon import:

> ImportError: dlopen(/Users/christianhenning/miniconda3/envs/acore/lib/python3.10/site-packages/zxingcpp.cpython-310-darwin.so, 0x0002): tried: '/Users/christianhenning/miniconda3/envs/acore/lib/python3.10/site-packages/zxingcpp.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/christianhenning/miniconda3/envs/acore/lib/python3.10/site-packages/zxingcpp.cpython-310-darwin.so' (no such file), '/Users/christianhenning/miniconda3/envs/acore/lib/python3.10/site-packages/zxingcpp.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

Also the installation via `python setup.py install` does not work anymore. Here's the complete output:

[install.txt](https://github.com/zxing-cpp/zxing-cpp/files/11071305/install.txt)

**Comment by axxel** [comment]
Thanks for the feedback.
1) this error message seems to indicate that the `arm64.whl` file does contain a `x86_64` binary, which looks like bug in cuibuildwheel. I'll have to google for what it is going on there...
2) the error message in your install.txt let's me suspect that the problem is the `(` in the path `.../artifact (1)/...`. Could you please remove the parenthesis from the path and try again? That seems like a bug/limitation of the python setup utility.

**Comment by axxel** [comment]
So, I had a look at was going wrong in the arm64 case and I believe I found a (disappointing) explanation:  the cibuildwheel action basically does not work in this case if there is a cmake based native library involved. I hopefully found a way to get something working on macos, namely a universal2 build that contains both the x86 and the arm64 binaries. I have no idea whether or not it actually does, though. Could you give this new [artifacts.zip](https://github.com/axxel/zxing-cpp/suites/11819731028/artifacts/617220824) another look and try the universal wheel, please?

**Comment by chrhenning** [comment]
> I hopefully found a way to get something working on macos, namely a universal2 build that contains both the x86 and the arm64 binaries.

Yes, that seems to work well :)

> the error message in your install.txt let's me suspect that the problem is the ( in the path .../artifact (1)/.... Could you please remove the parenthesis from the path and try again? That seems like a bug/limitation of the python setup utility.

This seems to work now too. Thanks!
