### ISSUE TITLE
Result._position does not include EAN addon

### ISSUE THREAD

**Issue by pictview** [zxing-cpp/zxing-cpp#527]
When recognizing an EAN8 with an add-on, the position of the add-on is not included in the result.
I guess the value returned from MultiUPCEANReader::decodePattern() should use addOnRes.end.pixelsTillEnd() when appropriate.
I think also next should be adapted from addOnRes.end and not always from res.end.

**Comment by axxel** [comment]
Turns out this open TODO item was rather trivial to fix. And yes, the state of `next` should have been set to `addOnRes.end` in case an add-on was detected. Thanks for pointing that out.
