### ISSUE TITLE
Mac Catalyst support

### ISSUE THREAD

**Issue by iKova47** [zxing-cpp/zxing-cpp#531]
Hi,

I'd like to use this library in my mac catalyst app, but I can't figure out how to build the iOS wrapper with the support for mac catalyst.

I've tried to modify the `build-release.sh` script in the `wrappers/ios` folder to include the following line on line 32:

`-destination 'platform=macOS,variant=Mac Catalyst'`

but no luck, I've also tried various different solutions, but none of them resulted in any success.

Everything I tried resulted in the following error:

`While building for Mac Catalyst, no library for this platform was found in '../Packages/ZXingCpp/ZXingCpp.xcframework'.`

Can you please help me?

**Comment by axxel** [comment]
@parallaxe would you have anything to say about this issue?

**Comment by axxel** [comment]
Is this still an issue? If not: how did you solve it?
