### ISSUE TITLE
GS1 DataBar Limited

### ISSUE THREAD

**Issue by pictview** [zxing-cpp/zxing-cpp#534]
Are there plans to support reading GS1 DataBar Limited barcodes?

**Comment by axxel** [comment]
I currently don't have plans myself to do that. That said, my priorities can be influenced (see [my sponsors page](https://github.com/sponsors/axxel) ;)).

**Comment by glebaccon-eurekam** [comment]
Hey, my company can sponsor you for the development of GS1 DataBar Limited, Truncated and maybe Expanded.

May I contact you by mail ? zxingcpp@gmail.com ?

**Comment by axxel** [comment]
> Hey, my company can sponsor you for the development of GS1 DataBar Limited, Truncated and maybe Expanded.
> 
> May I contact you by mail ? [zxingcpp@gmail.com](mailto:zxingcpp@gmail.com) ?

Yes.
