### ISSUE TITLE
iOS demo launch crashed, dyld: Library not loaded:

### ISSUE THREAD

**Issue by mike1023** [zxing-cpp/zxing-cpp#538]
I tried to run the demo in wrapper/ios.
first I run the script build-release.sh, get the ZXingCpp.xcframework
then I run the demo on my device(iPhone 14 pro max, iOS 16.3). Xcode version: 14.2
I get the crash like the below:
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/15139581/228115267-8357f67a-1469-492e-a544-dcde6c1dd5de.png">
<img width="991" alt="image" src="https://user-images.githubusercontent.com/15139581/228115398-8896b894-da31-4208-83cb-dfce53d7b0c7.png">

**Comment by axxel** [comment]
I hope @parallaxe has something useful to say here. I'm not an iOS developer and can't even build the code on that platform.

**Comment by mike1023** [comment]
thanks for your reply, @parallaxe, could you check for this issue?

**Comment by mike1023** [comment]
strange issue, my colleague download the repo and run build-release.sh, get the xcframework. Then he run the demo, everything is ok.
our system version are different, my is macOS 13.1, him is macOS 12.5.1

**Comment by ChristianNorbertBraun** [comment]
I can not reproduce this error. @mike1023 did you manage to solve this?

**Comment by axxel** [comment]
Closing for lack of feedback.
