### ISSUE TITLE
ZXingC++ How to debug online with VScode on linux system？

### ISSUE THREAD

**Issue by niamdsamsd** [zxing-cpp/zxing-cpp#545]
ZXingC++ How to debug online with VScode on linux system,

**Comment by axxel** [comment]
I don't know what you mean by "online" in this context. Also your question is not really specific to ZXingC++. I suggest you look for answers in the general VSCode/Linux community.

**Comment by niamdsamsd** [comment]
OK ，thankyou！

**Comment by niamdsamsd** [comment]
Hello, Sir, I would like to get the decoding scheme of how to add MICRO_PDF417, do you have better suggestions




fei舟延
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zxing-cpp/zxing-cpp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月7日(星期五) 晚上11:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zxing-cpp/zxing-cpp] ZXingC++ How to debug online with VScode on linux system？ (Issue #545)





 
I don't know what you mean by "online" in this context. Also your question is not really specific to ZXingC++. I suggest you look for answers in the general VSCode/Linux community.
