### ISSUE TITLE
micro PDF417 added

### ISSUE THREAD

**Issue by niamdsamsd** [zxing-cpp/zxing-cpp#549]
Is it possible to add micro_PDF417 decoding to ZXingC++? What advice would you give? Is there any channel according to the ISO file?

Or if I want to buy, can I buy the source code

**Comment by niamdsamsd** [comment]
How to buy micro pdf417 decode source code

**Comment by axxel** [comment]
This is already discussed in #385.

**Comment by niamdsamsd** [comment]
I&nbsp; WANT BUY MICRO_PDF417

fei舟延
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zxing-cpp/zxing-cpp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月11日(星期二) 凌晨4:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zxing-cpp/zxing-cpp] micro PDF417 added (Issue #549)





 
This is already discussed in #385.
