### ISSUE TITLE
Error (missing file) on building project on linux

### ISSUE THREAD

**Issue by fostjms** [zxing-cpp/zxing-cpp#560]
Hi,

Im trying to run ZXing on Qt creator but when building the project it gives me an error regarding missing files: arm-linux-gcc.br_real and arm-linux-c++.br_real.
How to solve this ?

**Comment by axxel** [comment]
Looks like you are trying to cross compile the library? I don't believe this has anything todo with Qt Creator specifically. I suggest you try to compile the code with plain `cmake` first and once this works, it es very easy to open that project with QtCreator (which is my personal development environment as well). If you have issues with the cmake build, please post the exact cmake command line you are using.

**Comment by fostjms** [comment]
Problem solved. Thank you!
