### ISSUE TITLE
Python Bindings on Raspberry Pi Zero

### ISSUE THREAD

**Issue by niwla23** [zxing-cpp/zxing-cpp#564]
all the [piwheels builds](https://www.piwheels.org/project/zxing-cpp/) are failing for this library. I am trying to get it to run with python bindings on a raspberry pi zero. When I try to build it myself, the raspberry becomes unresponsive and is stuck at 7% compiling. Is there any chance of getting the piwheels fixed or is there another way to get this running?

**Comment by axxel** [comment]
Thanks for bringing this to my attention. See my comments in the issue you linked above. About the problem with compiling it yourself: can you follow the build instructions as described in the [README](https://github.com/zxing-cpp/zxing-cpp#build-instructions)? And if that fails, post the cmake and build output (as far as it gets)?

**Comment by niwla23** [comment]
Got it working, the Problem was RAM. So after increasing swap I was able to build even though it took an hour.

**Comment by axxel** [comment]
At least the piwheels Bullseye package is now building after v2.1.0 release. Buster fails due to compilation issues with the old gcc 8 compiler.
