### ISSUE TITLE
QRCode not recognized

### ISSUE THREAD

**Issue by mbaros100** [zxing-cpp/zxing-cpp#566]
Hello,

I have 2 identical QR codes with 1 pixel white margin.
One is extra padded with white and the other one with black margin.

The white one is recognized by the library but the black one is not.

![black](https://github.com/zxing-cpp/zxing-cpp/assets/8537079/6548053c-b929-4989-b054-54264d92efbe)
![white](https://github.com/zxing-cpp/zxing-cpp/assets/8537079/73849607-57b4-4d7c-8678-d4bdec227b15)

**Comment by axxel** [comment]
The first one is an invalid code. The standard requires at least 4 modules of quiet zone. The current implementation requires 0.5 modules. This is somewhat related to #202. As it is rather trivial to fix this particular image by reducing the minimum to 0.1 modules and this also adds one missing detection from the sample set, while not really affecting performance, I decided to push that.

**Comment by mbaros100** [comment]
Thank you!
