### ISSUE TITLE
GenAI based QR codes are not being detected reliably

### ISSUE THREAD

**Issue by siddBanPsu** [zxing-cpp/zxing-cpp#571]
Some are getting detected, others are not: https://media.licdn.com/dms/image/D5622AQH7_z75TkX-dg/feedshare-shrink_2048_1536/0/1686017475195?e=1689206400&v=beta&t=YHjldXW2tlk7IgAMazu5dwxhIEy0GUDs_YEUQrUGAf0

**Comment by duanqn** [comment]
Maybe the `isPure` mode can help? I'm really surprised that this QR code can be scanned by WeChat.

**Comment by axxel** [comment]
`isPure` mode will not help, while this image is oriented correctly for that mode, the image has anything but a clear/white background.

**Comment by axxel** [comment]
The link to the example does not work anymore and I consider the original question as answered.
