### ISSUE TITLE
TypeError: Unsupported type <class 'numpy.ndarray'>

### ISSUE THREAD

**Issue by pauljurczak** [zxing-cpp/zxing-cpp#582]
I thought that zxing-cpp supports Numpy arrays. This Python 3.11.4 script with zxing-cpp 2.0.0
```
import zxingcpp
import numpy as np

a = np.arange(240).reshape(10, 24)
r = zxingcpp.read_barcodes(a)
```
produces
```
    r = zxingcpp.read_barcodes(a)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Unsupported type <class 'numpy.ndarray'>. Expect a PIL Image or numpy array
```
There is no `numpy array` class. Numpy arrays are of `<class 'numpy.ndarray'>` type. How do I use Numpy arrays with zxing-cpp?

**Comment by pauljurczak** [comment]
When I try to use PIL
```
import zxingcpp
import numpy as np
from PIL import Image

a = Image.fromarray(np.arange(240, dtype='i1').reshape(10, 24))
res = zxingcpp.read_barcodes(a)
```
I get
```
    res = zxingcpp.read_barcodes(a)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Unsupported type <class 'PIL.Image.Image'>. Expect a PIL Image or numpy array
```

**Comment by axxel** [comment]
The error message provided had changed since the release of 2.0. The current head produces the following error for the first of your test scripts:
```
TypeError: Cannot cast array data from dtype('int64') to dtype('uint8') according to the rule 'safe'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/axel/contrib/zxing-cpp.release/wrappers/python/582.py", line 8, in <module>
    res = zxingcpp.read_barcodes(a)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
```

So if you change the `a=` line to `a = np.arange(240, dtype=np.uint8).reshape(10, 24)` it works.

The PIL based sample works just out of the box with current head, no idea why it did not in 2.0.

A 2.1 release is planed in the comming days.

**Comment by pauljurczak** [comment]
Thank you. This solved my problem. Both examples work with `dtype='u1'` or equivalent `dtype=np.uint8`.
