### ISSUE TITLE
Blurry EAN-13 barcode can not be decoded

### ISSUE THREAD

**Issue by PureHing** [zxing-cpp/zxing-cpp#585]
![Cam0](https://github.com/zxing-cpp/zxing-cpp/assets/62579216/8fe8c4e3-622c-447d-97a8-9f63f3cb47b9)

can u give me some advice?
@axxel  Thank you!

**Comment by axxel** [comment]
The image is too blurry, either not focused properly or maybe motion blur. zxing-cpp will not be able to decode this. The resolution could also be higher but if it was sharply focused it would be sufficient.

**Comment by PureHing** [comment]
OK.
@axxel 
BTW,I compiled ZxingReader.exe on VS2019 ,follow by Readme, but datamtrix cannot be parsed, but your webpage can, is it because I didn’t set the parameters right?

**Comment by axxel** [comment]
1. Building with c++20 improves the DataMatrix detection but it does work without as well. But in that case the symbol needs to be in the center of the image.
2. libdmtx is a completely different library that uses a completely different algorithm.

**Comment by derpda** [comment]
I think many commercial barcode libraries can read even such blurred examples. 
Maybe they use techniques such as those outlined in [this blog post](https://web.archive.org/web/20160610003715/http://www.windytan.com/2016/02/barcode-recovery-using-priori.html) (only available on the wayback machine...).
How hard would it be to implement something like that in zxing, and could you give me any advice on how to do that @axxel? 
I'm new to the zxing library, apologies if something like that already exists here or is not desired.

**Comment by axxel** [comment]
> Maybe they use techniques such as those outlined in [this blog post](https://web.archive.org/web/20160610003715/http://www.windytan.com/2016/02/barcode-recovery-using-priori.html)

Interesting approach but also very specific to a particular type of input. Also the initial rectification by manually identifying the corners of the ID card is obviously not usable in the general context of this library. Next is the fact that starting from the resolution, the used symbology, down to the expected content of the symbol this is a very tailored approach. That said, the results are surely very impressive. And for the EAN13 symbology, this might actually be practically applicable, as the symbology itself already is very constrained (fixed length and only 10 possible characters).

> How hard would it be to implement something like that in zxing, and could you give me any advice on how to do that @axxel?

The approach described in the blog post is very different from what zxing does, starting from the fact that the character detection is working directly on greyscale data, while all algorithms in zxing are working on binary data, where a lot of information is already lost. If you wanted to copy the ideas, you might actually start from scratch using something like opencv as outlined in the post. ZXing might be helpful in generating the filter masks or by simply using it as a source of information about the specification of the codes.

> I'm new to the zxing library, apologies if something like that already exists here or is not desired.

It does not exists and might very well be desirable depending on how much disruption it would case to the current infrastructure and how the ratio of additional detections vs. additional runtime will turn out.

@PureHing I had a closer look at the kind of blur in your sample and I believe it is mostly motion blur. Maybe the round thing with the barcode attached is rotating? If you can control the camera, just reducing the capture time might it work for you.

**Comment by derpda** [comment]
Thank you for your quick reply!
Yes the blog post is indeed *very* specific, its basically a particular riddle the author wanted to solve (generally very cool blog btw). Nevertheless, some parts of the post seem generally applicable. 
I'll need to read the source code a bit more, and also some proper papers on the subject, but maybe writing a new binarizer is the way to go? Once the binary data is available, the decoding would be the same. But again, my understanding is still very limited.

**Comment by axxel** [comment]
> maybe writing a new binarizer is the way to go?

Not if you want to apply the approach taken in the mentioned blog post. The author made deliberate use of the fact that a blurred high frequency signal (switch between black and white) becomes a grey (mean value) signal, which can be part of the match. If you force that back to black or white, you loose that information.

**Comment by PureHing** [comment]
> I had a closer look at the kind of blur in your sample and I believe it is mostly motion blur. Maybe the round thing with the barcode attached is rotating? If you can control the camera, just reducing the capture time might it work for you.

Yes,Indeed it is.
@axxel I would like to ask about the angle information. For one-dimensional codes, I found that 0° to 15° are all 0°, and those greater than 20° seem to be unrecognizable. Where can I see this part of the design. So is the QR code also designed like this? Thank you so much.
<img width="478" alt="1689173132029" src="https://github.com/zxing-cpp/zxing-cpp/assets/62579216/c57bfdc5-6e80-4f18-be9f-6731f18b6d42">

**Comment by axxel** [comment]
Linear symbologies are only detected on horizontal and vertical lines, therefore the orientation information for those can only ever be 0, 90, 180 and 270. If the rotation is too far away from any of those 4 (depends on the symbology) then it will not be detected.

QRCodes are build to be detected completely independent of their rotation. They don't have that limitation.

**Comment by axxel** [comment]
@derpda if you want to discuss your ideas related to the mentioned blog post, let's start a new discussion or even a PR if you ave some code. I'm closing this issue now.
