### ISSUE TITLE
[Request] Qr from image c++

### ISSUE THREAD

**Issue by jhay06** [zxing-cpp/zxing-cpp#586]
Can someone give me sample on how can i read/decode QR from image file using c++ ,

already built libZXing.so but i dunno how to use it, i read the example but can't find answer from there 
any simple c++ code ? 

Thanks

**Comment by axxel** [comment]
Yes, the `ZXingReader.cpp` is indeed not very easy to follow as it evolved into a fully fledged command line tool. I hope the following is helpful to you:
```c++
	using namespace ZXing;

	int width, height;
	uint8_t* data = // read your image data from a file or get it from somewhere else.
	                // The following code assumes 3 bytes (RGB) per pixel.

	auto hints = DecodeHints().setFormats(BarcodeFormat::QRCode);
	auto image = ImageView{data, width, height, ImageFormat::RGB};

	auto results = ReadBarcodes(image, hints);

	for (auto& result : results) {
		std::cout << result.text() << "\n";
	}
```

**Comment by jhay06** [comment]
okay already solved but i have a next problem , i want Text to become QR i read the sample ZXingWriter , but i dont know how to convert the bitmatrix to QImage , btw im using zxing using QT

**Comment by axxel** [comment]
You are using Qt? If you only said that earlier... ;). Please have a look at [ZXingQtReader.cpp](https://github.com/zxing-cpp/zxing-cpp/blob/master/example/ZXingQtReader.cpp) and the brand new [ZXingQtWriter.cpp](https://github.com/zxing-cpp/zxing-cpp/blob/master/example/ZXingQtWriter.cpp).

**Comment by jhay06** [comment]
Already resolved , :)   thanks
