### ISSUE TITLE
Support for non-ISO8859_1 characters in DataMatrix generation missing

### ISSUE THREAD

**Issue by wwzh2015** [zxing-cpp/zxing-cpp#592]
How to Generate QR code that contain chinese word? But contain English word is exactly.

e.x:
int main(int argc, char* argv[])
{
	CharacterSet encoding = CharacterSet::UTF8;
	BarcodeFormat format = BarcodeFormat::QRCode;

	int width = 500, height = 500;
	int margin = 10;    //空白
	int eccLevel = -1;	//纠错级别
	
	std::string text = "公共号1hgreh346346w+_=@#$%| a|";
	std::string filePath = "qr1.png";

	if (!ParseOptions(argc, argv, &width, &height, &margin, &encoding, &eccLevel, &format, &text, &filePath)) {
		PrintUsage(argv[0]);
		return -1;
	}

	try {
		auto writer = MultiFormatWriter(format).setMargin(margin).setEncoding(encoding).setEccLevel(eccLevel);
		
		auto bitmap = ToMatrix<uint8_t>(writer.encode(TextUtfEncoding::FromUtf8(string_To_UTF8(text)), width, height));

		auto ext = GetExtension(filePath);
		int success = 0;
		if (ext == "" || ext == "png") {
			success = stbi_write_png(filePath.c_str(), bitmap.width(), bitmap.height(), 1, bitmap.data(), 0);
		}
		else if (ext == "jpg" || ext == "jpeg") {
			success = stbi_write_jpg(filePath.c_str(), bitmap.width(), bitmap.height(), 1, bitmap.data(), 0);
		}

		if (!success) {
			std::cerr << "Failed to write image: " << filePath << std::endl;
			return -1;
		}
	}
	catch (const std::exception& e) {
		std::cerr << e.what() << std::endl;
		return -1;
	}

	std::system("Pause");
	return 0;
}

**Comment by axxel** [comment]
If call `ZXingWriter -encoding utf8 qrcode "公共号1hgreh346346w+_=@#$%| a|" test.png` and then `ZXingReader test.png` I get exactly the input string back. What is your problem?

I suggest you replace `TextUtfEncoding::FromUtf8(string_To_UTF8(text))` with `text` and try again.

**Comment by wwzh2015** [comment]
> replace `TextUtfEncoding::FromUtf8(string_To_UTF8(text))` with

My problem is generate fail when the QR code contain chinese word, english word is successful.

How can successful generate QR code that contain chinese word!

**Comment by axxel** [comment]
I don't understand what your problem is. You need to be more specific. To get a baseline, please execute the command `ZXingWriter -encoding utf8 qrcode "公共号1hgreh346346w+_=@#$%| a|" test.png` and post the resulting `test.png` here or any error message you receive in case that command should fail.

**Comment by wwzh2015** [comment]
> ZXingWriter -encoding utf8 qrcode "公共号1hgreh346346w+_=@#$%| a|" test.png

ZXingWriter -encoding utf8 qrcode "公共号1hgreh346346w+_=@#$%| a|" test.png
Found empty contents

Why dont support “公共号” these chinese words？But support "1hgreh346346w+_=@#$%| a|"

**Comment by axxel** [comment]
I'm trying to help you, but you need to follow my instructions (see above) otherwise we won't make any progress.

**Comment by wwzh2015** [comment]
> I'm trying to help you, but you need to follow my instructions (see above) otherwise we won't make any progress.

I have follow your instructions, what do you mean?

are you fake?

**Comment by wwzh2015** [comment]
> instructions

you can't recognize my English word？

**Comment by axxel** [comment]
> you can't recognize my english？

Yes, it seems we are having a communication issue.

> I have in CMD Console input: "ZXingWriter -encoding utf8 qrcode "公共号1hgreh346346w+_=@#$%| a|" test.png" tips: Found empty contents

So "Found empty contents" is an actual error message you receive when executing this command? On my machine this just works. What OS/platform are you using?

**Comment by wwzh2015** [comment]
> > you can't recognize my english？
> 
> Yes, it seems we are having a communication issue.
> 
> > I have in CMD Console input: "ZXingWriter -encoding utf8 qrcode "公共号1hgreh346346w+_=@#$%| a|" test.png" tips: Found empty contents
> 
> So "Found empty contents" is an actual error message you receive when executing this command? On my machine this just works. What OS/platform are you using?

Thanks, I using C++ vs2019 vc142 compile this zxing in win10 x64 platform,
Please give me your project with zxing?
Now I just want to generate QR code that contain chinese word.

**Comment by axxel** [comment]
I'm using Ubuntu. Maybe there is something wrong with your Windows console or language setup. Let's try something that is selfcontained, like your original sample. Please compile and execute the following minimal program and see if you get "37" as an answer or some other error message:
```
#include <ZXing/MultiFormatWriter.h>
#include <ZXing/BarcodeFormat.h>
#include <ZXing/BitMatrix.h>
#include <ZXing/CharacterSet.h>

#include <iostream>

using namespace ZXing;

int main(int argc, char* argv[])
{
	std::wstring text = L"公共号1hgreh346346w+_=@#$%| a|";

	try {
		auto writer = MultiFormatWriter(BarcodeFormat::QRCode).setEncoding(CharacterSet::UTF8);
		
		auto bitmap = ToMatrix<uint8_t>(writer.encode(text, 0, 0));

		std::cout << bitmap.width() << "\n";
	}
	catch (const std::exception& e) {
		std::cerr << e.what() << std::endl;
		return -1;
	}

	return 0;
}
```

**Comment by wwzh2015** [comment]
> I'm using Ubuntu. Maybe there is something wrong with your Windows console or language setup. Let's try something that is selfcontained, like your original sample. Please compile and execute the following minimal program and see if you get "37" as an answer or some other error message:
> 
> ```
> #include <ZXing/MultiFormatWriter.h>
> #include <ZXing/BarcodeFormat.h>
> #include <ZXing/BitMatrix.h>
> #include <ZXing/CharacterSet.h>
> 
> #include <iostream>
> 
> using namespace ZXing;
> 
> int main(int argc, char* argv[])
> {
> 	std::wstring text = L"公共号1hgreh346346w+_=@#$%| a|";
> 
> 	try {
> 		auto writer = MultiFormatWriter(BarcodeFormat::QRCode).setEncoding(CharacterSet::UTF8);
> 		
> 		auto bitmap = ToMatrix<uint8_t>(writer.encode(text, 0, 0));
> 
> 		std::cout << bitmap.width() << "\n";
> 	}
> 	catch (const std::exception& e) {
> 		std::cerr << e.what() << std::endl;
> 		return -1;
> 	}
> 
> 	return 0;
> }
> ```



> I'm using Ubuntu. Maybe there is something wrong with your Windows console or language setup. Let's try something that is selfcontained, like your original sample. Please compile and execute the following minimal program and see if you get "37" as an answer or some other error message:
> 
> ```
> #include <ZXing/MultiFormatWriter.h>
> #include <ZXing/BarcodeFormat.h>
> #include <ZXing/BitMatrix.h>
> #include <ZXing/CharacterSet.h>
> 
> #include <iostream>
> 
> using namespace ZXing;
> 
> int main(int argc, char* argv[])
> {
> 	std::wstring text = L"公共号1hgreh346346w+_=@#$%| a|";
> 
> 	try {
> 		auto writer = MultiFormatWriter(BarcodeFormat::QRCode).setEncoding(CharacterSet::UTF8);
> 		
> 		auto bitmap = ToMatrix<uint8_t>(writer.encode(text, 0, 0));
> 
> 		std::cout << bitmap.width() << "\n";
> 	}
> 	catch (const std::exception& e) {
> 		std::cerr << e.what() << std::endl;
> 		return -1;
> 	}
> 
> 	return 0;
> }
> ```

Thanks your help，now  QRcode PDF417 can generate correct，but DATA_MATRIX generated also fail When it contain chinese word.

**Comment by wwzh2015** [comment]
DATA_MATRIX generated also fail When it contain other word.

**Comment by axxel** [comment]
> but DATA_MATRIX generated still fail whatever it contain chinese word or 123456 or english word.

I can confirm that DataMatrix does not support encoding characters outside of the ISO8859_1 character set. It is simply not implemented. I was not even aware of that fact. This is yet another reason to look at #332 (which I am currently doing, but results will take some time).

`ZXingWriter datamatrix "123456" test.png` does work without issues, though.
