### ISSUE TITLE
Assert in RegressionLine::evaluate due to empty points

### ISSUE THREAD

**Issue by LeonnardoVerol** [zxing-cpp/zxing-cpp#593]
```
15:00:41: Starting D:\DEV\Qt\build-zxing-qt-Desktop_Qt_6_3_2_MSVC2019_64bit-Debug\debug\zxing-qt.exe...
QML debugging is enabled. Only use this in a safe environment.
Aztec|Codabar|Code39|Code93|Code128|DataBar|DataBarExpanded|DataMatrix|EAN-8|EAN-13|ITF|MaxiCode|PDF417|QRCode|UPC-A|UPC-E|MicroQRCode
15:00:43: D:\DEV\Qt\build-zxing-qt-Desktop_Qt_6_3_2_MSVC2019_64bit-Debug\debug\zxing-qt.exe crashed.
```

Also, `BarcodeFormat::Any` is missing at `ZXingQtReader.h`

```
Any			= LinearCodes | MatrixCodes
```
PS: build:  6.3.2 Qmake MSVC 2019 64bit
PS2: Crash also on 6.5.0: https://github.com/zxing-cpp/zxing-cpp/discussions/559#discussioncomment-5826563

---

Edit: 
Commenting `MediaDevices` & derived code (comboBox model etc) avoids the immediate crash but the app hangs until it crashes.

Not having a proper barcode (or any) in front of the camera seems to make it crash quicker.

Disabling `Try Harder` and `Matrix Codes` "improves" when no barcode is detected but hangs (not like before, at least) when it can't easily decode the barcode

Having a barcode in front of the camera avoids the crash for some time

![image](https://github.com/zxing-cpp/zxing-cpp/assets/6124410/321907d5-5e1d-4f98-91a4-8c4dc20ad069)

**Comment by axxel** [comment]
There is no "zxing-qt" target in our sample set. Based on the console output it seems it is based on the `ZXingQtCamReader`?

I just tried the vanilla `example/ZXingQtCamReader` on Ubuntu with qt 6.4.2 and it works just fine (letting it run a few seconds and holding a barcode in front of the webcam).

Can you run this in a debugger and find out which `back()` call is crashing?

**Comment by LeonnardoVerol** [comment]
"zxing-qt" is the name of my qt solution.

Commenting `MediaDevices` & derived code (comboBox model etc) avoids the immediate crash but the app hangs until it crashes.

Not having a proper barcode (or any) in front of the camera seems to make it crash quicker.

Disabling `Try Harder` and `Matrix Codes` "improves" when no barcode is detected but hangs (not like before, at least) when it can't easily decode the barcode

Having a barcode in front of the camera avoids the crash for some time

---

I will try to run debugger and find out more about it

**Comment by LeonnardoVerol** [comment]
![image](https://github.com/zxing-cpp/zxing-cpp/assets/6124410/f8bccbb5-f4ae-4efe-8627-d9562fec7641)

![image](https://github.com/zxing-cpp/zxing-cpp/assets/6124410/4151bb91-d981-4313-a64a-5fb1118d3922)

![image](https://github.com/zxing-cpp/zxing-cpp/assets/6124410/15e5847f-13ec-4692-a4e2-23f2b5e411e6)

![image](https://github.com/zxing-cpp/zxing-cpp/assets/6124410/800daec4-8eb9-4f7c-8d26-c60823f16499)

![image](https://github.com/zxing-cpp/zxing-cpp/assets/6124410/43a7117c-7bbe-448e-ba87-044cb05656dc)

![image](https://github.com/zxing-cpp/zxing-cpp/assets/6124410/16c8fe2b-552a-4c4f-9d01-4c72c6ff6250)

etc

![image](https://github.com/zxing-cpp/zxing-cpp/assets/6124410/5ec95e4f-a8b5-41ca-aafc-df8364f427bb)

![image](https://github.com/zxing-cpp/zxing-cpp/assets/6124410/ba22c501-ef28-47f1-8291-97ebc42269d1)

**Comment by LeonnardoVerol** [comment]
![image](https://github.com/zxing-cpp/zxing-cpp/assets/6124410/f8bccbb5-f4ae-4efe-8627-d9562fec7641)

![image](https://github.com/zxing-cpp/zxing-cpp/assets/6124410/4151bb91-d981-4313-a64a-5fb1118d3922)

![image](https://github.com/zxing-cpp/zxing-cpp/assets/6124410/15e5847f-13ec-4692-a4e2-23f2b5e411e6)

![image](https://github.com/zxing-cpp/zxing-cpp/assets/6124410/800daec4-8eb9-4f7c-8d26-c60823f16499)

![image](https://github.com/zxing-cpp/zxing-cpp/assets/6124410/43a7117c-7bbe-448e-ba87-044cb05656dc)

![image](https://github.com/zxing-cpp/zxing-cpp/assets/6124410/16c8fe2b-552a-4c4f-9d01-4c72c6ff6250)

etc

![image](https://github.com/zxing-cpp/zxing-cpp/assets/6124410/5ec95e4f-a8b5-41ca-aafc-df8364f427bb)

![image](https://github.com/zxing-cpp/zxing-cpp/assets/6124410/ba22c501-ef28-47f1-8291-97ebc42269d1)

**Comment by LeonnardoVerol** [comment]
This change (`textRole`) fixed one of the crashes on my end (The immediately one)

![image](https://github.com/zxing-cpp/zxing-cpp/assets/6124410/d97fb9b2-a4b4-456a-8ce5-8d4288e3347d)

**Comment by axxel** [comment]
Thanks for the detailed set of screenshots. You seem to know your way around a debugger. Would it be possible for you do something along the lines of what I described [here](https://github.com/zxing-cpp/zxing-cpp/pull/543#issuecomment-1488235310)? The goal would be to generate a png-file from your camera input that I can then use to reproduce the issue on my machine. This (second) crash has likely nothing to do with Qt.

The immediate crash might but to get closer to that problem, a trace of that crash would be required as well.

**Comment by LeonnardoVerol** [comment]
## Video:

https://github.com/zxing-cpp/zxing-cpp/assets/6124410/84256c92-99ac-451d-be93-59f81b46aa22

## Image: 

![crashImage](https://github.com/zxing-cpp/zxing-cpp/assets/6124410/1b58e901-be4e-4dd6-8b67-599d483f94d0)

## Other

QT Kit: Desktop Qt 6.3.2 MSVC2019 64bit
QT Build: Debug & Release (Crash on both)

PS: "Try Harder" option freezes the app

## System Info

OS Name: Microsoft Windows 11 Pro
OS Version: 10.0.22621 Build 22621
Processor: AMD Ryzen 7 5800X3D 8-Core Processor, 3401 Mhz, 8 Core(s), 16 Logical Processor(s)
BaseBoard Product: PRIME B450M-GAMING/BR
Installed Physical Memory (RAM): 32,0 GB

**Comment by axxel** [comment]
Thanks. I tried to replicate the problem with this image without success. I see in your video that you applied my suggested idea differently than I had in mind. Please remove the if-statement you added and instead add the following one inside the `evaluate` function directly before the line `ret = evaluate(points);` where the assert happened earlier:
```
    if (points.empty())
       throw 1;
```

Then please use the saved png file and put it into `ZXingReader`. The same throw should happen there. Then I can properly start debugging.

**Comment by LeonnardoVerol** [comment]
I did the requested change and got the same result.

BUT, I think I know why you can't replicate it. 
I tested with `6.5.1 MinGW` and it did **Not** crash. But it does with MSVC2019.

That original PR/Code does avoid the crash on MSVC2019

```
if (points.empty())
       return false;
```

With this new information, let me know if you need anything else. 

Sadly, I can't change the build of the codebase I am working on... So until there is an official fix, I will be using that piece of code.

**Don't leave us MSVC2019 hanging =p**

**Comment by axxel** [comment]
Using MinGW might 'fix' your specific crash (failed assert) because the MinGW implementation of `vector::back()` might simply not have that assert. But I highly doubt that the reason your `points` vector is ending up being empty has anything to do with the compiler.

Please send me the png files from my suggested `throw 1` variant and please also test if your build of `ZXingReader` runs into the same `throw 1` statement. If it does not, then this also explains why I can't reproduce it and we'd have to keep digging elsewhere.

**Comment by LeonnardoVerol** [comment]
I did the requested change and got the same results, yesterday.
Funny... is not crashing today

**Comment by axxel** [comment]
Given your silence on the matter, I assume you were not able to reproduce the crash and save the image for inspection?

**Comment by axxel** [comment]
Did you by chance find a sample that triggers the assert? I just got some feedback from someone else who might have the same issue but there is no chance he can get access to a sample. If you could not find one either, I will fix the symptom without knowing the cause.

**Comment by LeonnardoVerol** [comment]
Other than the one above, not yet (sadly, that one stopped triggering)

I will try triggering that crash again, this weekend

**Comment by LeonnardoVerol** [comment]
![crashImage_1698435124768](https://github.com/zxing-cpp/zxing-cpp/assets/6124410/1b960218-a1b2-42af-9934-ab82a9683015)

https://github.com/zxing-cpp/zxing-cpp/assets/6124410/f65871aa-e181-48cf-8c00-803e7833d9a7

**Comment by LeonnardoVerol** [comment]
1)
try Harder: off
Matrix Codes: off
Others: on

2) enable Matrix Codes -> Crash

**Comment by LeonnardoVerol** [comment]
Probably a good place to add a check would be here

Line 59: `template <typename T> bool evaluate(const std::vector<PointT<T>>& points) { return evaluate(&points.front(), &points.back() + 1); }`

![image](https://github.com/zxing-cpp/zxing-cpp/assets/6124410/6d0c3dde-6668-4f1c-b275-f31bd9a0924d)

**Comment by LeonnardoVerol** [comment]
I dont know if this helps...

![image](https://github.com/zxing-cpp/zxing-cpp/assets/6124410/b392e6f6-c5c0-4874-8fe3-271c30c25f3e)

**Comment by LeonnardoVerol** [comment]
![crashImage_1698436822498](https://github.com/zxing-cpp/zxing-cpp/assets/6124410/94a566d4-25e2-4a48-a358-3be70f37dddf)

**Comment by axxel** [comment]
Thanks for working on this again. Unfortunately neither of the two images triggers the problem for me. Can you confirm that if you simply use `ZXingReader` in a debug build with those images, you hit the same assert?

**Comment by axxel** [comment]
> I dont know if this helps...

I think it did help. :). It made me realize that it is indeed quite possible that I could end up with a set of points who's regression line is in fact further away than 3 pixels from _all_ individual points. I still don't understand how the code could end up placing those random points into the `line` but that is enough insight for me to fix this without feeling that I missed something completely.

**Comment by LeonnardoVerol** [comment]
> Thanks for working on this again. Unfortunately neither of the two images triggers the problem for me. Can you confirm that if you simply use `ZXingReader` in a debug build with those images, you hit the same assert?

I havent been able to trigger like that. Even using the camera, nowadays, I have to wiggle around a few times

> EDIT: Are you using the current HEAD or some older version?

I am still using the same version from when this issue started.
