### ISSUE TITLE
Version of web demo

### ISSUE THREAD

**Issue by Felix00643298** [zxing-cpp/zxing-cpp#594]
Does anyone know the version of zxing web demo is using?
I just realized the web demo has better recognization ablity than my local ZxingReader?
I am currently using python binding with version 2.0.0.
Thanks in advance.

**Comment by axxel** [comment]
The web reader demo is a little newer than 2.1.0 but in terms of detection rate it is equivalent to 2.1.0. See the release notes for info about improvements of 2.1. over 2.0.

**Comment by axxel** [comment]
Can you confirm that the 2.1 version of the python module behaves the same as the web-version? If so, please close this issue, if not, please send me a sample image that shows the different behavior of the two.

**Comment by Felix00643298** [comment]
> Can you confirm that the 2.1 version of the python module behaves the same as the web-version? If so, please close this issue, if not, please send me a sample image that shows the different behavior of the two.

I am not sure yet. Will test it next week.
I just upgraded my Python module from 2.0.0 to 2.1.0.
Sure, I am closing this issue. Thanks!
