### ISSUE TITLE
ZxingReader (compiled by C++20) cannot recognize datamatrix, but web demo can

### ISSUE THREAD

**Issue by Felix00643298** [zxing-cpp/zxing-cpp#602]
I tried to compile the project (version 2.1.0) on ubuntu by adding `set(CMAKE_CXX_STANDARD 20)`in CMakeLists, and compile the project by following commands:
```
mkdir build
cd build
cmake ..
make
make install
```
but built reader still cannot recognize the datamatrix. However, web demo can recognize the same image.
I am wondering is there anything I did wrong while compiling?
gcc version is `gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)`.
Thanks.

**Comment by Felix00643298** [comment]
ok, I believe it is because of the version of g++. I don't know the recommand version. I fixed this issue by upgrade to g++11.

**Comment by axxel** [comment]
Good that you found a solution to your problem.
