### ISSUE TITLE
Qml Qt6 Error

### ISSUE THREAD

**Issue by niqt** [zxing-cpp/zxing-cpp#603]
In the last example for qml with Qt6 there are code problem, (object/variables undefined), but a part that (fixing), the app crash.

**Comment by niqt** [comment]
I'm not able to rebuid my project,i deleted it and i'm not able to recreate the same situation. To avoid missunderstanding is possible to have instruction how to integrate this library in a Qt project? I'm trying on iOS and it's a pain.

**Comment by axxel** [comment]
I don't have any experience with iOS+Qt. Sorry.

**Comment by LeonnardoVerol** [comment]
@niqt , are you using qmake?

**Comment by niqt** [comment]
CMake

**Comment by axxel** [comment]
Are you still having issues building the Qt6 sample? If so, can you provide details what exactly is not working?

**Comment by niqt** [comment]
Yes, now I'm using another library :(. In any case, on ios not discovery the Qrcode and on Android crashes.
