### ISSUE TITLE
No matter what I do, Windows only builds a Debug build

### ISSUE THREAD

**Issue by israelidanny** [zxing-cpp/zxing-cpp#605]
I tried to build this lib in accordance to instructions. The build runs just fine, but no matter what I do, it outputs to `/core/Debug/ZXing.lib` in the build folder. Even though it explicitly prints that it will default to "Release".

**Comment by axxel** [comment]
As you can see from the Github Actions [log](https://github.com/zxing-cpp/zxing-cpp/actions/runs/5765801496/job/15632481102#step:6:131) of the windows build, this seems to work just fine. Although there the build type is explicitly requested as `Release` and the used `cmake` build command explicitly contains the `--config` option, see [here](https://github.com/zxing-cpp/zxing-cpp/actions/runs/5765801496/job/15632481102#step:6:2). That may be required for multi-config build tools like MSVC?

**Comment by israelidanny** [comment]
You're absolutely right @axxel ! The explicit `--config` was the missing piece. Thank you <3
