### ISSUE TITLE
Inconsistent linear barcode detection between `ReadBarcode()` and `ReadBarcodes()`

### ISSUE THREAD

**Issue by KirillZhingalov** [zxing-cpp/zxing-cpp#606]
I am encountering an issue with the zxing-cpp library where the results from the C++ version and the Python wrapper differ significantly when performing barcode detection on the same image.
Run barcode detection using the C++ version of zxing-cpp with the following command:
```
./build/example/ZXingReader ./diff.jpeg
```
Output:
```
Text:       "3592751842147"
Bytes:      33 35 39 32 37 35 31 38 34 32 31 34 37
Format:     EAN-13
Identifier: ]E0
Content:    Text
HasECI:     false
Position:   171x502 559x502 557x586 176x586 
Rotation:   0 deg
IsMirrored: false
IsInverted: false
Lines:      2
Country:    FR
```

But using Python wrapper:
```
>>> result = zxingcpp.read_barcode(Image.open('diff.jpeg'))
>>> result is None
True
```

Env:
```
zxing-cpp Library Version: ZXingReader 2.0.0
Python Version: zxing-cpp 2.0.0
OS: Ubuntu 20.04.5 LTS
python version: 3.8.10
gcc version: 9.4.0
cmake version: 3.16.3
```
[Image to reproduce the results](https://drive.google.com/file/d/1N-ZuSrMJzQniOB5I05Nzj0CMSwsZ-GkJ/view?usp=sharing)

**Comment by axxel** [comment]
The difference comes not from c++ vs python but from `read_barcode` vs `read_barcodes` the latter is used in `ZXingReader`. This should basically fix your original issue but I actually expected the two functions to behave the same in this case. I'll investigate what is going on.

**Comment by KirillZhingalov** [comment]
Also, found couple cases when C++ and Python code give different result (using correct method in Python)

## Example 1
Python:
```
>>> result = zxingcpp.read_barcodes(Image.open('./diff_1.png'))
>>> [res.text for res in result]
['823233724068']
```
C++:
```
./build/example/ZXingReader ./diff_1.png 
Text:       "823233724068"
Bytes:      38 32 33 32 33 33 37 32 34 30 36 38
Format:     UPC-A
Identifier: ]E0
Content:    Text
HasECI:     false
Position:   404x88 127x88 126x211 400x211 
Rotation:   180 deg
IsMirrored: false
IsInverted: false
Lines:      54
Country:    US/CA

Text:       "823233724068 15"
Bytes:      38 32 33 32 33 33 37 32 34 30 36 38 20 31 35
Format:     UPC-A
Identifier: ]E3
Content:    Text
HasECI:     false
Position:   404x89 37x89 36x213 400x213 
Rotation:   180 deg
IsMirrored: false
IsInverted: false
Lines:      62
Country:    US/CA
Add-On:     15
Issue #:    15
```
[Example image](https://drive.google.com/file/d/1PT29ZWd4Kcrjcii0EAS_Qao6jZFS4fkX/view?usp=sharing)

## Example 2
Python:
```
>>> result = zxingcpp.read_barcodes(cv2.imread('./diff_3.png'))
>>> [res.text for res in result]
['823233724068']
```
C++:
```
./build/example/ZXingReader ./diff_3.png 
Text:       "823233724068 15"
Bytes:      38 32 33 32 33 33 37 32 34 30 36 38 20 31 35
Format:     UPC-A
Identifier: ]E3
Content:    Text
HasECI:     false
Position:   48x46 400x46 399x164 45x164 
Rotation:   0 deg
IsMirrored: false
IsInverted: false
Lines:      98
Country:    US/CA
Add-On:     15
Issue #:    15
```
[Example image](https://drive.google.com/file/d/1M2SOujTZQZKC30Tee0IEKWtiNeXog3dN/view?usp=sharing)

**Comment by axxel** [comment]
> I'll investigate what is going on.

I did and the reason is that the 'density' of the line scan is increased when looking for multiple symbols in one scan (see [here](https://github.com/zxing-cpp/zxing-cpp/blob/81b405ba4800cccf8e8d5440052be5adebbc2ed4/core/src/oned/ODReader.cpp#L92)). While this is indeed not intuitive (I forgot about this myself), it is not obviously the wrong thing to do...

There is a balance of runtime performance vs detection performance involved and it also has something to do with the history of this particular code. Comments welcome.

**Comment by axxel** [comment]
Well, since no-one commented on the situation, I consider this discussion to be over. ;)
