### ISSUE TITLE
PDF 417 via the MultiformatWriter possibly broken

### ISSUE THREAD

**Issue by einhugur** [zxing-cpp/zxing-cpp#608]
Is the PDF 417 via MultiformatWriter broken ? 

I get this when testing:

![PDF417](https://github.com/zxing-cpp/zxing-cpp/assets/42967211/6a569be2-4e71-4e47-b92c-c45f31a1e182)

Other types seem to work fine with same code like QR Code and Aztec

**Comment by axxel** [comment]
calling `ZXingWriter pdf417 "This is a PDF417" test.png` produces a perfectly fine `test.png` file. So I assume you are doing something wrong with interpreting the memory layout or simply the dimensions of the returned `BitMatrix`. The fact that square symbologies (QR and Aztec) work for you but this rectangular one (PDR417) does not and the bottom black part of your image makes me take that guess.

**Comment by axxel** [comment]
Closing for lack of feedback.
