### ISSUE TITLE
Make a pod available for the iOS wraper or a way to use in a podspec

### ISSUE THREAD

**Issue by AbijahKaj** [zxing-cpp/zxing-cpp#623]
Hello!
Is there a way to use the iOS wrapper in a `podspec` file? Or is there an available pod of the wrapper? I only found [this one](https://github.com/zxingify/zxingify-objc), but it seems outdated and it's written in objc.

Thanks in advance.

**Comment by axxel** [comment]
There is currently no `podspec` file available/included in `zxing-cpp` but @benjohnde who maintains the repo you linked to just recently [mentioned](https://github.com/zxing-cpp/zxing-cpp/pull/619#issuecomment-1730923196) that he wants to work on 'our' iOS wrapper code. So maybe he would be in the best possible position to provide a CocoaPods integration? :)

**Comment by benjohnde** [comment]
Hi there @AbijahKaj, you can nowadays use CocoaPods alongside with SPM. Is there any particular reason you want to use CocoaPods? I can tackle a podspec in the upcoming week, with the recent PR #630 you should be able to inject the dependency with ease by just providing this repository in Xcode (Package Dependency Window).

**Comment by benjohnde** [comment]
btw you can already give it a try by specifying the branch `feat/ios-wrapper-improvement` and temporarily using my fork `https://github.com/benjohnde/zxing-cpp` as package url.

**Comment by AbijahKaj** [comment]
Hey @benjohnde !
Thanks for the message, I'm making a react native module, so a Podspec is the only way to go, I tried some not-so-clean hacks to add SPM but it's not being consumed by my module.

Thanks I'll try your branch.

**Comment by axxel** [comment]
As explained by @alexmanzer [here](https://github.com/zxing-cpp/zxing-cpp/pull/630#issuecomment-1766046411), the whole CocoaPods universe is about to go under soonish? I have to admit that I usually tend towards his "legacy guys" reaction and would question the introduction of some already outdated distribution solution. (I will for example require c++20 support in the upcoming `WriteBardcode` API, or maybe I should even be consequent and go for C++23, looking at my calendar ;)).

On the other hand, I also appreciate if the user base of this library grows... sigh ;).

**Comment by AbijahKaj** [comment]
Hi @axxel !
As you probably know, Cocoapods is also used in many other massively used tools/frameworks, so I don't think it's going anywhere anytime soon. Just look at how many people use react native or flutter, if you want to add an iOS native module to those, the only way to go is Cocoapods.

So it's not legacy support but just a standard way besides SPM that is being used in the mobile development industry.

**Comment by benjohnde** [comment]
@axxel I do believe @alexmanzer has a point there! Not quite sure if anybody is still using Carthage though but for CocoaPods, there is a reason that this is still widely used. I would add to the list of react-native and flutter the Kotlin Multiplatform realm. We are using mainly SPM but for some projects, we still rely on CocoaPods as the KMP-iOS-dependency integration has yet to be met by some SPM implementation. The only way to integrate iOS dependencies in a KMP project is CocoaPods.

I believe things will change rapidly with the new [Swift / C++ interop](https://www.swift.org/documentation/cxx-interop/) but it doesn't harm to offer the CocoaPods solution as well.

**Comment by axxel** [comment]
Due to your combined effort to convince me to include a podspec, I am now convinced. ;)

**Comment by axxel** [comment]
@benjohnde / @alexmanzer would any of you provide a little bit of substance regarding the various options regarding the inclusion of the library into an iOS project to the [README.md](https://github.com/zxing-cpp/zxing-cpp/blob/master/wrappers/ios/README.md). I mean the CocoaPods vs. SPM vs. manual inclusion situation.

**Comment by alexmanzer** [comment]
It would definitely be good to update the README and give some info and examples about integration and usage.

I'm unfortunately away for the next two weeks and probably won't get around to it before then. 🙈

**Comment by benjohnde** [comment]
I can make a suggestion and @alexmanzer can finalise it afterwards!

**Comment by ryantrem** [comment]
> Hey @benjohnde ! Thanks for the message, I'm making a react native module, so a Podspec is the only way to go, I tried some not-so-clean hacks to add SPM but it's not being consumed by my module.
> 
> Thanks I'll try your branch.

@AbijahKaj if you are thinking of making a React Native module wrapper for zxing-cpp, it may be worth starting a dedicated [discussion](https://github.com/zxing-cpp/zxing-cpp/discussions) on this. My team has created a high performance React Native wrapper that fully polyfills the [BarcodeDetector](https://developer.mozilla.org/en-US/docs/Web/API/BarcodeDetector) WebAPI, which has the advantage of allowing the same JavaScript code for barcode detection to work in either a browser (that supports the BarcodeDetector API) or a React Native app. We've thought about trying to contribute this back as OSS, but it is more challenging without having zxing-cpp available as a pod (since Xcode doesn't really have any CMake integration). If a zxing-cpp pod is possibly on the horizon, then it makes this easier, and we would reconsider contributing back what we have.

**Comment by axxel** [comment]
With the 2.2.0 release done, I went ahead and did the initial cocoapods publishing: https://github.com/CocoaPods/Specs/blob/master/Specs/1/6/a/zxing-cpp/2.2.0/zxing-cpp.podspec.json

If I search for "zxing-cpp" on https://cocoapods.org/ it is not found though. Maybe it needs some internal synchronization?

Note: I don't have a macOS for testing available (`pod trunk` also worked on Linux), so I don't know if `pod 'zxing-cpp'` now actually works.

**Comment by alexmanzer** [comment]
Yes, it seems to have worked. If you search for the pod with `pod search zxing-cpp`, it will be found in the official Cocoapod repository; so it should be possible to integrate it into the podfile without any problems.

```
axm@axm-mbp ~ % pod search zxing-cpp

-> zxing-cpp (2.2.0)
   C++ port of ZXing
   pod 'zxing-cpp', '~> 2.2.0'
   - Homepage: https://github.com/zxing-cpp/zxing-cpp
   - Source:   https://github.com/zxing-cpp/zxing-cpp.git
   - Versions: 2.2.0 [cocoapods repo]
   - Subspecs:
     - zxing-cpp/Core (2.2.0)
     - zxing-cpp/Wrapper (2.2.0)
```

**Comment by benjohnde** [comment]
Only the search seems to be broken: https://cocoapods.org/pods/zxing-cpp

**Comment by axxel** [comment]
The screenshot of this error message seems to be cropped. Can you please copy the text and post it here instead?

From what I see, it seems like there is a bug in the c++ library included in folly? `zxing-cpp` does not know anything about a `folly/CancellationToken.h` file.

You are saying you can compile 2.2.0 with react-native by building the project "manually" but not using the provided `pod`?

**Comment by vokhuyetOz** [comment]
if i have no `"zxing-cpp"` in Podfile => compile success
if i install `"zxing-cpp"` => compile error

```
yarn run v1.22.21
$ react-native run-ios
info Found Xcode workspace "example.xcworkspace"
info Found booted iPhone SE (3rd generation)
info Building (using "xcodebuild -workspace example.xcworkspace -configuration Debug -scheme example -destination id=56503433-94AB-4290-B10A-82B4B2C17817")
▸ Running script '[CP-User] [Hermes] Replace Hermes for the right configuration, if needed'
▸ Running script '[CP-User] Generate Specs'
▸ Compiling zxing-cpp-dummy.m
▸ Compiling zueci.c
▸ Compiling ZXIWriterOptions.mm
▸ Compiling ZXIPosition.m
▸ Compiling ZXIResult.mm
▸ Compiling ZXIReaderOptions.mm
▸ Compiling ZXIPosition+Helper.mm

❌  /Users/ci-cd-rabiloo/H_Rabiloo/example/ios/Pods/RCT-Folly/folly/experimental/coro/Result.h:22:10: 'folly/CancellationToken.h' file not found

#include <folly/CancellationToken.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~


▸ Compiling ZXIPoint.m
▸ Compiling ZXIGTIN.mm
▸ Compiling ZXIFormatHelper.mm
▸ Compiling ZXIErrors.mm
▸ Compiling ZXIBarcodeWriter.mm
▸ Compiling ZXIBarcodeReader.mm
▸ Compiling ZXBigInteger.cpp
▸ Compiling WhiteRectDetector.cpp
    Run script build phase 'Bundle React Native code and images' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'example' from project 'example')
    Run script build phase '[CP-User] [Hermes] Replace Hermes for the right configuration, if needed' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'hermes-engine' from project 'Pods')

info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor 

error Failed to build iOS project. "xcodebuild" exited with error code '65'. To debug build logs further, consider building your app with Xcode.app, by opening 'example.xcworkspace'.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by axxel** [comment]
This looks like an issue with your build setup. Please have a look at https://github.com/facebook/react-native/issues/31452. Maybe one of those steps helps in your case, too.

**Comment by vokhuyetOz** [comment]
i tried all workaround in [facebook/react-native/issues/31452](https://github.com/facebook/react-native/issues/31452) before but no success.
other information:
 `react-native 0.64.0 + pod "zxing-cpp", :git => 'https://github.com/zxing-cpp/zxing-cpp.git'` -> worked
`react-native 0.73 + pod "zxing-cpp"` -> error above
`react-native 0.73 + pod "zxing-cpp", :git => 'https://github.com/zxing-cpp/zxing-cpp.git'` -> error above

**Comment by axxel** [comment]
So your latest findings only confirm my hypothesis that this is an internal react native issue. Please get in touch with that project to further investigate.
