### ISSUE TITLE
Data matrix codes on large images remains undetected

### ISSUE THREAD

**Issue by nwils** [zxing-cpp/zxing-cpp#629]
I compiled the zxing library version 2.1.0 using c++ standard 20 and g++ version 9.4 on Ubuntu 20.04. I tried to detect a data matrix code in the image using the opencv code in the examples.  Unfortunately the code was not detected. I tested the same image on the web demo and the data matrix code in the image was detected. I have attached the image here. 
I tried setting hints tryHarder and GlobalHistogram for the detection. But the code remains undetected on large images. The code is detected if the image is cropped to the data matrix code area. Is there any size limitation for the data matrix code detection?
Can you please provide some hints on detecting data matrix codes on large images?
Thank you.
![test_image_dmcode](https://github.com/zxing-cpp/zxing-cpp/assets/65023541/f9b768d3-8910-425a-a42c-3fe866bd341b)

**Comment by axxel** [comment]
When I process this image with my local `ZXingReader` binary, the symbol gets detected just fine. After having had a look at https://gcc.gnu.org/wiki/cxx-coroutines, I fear that gcc only started supporting co-routines (which is what we need from c++-20 in this case) with version 10. So gcc 9.4 will simply not work to get what you want.

**Comment by axxel** [comment]
Update: according to my comment [here](https://github.com/zxing-cpp/zxing-cpp/issues/386#issuecomment-1223658682) you actually need at least gcc-11 for this to 'just work'.

**Comment by nwils** [comment]
I compiled the ZXing library with C++-20 standard and gcc-11. Now it detects the code in large images. Thank you very much.
