### ISSUE TITLE
Rotated 1D codes merge is not working precisely as non rotated one

### ISSUE THREAD

**Issue by fedormsv** [zxing-cpp/zxing-cpp#631]
In actual implementation of detecting rotated 1D code coordinates are rotated right after detecting code in a line.
It makes following merge with previously obtained results working on rotated coordinates. 
That merge is using operator==, where dTop and dBot are calculated in assumption codes are not rotated.
This is one of the reason there are multiple fixes to that operator== (merge criteria). 

As the rotated flag is not changed within DoDecode function and is used only to get line content, the fix would be to rotate only final results, keeping the internal code independent from this rotated flag.

**Comment by axxel** [comment]
Do you have an example showing the issue you are trying to fix?

**Comment by fedormsv** [comment]
I'm trying to contribute with changes I did during last few months. I
should look a bit for the test case of this fix. I'll submit it asap.

**Comment by axxel** [comment]
Thanks for your effort. I was asking for the sample to help me better understand the issue and your proposed fix. I'm preparing a new release. So, if you find that sample soonish, that would be nice. ;).

**Comment by axxel** [comment]
If you can't find a sample, maybe you can describe what it looked like? I mean horizontal vs. vertical codes of different or the same content?

**Comment by fedormsv** [comment]
Hello,
indeed, that's what I tried to do on the issue #631.
What I observed is that identical code (it was code128) in rotated and non
rotated version was reported with different dimensions:
the rotated one was either smaller or had more than one part.That actually
meant that merging a newly detected line with previously obtained results
was not working correctly. As merge criteria is incorporated in
Result::operator==, I found that internal comparison was done in assumption
of non rotated code (e.g. it was comparing bottom edge-top edge distances
between rectangles, while for rotated codes it should be left edge-right
edge distance).

As rotate is an argument of DoDecode function that is used only on
obtaining line and then rotating coordinates, I found that rotating only
final results would be a more stable and easy to maintain implementation.

I'm sorry for not quickly providing a sample. I was checking my test data
at the moment of receiving your email.
I'm afraid changes done between the fix on my side and a pull request
submission could neutrilize the problem I had (as operator== of Results was
a bit improved). Good lesson: I should contribute by pull requests quicker:)

BTW, regarding that operator, I remember there was a bug in merge
fnctionality where 'if(other == result)' was replaced by 'if(result ==
other)'.
It means operator== is not symmetrical and thus breaking usual semantic of
the language. May be to avoid confusion its non symmetrivcal part should be
moved to a function, e.g. IsJoinable.

Best regards,
-------------------
Fedor Moiseev

**Comment by axxel** [comment]
Thanks for your reply. To make sure I understood you correctly:

1) You had an issue where a rotated code128 symbol was not reported as one but two or more with identical content because the merge heuristic failed here?

2) The current HEAD revision does not show the problematic behavior with your test image anymore so the issue can be considered fixed?

If you still have that image where you know it was not working at some time in the past, I'd still be interested in having a look at it.

**Comment by fedormsv** [comment]
Yes, the issue was with the rotated code128.
Indeed it seems to be detectable with the HEAD.

I'm afraid I found a merge related issue (because zxing now uses 90 degrees
rotation and not 270 anymore) in my pull request and will close it.

You can find my test images attached. What is still problematic: +- 90
degrees rotated images are reported with half of lines with code (~120
instead of ~240).

Thank you for taking care of the repo. It evolved a lot within the last few
years.

Best regards,
Fedor Moiseev

**Comment by axxel** [comment]
> You can find my test images attached.

There is nothing attached. Maybe email attachments don't work in github. Can you login and use the github web-gui to add your image here?

**Comment by fedormsv** [comment]
![kkk270](https://github.com/zxing-cpp/zxing-cpp/assets/4365210/82693ec4-d0e5-4aa8-abd2-99161fcb77ee)
![kkk000](https://github.com/zxing-cpp/zxing-cpp/assets/4365210/68f33231-6264-47fa-9df7-d4f84ec3516a)
![kkk090](https://github.com/zxing-cpp/zxing-cpp/assets/4365210/ca400154-ec14-40bb-90a6-bff4926036a1)
![kkk180](https://github.com/zxing-cpp/zxing-cpp/assets/4365210/7fe43ed1-4a4d-4423-a403-52ff145aae3b)

**Comment by axxel** [comment]
> What is still problematic: +- 90 degrees rotated images are reported with half of lines with code (~120 instead of ~240).

I can't reproduce this. If you use the second image and rotate it 90° and save it again, you get the same line count. Note that the first and the second image have different sizes. That will influence the precise placement and and potentially number of scan-lines used during scanning.
