### ISSUE TITLE
Why can't this code128 code be decoded

### ISSUE THREAD

**Issue by layfolk233** [zxing-cpp/zxing-cpp#651]
![c064d83907598c109d4054027c8889b](https://github.com/zxing-cpp/zxing-cpp/assets/73208956/535d5bb4-69b0-4964-ba7b-792c287641c2)

**Comment by axxel** [comment]
The problem is the combination of resolution and sharpness/contrast. At least one of them needs to be higher for `zxing-cpp` to work here.
