### ISSUE TITLE
Publishing aar to mavenCentral

### ISSUE THREAD

**Issue by adrienbusin** [zxing-cpp/zxing-cpp#655]
Please, is it possible to publish your aar to mavenCentral instead of build an aar manualy ? 

Thanks a lot !

**Comment by axxel** [comment]
Yes, this is going to happen soonish. Please see the discussion in #636 .

**Comment by axxel** [comment]
Update: there is now a `SNAPSHOT` version available. To access it, you need to touch at least 3 files in your app:

1) `settings.gradle.kts`
```
dependencyResolutionManagement {
    repositories {
        maven(url = "https://s01.oss.sonatype.org/content/repositories/snapshots")
    }
}
```

2) `build.gradle.kts`:
```
dependencies {
    implementation("io.github.zxing-cpp:android:2.1.0-SNAPSHOT")
}
```

3) `your-app.kts`
```
import zxingcpp.ZXingCpp
```

Before I publish the final release, I'd like to hear from at least 2 of @markusfisch @benjohnde @adrienbusin @okarmazin that this works for them. Please note that the class-path/namespace recently changed from `com.zxingcpp` to `zxingcpp`.

**Comment by markusfisch** [comment]
Works for me 👍

**Comment by adrienbusin** [comment]
Works for me too 👌

**Comment by benjohnde** [comment]
Brilliant! Nice :)

**Comment by adrienbusin** [comment]
Hello @axxel did you push 2.2.0 version to [mavenCentral](https://central.sonatype.com/search?q=io.github.zxing-cpp) ? I don't find it, but in your [readme](https://github.com/zxing-cpp/zxing-cpp/tree/master/wrappers/android) It's written that 2.2.0 is available into MavenCentral ? 
Thanks 🙂

**Comment by axxel** [comment]
Sorry for the confusion but the 2.2 release is not out, yet.

See the recent discussion about remaining inconsistencies. (Github mobile app does not help me in finding the #-number... :-/ )

**Comment by adrienbusin** [comment]
Ok ! @axxel so when do you plan to release a new version add push it to mavenCentral ? thanks 🙂

**Comment by axxel** [comment]
Done: https://central.sonatype.com/artifact/io.github.zxing-cpp/android
