### ISSUE TITLE
Inlcude files to go with the lib? 

### ISSUE THREAD

**Issue by oziphantom** [zxing-cpp/zxing-cpp#676]
I'm on Windows and I've build with CMAKE and MSVC to see if there was any difference. I get a `ZXing.lib` , but I don't get any "include" headers to go with it? 
Do I pull out all the headers from `main/src` and the keep the children directories? 
Do I only need the top level ones? 
Do I just need a select few? 

Is there a tutorial on how to include this in another project somewhere?

**Comment by axxel** [comment]
Just because it might not be obvious where to find the headers exactly. The list starts [here](https://github.com/zxing-cpp/zxing-cpp/blob/5214892ccd68264f9bc3a81c02ec0f7d54719077/core/CMakeLists.txt#L155) and ends in line 190.

Did you find a solution to your problem?

**Comment by oziphantom** [comment]
Sorry, 

cmake --install did nothing, but I was able to find and copy the header files from the CMakeList file in core. 

Thank you for your help.
