### ISSUE TITLE
accessing result bounding box

### ISSUE THREAD

**Issue by farfromrefug** [zxing-cpp/zxing-cpp#677]
i looked but did not anything that would seem like it. i see there is a position in Result but it does not seem to be related d to the bounding box.
for reference I would like to draw in live on a camera feed the bounding box of the found bar codes.
is that possible ?

**Comment by axxel** [comment]
> telqte d

I can't extrapolate which word you meant to write here. The `Position` of the result contains the 4 corners of the detected symbol. You can use those to calculate a bounding box if you need it more coarse. Simply take the minimum and maximum of all x and y coordinates of the 4 corers and you have the bounding box.

You definitely can draw the location into a live camera feed. In fact the ZXingQtCamReader and ZXingOpenCV examples do that, as well as the Android wrapper demo app and the wasm based [live demo](https://zxing-cpp.github.io/zxing-cpp/demo_cam_reader.html).

**Comment by farfromrefug** [comment]
@axxel sorry fot mispelled word (writing from a phone I fixed it).
and thanks a lot for your answer. i will look at zxingopencv example. sorry i should have thought of looking there first.

**Comment by farfromrefug** [comment]
@axxel i managed to get the boundingBox using `getPosition`. It works perfectly for QRCode.
I have an issue with UPCA though. Most of the time the "box" has no "height" i would say if you look at an upca code.
Sometimes i get an height but most of the time it is almost 0.
The width is always correct though.
Do you have any idea?

**Comment by axxel** [comment]
Once one line is detected you have a valid barcode, so there is no point in spending more processing time. There is one thing you can do, though: use `ReadBarcodes()` and set `DecodingHints::tryHarder` to `true`. That will increase the width but will only detect the complete barcode in perfect conditions.

**Comment by farfromrefug** [comment]
@axxel ok makes total sense! i prefer it to be fast thanks a lot!
