### ISSUE TITLE
C++17 leads to poor DataMatrix detection

### ISSUE THREAD

**Issue by minorplanet0313** [zxing-cpp/zxing-cpp#686]
When I compile the zxing library with C++17, it performs poorly in DataMatrix detection and it's difficult to achieve successful detection. However, when I compile it with C++20, the performance is perfect, and it successfully detects all test images. Is there something wrong with my settings? How can I make the C++17 compiled version perform similarly to C++20? 
Here are the test images: 

![image](https://github.com/zxing-cpp/zxing-cpp/assets/70427549/7066220e-33eb-4cfa-b357-a595766a21d9)

![image3](https://github.com/zxing-cpp/zxing-cpp/assets/70427549/a31fc525-9a78-42a4-a61e-368c54dcf4fa)

**Comment by axxel** [comment]
> How can I make the C++17 compiled version perform similarly to C++20?

You can not. See #386.

**Comment by minorplanet0313** [comment]
Reading a data matrix does what I want, but when I use c++17 and run "./ZXingReader image.png" it just says "No barcode found". I'm using ubuntu 20.04, gcc version 9.4.0, cmake version 3.16.3.

Is it true that the C++17 version cannot detect the above two images?
