### ISSUE TITLE
Could I decode a QR in a esp32 with only 4MB of code space?

### ISSUE THREAD

**Issue by mark-hahn** [zxing-cpp/zxing-cpp#687]
Is this possible or is it a ridiculous idea?

**Comment by axxel** [comment]
Interesting question, although the size of the binary should not be an issue at all, I believe. The more limiting factor is most likely the RAM size and the size of your images. Do you have concrete numbers for those?

**Comment by mark-hahn** [comment]
I've already spec'd out the sram.  I only need to know about code size.

Since I asked the question I found code that runs in my esp32: https://github.com/alvarowolfx/ESP32QRCodeReader

So I've answered my own question.  But mucho thanks for your reply.
