### ISSUE TITLE
Zxing-cpp 2.x uses C++17 features in headers, forcing downstream project to use C++17 or higher

### ISSUE THREAD

**Issue by hosiet** [zxing-cpp/zxing-cpp#689]
This may not be a bug, but probably needs some documentation.

https://github.com/zxing-cpp/zxing-cpp/blob/ce602b468109576ce4e976a576105eb0201dab03/core/src/BitHacks.h#L38

`std::is_integral_v` is only supported with C++17 or higher. If any project is using Zxing-cpp headers but gets built with C++14, the build will fail. Please see https://buildd.debian.org/status/fetch.php?pkg=linphone&arch=amd64&ver=5.2.0-4%2Bb1&stamp=1702768636&raw=0 for an example.

I am not sure if it is intended. If yes, please mention that zxing-cpp does not support anything below C++17. This is different from "Written in pure C++17 (/C++20)" because the problem lies in the headers, not library body.

**Comment by axxel** [comment]
Yes, you need a C++17 compiler to build client projects. If cmake is used to build the client project and the `ZXing::ZXing` library is added then this should be taken care of automatically. This change has been introduced and documented in https://github.com/zxing-cpp/zxing-cpp/releases/tag/v2.0.0.

I'll add a hint to the README text.
