### ISSUE TITLE
Unable to detect multiple Code39 barcodes

### ISSUE THREAD

**Issue by MikeCas** [zxing-cpp/zxing-cpp#690]
Axxel,
Similar to this issue:
https://github.com/zxing-cpp/zxing-cpp/issues/386

In my Python code,
`results = zxingcpp.read_barcodes(img) `
returns only one item when it scans the image below.

I am running zxing-cpp-2.2.0 
Can you please help?

![Code39A B](https://github.com/zxing-cpp/zxing-cpp/assets/18174693/28525e35-29d5-4496-99c8-01f87950253e)

**Comment by axxel** [comment]
The resolution of the first code is too low. I claim it is an invalid barcode symbol. It seems to be a downsampled version of the second code but so much so that some bars effectively disappear.

**Comment by axxel** [comment]
> If I rotate my camera 180 degrees, the program can recognize "WIKPEDIA". but cannot recognize the 2nd simultaneously

What do you mean by "the program"?

**Comment by phantomgz** [comment]
I have built and run "example/ZXingQtCamReader"

**Comment by axxel** [comment]
I see. Let me refer to [this discussion](https://github.com/zxing-cpp/zxing-cpp/discussions/716#discussioncomment-8410190) since this is about Qt and not about Code39.
