### ISSUE TITLE
If I want to support a non-standard QRCode is it possible to use existing code?

### ISSUE THREAD

**Issue by Haoxiqiang** [zxing-cpp/zxing-cpp#698]
![WXACode fa3d686a](https://github.com/zxing-cpp/zxing-cpp/assets/3881604/ae24c7b1-92d8-4bb2-9aaf-369a9d5d2777)
This is a QR code designed by WeChat.
It is composed of `19 * 19` dot matrix data, which is less than the standard `21*21` of the QR code.
Contains information similar to `P.URL.CN/0C12345678901234ABC` that total length is 28 characters.
I nkow that the zxing implementation supports 40 different QR versions, so I'd like to ask whether it is feasible to extend support for newer versions on the current repo.

**Comment by axxel** [comment]
This is definitively not a QRCode. It might have features in common with a QRCode and therefore it might be possible to leverage existing code but to be able to find that out, one would need a specification for this symbology.

**Comment by Haoxiqiang** [comment]
you are right. the number of rows and columns is 19, which is less than 21. It's not the definition of QRCode.
I try to analyze the code to see if it can achieve my needs.

**Comment by axxel** [comment]
If you can make this work and want to contribute something back to the project, please let me know.
