### ISSUE TITLE
QR code plus DataMatrix recognition is slower than before on a certain image

### ISSUE THREAD

**Issue by duanqn** [zxing-cpp/zxing-cpp#699]
Hi, I recently tried to recognize a QR code with 2 different versions of ZXing-cpp (d2ed8152aa866714348ffb712672d38b64f030b7 vs 0dbcb6d97debeb7ae5bd180dcd83fecca0132808). I found that the recognition time is greatly increased on a certain image (50 ms vs 125 ms).

I scanned through the commit history and found some enhancement & new feature (e.g. Model 1) in QR code recognition over the last year, so I am guessing the longer recognition time is related to the new feature code. But if anyone is interested in the performance difference, I'm providing the image for investigation.
![0](https://github.com/zxing-cpp/zxing-cpp/assets/21275667/d01918d3-ef32-4254-86d4-7f25936eb2b4)

**Comment by axxel** [comment]
That sounds strange. I care *a lot* about performance and would never accept a 100% performance regression (after I spent months on squeezing out a few percent here and there).
* Can you repeat the test and make sure you are only looking for QRCodes (`setFormats(BarcodeFormat::QRCode)`)?
* How did you measure the runtime?
* Are you building in c++17 or c++20 mode and made sure both builds use the same c++ version?

**Comment by duanqn** [comment]
Hi @axxel , sorry for the late response. I can repro this performance issue with our project but I have not reproduced with standalone ZXing-cpp. On my test machine, the time to recognize this image is about 25ms vs 100 ms for the two commits. I excluded some overhead in our code and this new result is more accurately reflecting the time consumption of ZXing-cpp.

We are looking for QRCodes and DataMatrix codes.

This is how we invoke ZXing-cpp to recognize the image:
```
#if (ZXING_VERSION_MAJOR == 2 && ZXING_VERSION_MINOR >= 2) || ZXING_VERSION_MAJOR > 2
    // 2.2.0 and above
    ZXing::ReaderOptions hints;
    hints.setEanAddOnSymbol(ZXing::EanAddOnSymbol::Read);
#else
    ZXing::DecodeHints hints;
#endif
    hints.setFormats(ZXing::BarcodeFormat::QRCode | ZXing::BarcodeFormat::DataMatrix);
    hints.setMaxNumberOfSymbols(1);
    hints.setTryDownscale(false);
    hints.setTryRotate(true);
    hints.setTryHarder(true);

    hints.setBinarizer(ZXing::Binarizer::FixedThreshold);
    auto results = ZXing::ReadBarcodes(zxing_view, hints);

    if(results.empty())
    {
        hints.setBinarizer(ZXing::Binarizer::GlobalHistogram);
        hints.setTryDownscale(true);
        hints.setDownscaleFactor(2);
        hints.setDownscaleThreshold(150);
        results = ZXing::ReadBarcodes(zxing_view, hints);
    }
```

I have confirmed that, in both versions of ZXing-cpp, the recognition succeeds in the second invocation of `ZXing::ReadBarcodes`.
The time measurement is done by surrounding the above code block with `std::chrono::high_resolution_clock::now()` timers. (We do have some extra post processing logic so it is not purely measuring `ZXing::ReadBarcodes`, but those parts are not changed.)

**Comment by duanqn** [comment]
I think my previous title might be a bit misleading.

**Comment by axxel** [comment]
> but I have not reproduced with standalone ZXing-cpp

You mean, you did not try it with `ZXingReader` or you did but it does not show the same performance regression?

> I have confirmed that, in both versions of ZXing-cpp, the recognition succeeds in the second invocation of `ZXing::ReadBarcodes`.

I assume this 2-phase approach is meant to increase detection performance? I suggest you change your approach and include the `tryDownscale(true)` part in the first phase. At least for this image, this will make the detection 2-3x faster.

> The time measurement is done by surrounding the above code block with `std::chrono::high_resolution_clock::now()` timers. (We do have some extra post processing logic so it is not purely measuring `ZXing::ReadBarcodes`, but those parts are not changed.)

Just to be really sure: please add a second measurement just around the above code, so nothing except zxing-cpp code is included.

Also to better get an idea of where the regression happens, could you please test both versions with only `QRCode` and then only `DataMatrix` detection. And then with both only `FixedThreshold` and only `GlobalHistogram` binarizer?

**Comment by duanqn** [comment]
> You mean, you did not try it with ZXingReader or you did but it does not show the same performance regression?

I did not try. It seems that ZXingReader does not provide a convenient interface for controlling binarizer.

>  I assume this 2-phase approach is meant to increase detection performance? I suggest you change your approach and include the tryDownscale(true) part in the first phase. At least for this image, this will make the detection 2-3x faster.

I don't understand this part. Can you explain a bit more? Do you mean I should set `tryDownscale(true)` for the first pass? From my understanding it has no effect on FixedThreshold binarizer.

> Just to be really sure: please add a second measurement just around the above code, so nothing except zxing-cpp code is included.
> Also to better get an idea of where the regression happens, could you please test both versions with only QRCode and then only DataMatrix detection. And then with both only FixedThreshold and only GlobalHistogram binarizer?

Good suggestions. I will do that, but probably need a few more days.

**Comment by axxel** [comment]
> I did not try. It seems that ZXingReader does not provide a convenient interface for controlling binarizer.

That is true. I still recommend doing it (without any change of the binarizer). Please use the following command line:

```bash
MEASURE_PERF=1 ZXingReader -format qrcode,datamatrix -noinvert -1 <your file>
```
That will conveniently report the consumed time for the `ReadBarcodes()` function. On my machine with current HEAD I get (on a 4 year old Intel Core i9 mobile processor):

```
/home/axel/zxing/#699.png QRCode "https://www.napnameplates.com/"
time: 22.98 ms per frame
```

> I don't understand this part. Can you explain a bit more? Do you mean I should set `tryDownscale(true)` for the first pass? From my understanding it has no effect on FixedThreshold binarizer.

Yes, that is what I meant. The downscaling has an effect in this case because it effectively acts as a noise filter which fixes the pixel noise you get from oversampling the monitor pixels with a high resolution camera. If you `tryDownscale` in the first pass, this qrcode gets detected there already.

I believe what you had in mind was an earlier discussion about how the downscaling particularly helps with the `LocalAverage` binarizer. But you don't use that one at all. I would actually suggest to use that one in second pass as it has a substantially higher success rate in general compared to `GlobalHistogram`. If you have a very specific set of input images (like only those monitor scans) than things might be different for your case, though.

**Comment by axxel** [comment]
Note:
 * if you are sure that inverted codes are not of interest to you, then `setTryInvert(false)` which will save a few extra ms.
 * if by any chance you can get greyscale data (like using the `Y` channel in a mobile app setting) instead of RGB, then use that, definitively helps reducing the runtime as well (for the GlobalHistogram and LocalAverage binarizers, the FixedThreshold one simply uses the 'G' channel and saves on the RGB->Lum conversion).

**Comment by duanqn** [comment]
> Also to better get an idea of where the regression happens, could you please test both versions with only QRCode and then only DataMatrix detection. And then with both only FixedThreshold and only GlobalHistogram binarizer?

Only QRCode:
100 ms

Only DM:
19 ms

Only QRCode Only 1st pass:
5 ms

Only QRCode Only 2nd pass:
96 ms

From this I think the additional overhead in my code is negligible, right? Because (overhead + 1st pass + 2nd pass) = 100 (ms), and (overhead + 1st pass) + (overhead + 2nd pass) = 5 + 96 = 101 (ms).

**Comment by axxel** [comment]
So, to sum up your latest findings:

* `ZXingReader -format qrcode,datamatrix` is actually considerably faster with the new version.
* The slow part in your code is the qrcode detection with the GlobalHistogram binarizer.
* We assume the old code was faster with that but you have not measured it explicitly.

That makes me believe the binarizer is at fault. That is actually 'possible' in the sense that I don't performance test that binarizer. To close the gap between your own code and the ZXingReader results: could you change the second pass to use the LocalAverage binarizer and measure again?

**Comment by duanqn** [comment]
To my surprise, after changing to `LocalAverage` binarizer the time reduced from ~100 ms to ~50 ms.

**Comment by duanqn** [comment]
For LocalAverage binarizer, the time comparison (old vs new) is 43 ms vs 47 ms, which is roughly similar. I previously thought LocalAverage was slower than GlobalHistogram so I actually put it in the third pass.

**Comment by axxel** [comment]
> For LocalAverage binarizer, the time comparison (old vs new) is 43 ms vs 47 ms, which is roughly similar. I previously thought LocalAverage was slower than GlobalHistogram so I actually put it in the third pass.

Interesting. A couple things:
 * If I use the `GlobalHistogram` binarizer in current `ZXingReader`, I still don't see this performance difference?!? Can you confirm this with your `ZXingReader` build and try this with both old and new versions?
 * In general, you are right that the global binarizer is faster but in this case I assume the slowdown comes from the fact that you have those oversampled monitor pixels. But that is just a guess a.t.m.

**Comment by duanqn** [comment]
> * If I use the `GlobalHistogram` binarizer in current `ZXingReader`, I still don't see this performance difference?!? Can you confirm this with your `ZXingReader` build and try this with both old and new versions?

That is true. If I use the new code and override binarizer to `GlobalHistogram`, I get:

```
time: 14.35 ms per frame
```

However, if I combine this `GlobalHistogram` with `options.setDownscaleFactor(2);`, then it suddenly goes up to

```
time: 101.10 ms per frame
``` 

I think it is not the binarizer itself causing such slow performance, but some of (probably one of) the images produced in the series of downscaling. Maybe some image triggers time-consuming operations in QRCode detection / recognition. It is possible that a large number of QR patterns are detected, considering the black/white grid-like noise in this image. We have observed this kind of slowness before on other images with grid-like backgrounds, like photos of a mat.

If my theory is correct, I don't think the regression is a very serious issue, since it is only occurring on this image and the image itself has something to blame for. Maybe it's worth checking if the change is intentional and that's all.

**Comment by axxel** [comment]
I found the "problem". The change causing the performance degradation is [this](https://github.com/zxing-cpp/zxing-cpp/commit/cf975502708f443216f99692974bc9c80e070dcc#diff-5d6a0ddd024f3102876492f502a41becde594de81f46d942b87b64cbfdc1985b). You can easily "fix" your specific problem by setting [this line](https://github.com/zxing-cpp/zxing-cpp/blob/e1dead79d57a4ab1b2c467edd8eee289fbd9f1a8/core/src/qrcode/QRDetector.cpp#L40) to `false`.

Besides that one, you have the other two options of 
1. `setDownscaleFactor(3)`
2. `setBinarizer(Binarizer::LocalAverage)`

There might be something else that can be done about this particular issue but I'd have to further investigate.

**Comment by axxel** [comment]
And for easier testing in the future, there is now a `-binarizer` command line option in `ZXingReader`.

**Comment by duanqn** [comment]
Thanks for the verification! So this is an intended change for better recognition success rate.

**Comment by duanqn** [comment]
> There might be something else that can be done about this particular issue but I'd have to further investigate.

I think it may be an easier task to specifically optimize for `setMaxNumberOfSymbols(1)` ? We can look at the most likely (largest? most clear?) patterns first, if we can decode a QR code out of them, then stop processing all the other patterns.
