### ISSUE TITLE
can it work on C++11?

### ISSUE THREAD

**Issue by PureHing** [zxing-cpp/zxing-cpp#702]
@axxel   Hi,
Deployed on embedded, can it work on C++11?
If I want it to work on C++11, how can it be modified while maintaining performance as much as possible? Can you provide some suggestions?

**Comment by axxel** [comment]
My first suggestion: update/replace your tool chain. ;)

The library will obviously not compile with a c++11 compiler. If you tried, you'll get a lot of compiler errors. Out of the top of my head, I have no idea how much code would need to be touched/modified to make it compile on c++11. If I personally had this goal, I'd simply try it and see what happens and then start disabling features and work around issues and see how far I can get. I personally don't have any interest to go that direction. The next major release will likely require at least c++20.

**Comment by PureHing** [comment]
Ok.Thanks
