### ISSUE TITLE
QR code generated with ZXingWriter does not encode the full content

### ISSUE THREAD

**Issue by duanqn** [zxing-cpp/zxing-cpp#712]
Hi, I am using ZXingWriter for my first time and I try to generate a QR code with content "ABC\0DEF" (with a NUL byte), but the generated QR code only contains "ABC". Meanwhile, Zint can generate a correct QR code.
![out](https://github.com/zxing-cpp/zxing-cpp/assets/21275667/e325a0ac-a892-4e7e-ba85-ec221fa67b6c)

**Comment by axxel** [comment]
How did you generate the symbol with `zxing-cpp`?  Can you show the code?

**Comment by duanqn** [comment]
Hi @axxel , I modified the source code and added

```
*text = "ABC\0DEF";
```

below [this line](https://github.com/zxing-cpp/zxing-cpp/blob/master/example/ZXingWriter.cpp#L98)

**Comment by axxel** [comment]
Well, that can't possibly work, see [here](https://stackoverflow.com/questions/42874699/stdstring-stops-at-0). It might be necessary to use the `std::wstring` overload of [`encode()`](https://github.com/zxing-cpp/zxing-cpp/blob/c580d1e0c0c53a58cea1789b5a9dd8e78b5a53e1/example/ZXingWriter.cpp#L152).

**Comment by duanqn** [comment]
I see. My stupid mistake :(
