### ISSUE TITLE
Delete function for WriterOptions in C API takes in wrong pointer type

### ISSUE THREAD

**Issue by hha1501** [zxing-cpp/zxing-cpp#746]
Hello,

I use zxing-cpp with .NET wrapper and everything was great. I recently tried to use the new writer API and notice there is a bug in `ZXingC.h` and `ZXingC.cpp`. These delete functions should take in `ZXing_WriterOptions` instead of `ZXing_CreatorOptions`.

[L276 in ZXingC.h](https://github.com/zxing-cpp/zxing-cpp/blob/a8d1a3706682c1fac810e8a374fede264ed5afa7/core/src/ZXingC.h#L276)
[L365 in ZXingC.cpp](https://github.com/zxing-cpp/zxing-cpp/blob/a8d1a3706682c1fac810e8a374fede264ed5afa7/core/src/ZXingC.cpp#L365)

Thank you for actively maintaining this library and trying new things (e.g. zint integration for writer/encoder).

**Comment by axxel** [comment]
Thanks for pointing that out. I assume you are not talking about [this .NET wrapper](https://www.nuget.org/packages/ZXingCpp/)? Did you have a look at it? Anything missing (apart from the writer support, or course)?

**Comment by hha1501** [comment]
Ah. I am using zxing-cpp with a custom .NET wrapper I wrote myself based on your implementation in [wrappers/dotnet](https://github.com/zxing-cpp/zxing-cpp/blob/master/wrappers/dotnet/ZXingCpp/ZXingCpp.cs). The reader part works fine but I need writer support so I add P/Invoke bindings from [`ZXingC.h`](https://github.com/zxing-cpp/zxing-cpp/blob/master/core/src/ZXingC.h) and a thin C# wrapper.

If I have time I could upstream my additions to .NET wrapper (writer support + a small test).

**Comment by axxel** [comment]
Ah, thanks for sharing. Feel free to post your changes as a PR. Otherwise, I'll add those myself soonish.

**Comment by axxel** [comment]
My take on the writer API is [available](https://www.nuget.org/packages/ZXingCpp/) now.

**Comment by hha1501** [comment]
> My take on the writer API is [available](https://www.nuget.org/packages/ZXingCpp/) now.

Thanks for letting me know. I'm glad that your implementation is very similar to mine and I can drop my custom solution for now. However there is other thing I would like to add to .net wrapper. I see you use `IDisposable` pattern for `Image` [here](https://github.com/zxing-cpp/zxing-cpp/blob/75ae138c7a9d29effd767c046c615000a3a09be9/wrappers/dotnet/ZXingCpp/ZXingCpp.cs#L248) and I think other wrapper classes can/should have `IDisposable` implemented too. I will create a new issue for this and probably a follow-up PR.

Also nice [catch](https://github.com/zxing-cpp/zxing-cpp/commit/1a3aa5163526785c6d44838540b5aa4c0a4af4fc) on the default marshalling of byte as 4 byte int.
