### ISSUE TITLE
Excuse me, is there any way to download the barcode pictures in the test/samples directory?

### ISSUE THREAD

**Issue by layfolk233** [zxing-cpp/zxing-cpp#748]

**Comment by axxel** [comment]
`git clone --depth 1 https://github.com/zxing-cpp/zxing-cpp.git` :)

**Comment by axxel** [comment]
New option: download the tarball from the release page: https://github.com/zxing-cpp/zxing-cpp/releases/download/v2.2.1/test_samples.tar.gz

**Comment by layfolk233** [comment]
thanks
