### ISSUE TITLE
Data Matrix Code not detected at particular rotations, but detected when rotated by 90,180, etc

### ISSUE THREAD

**Issue by RakeshJaz** [zxing-cpp/zxing-cpp#749]
Background : I am try to read a code mounted on a fidget spinner spinning at high speeds, using a raspberry pi 5 with Cam V 3, using Python wrapper.

I noticed that the data matrix code was not being read at a particular angle, i rotated the image in software and fed it back (90deg, 180deg) ... then the code was read successfully. If i use some pre-processing like De-noise or Binary it is able to read, but the raw image is not able to be recognised.

Images Below
Original image : cannot read

![11](https://github.com/zxing-cpp/zxing-cpp/assets/67786056/0b824749-57c0-4b27-b6bf-f3e4b52b10c7)

rotated image : can read

![13](https://github.com/zxing-cpp/zxing-cpp/assets/67786056/58134a9d-82eb-4d97-a2f0-46503ad8da0b)

De-noised Image : Can read [ too less de-noise or too much denoise = cannot read ]
![denoise](https://github.com/zxing-cpp/zxing-cpp/assets/67786056/cada6034-a193-40d6-b04b-c2c960d6c6aa)

Binary image : can read 

![binary](https://github.com/zxing-cpp/zxing-cpp/assets/67786056/7943af7f-c72f-4bbd-972e-df5d7ce55664)

Note : image can be read if i centre it before reading. Original image can be read by generic phone code reader  apps

**Comment by RakeshJaz** [comment]
Thank you for your replies. I cloned the project and installed with setup.py
This made the initial code readable, but broke some other codes which are below.
The codes are not particularly difficult, but they are not readable at a particular angle.
My observation is that they fail when oriented diagonally (45 deg, 135 deg, etc ). I tried all four diagonal orientations and the code was not able to be read.

*Note : Codes are readable in all angles, i had to rotate them to a very specific angle to make it fail. 

I enabled the  return_errors = True, the code location was not found for image 1, but found at a wrong location for image 2. Looks like some issue with the locator / Detector code. I will try to look through the source if i can find anything.

Please take a look at image 2 below, the code location is found at a random un-related location (Green Box), although the code looks easy to recognise.

Image1 
![14](https://github.com/zxing-cpp/zxing-cpp/assets/67786056/08970abf-4e85-49c5-9638-aaebabe0e632)

Image2 - return_errors = True - code coordinates found at bottom right (Green box)
![15](https://github.com/zxing-cpp/zxing-cpp/assets/67786056/9656aa63-389c-4ba5-8b96-373fbf4c65d6)

Image3 - another diagonal orientation which fails to read
![16](https://github.com/zxing-cpp/zxing-cpp/assets/67786056/30a72795-de9c-4a5f-a8e9-0c599337e53b)

**Comment by axxel** [comment]
Thanks for providing more details. Your are right: there is a general issue in the detector that is related to 45% angles. I'm looking into it.
