### ISSUE TITLE
Assert (with debug build) in NumberOfTrailingZeros()

### ISSUE THREAD

**Issue by huycn** [zxing-cpp/zxing-cpp#756]
Running reader code in debug mode, I got an assert `assert(v != 0)` with the stack below:
```
ZXing::BitHacks::NumberOfTrailingZeros<unsigned int,void>(unsigned int v) Line 85	C++
ZXing::BitHacks::NumberOfTrailingZeros<unsigned __int64,void>(unsigned __int64 v) Line 85	C++
ZXing::GetPatternRow<unsigned char const *>(ZXing::Range<unsigned char const *> b_row, std::vector<unsigned short,std::allocator<unsigned short>> & p_row) Line 385	C++
ZXing::GetPatternRow(const ZXing::BitMatrix & matrix, int r, std::vector<unsigned short,std::allocator<unsigned short>> & pr, bool transpose) Line 130	C++
ZXing::QRCode::FindFinderPatterns(const ZXing::BitMatrix & image, bool tryHarder) Line 72	C++
ZXing::QRCode::Reader::decode(const ZXing::BinaryBitmap & image, int maxSymbols) Line 80	C++
ZXing::MultiFormatReader::readMultiple(const ZXing::BinaryBitmap & image, int maxSymbols) Line 67	C++
ZXing::ReadBarcodes(const ZXing::ImageView & _iv, const ZXing::ReaderOptions & opts) Line 185	C++
ZXing::ReadBarcode(const ZXing::ImageView & _iv, const ZXing::ReaderOptions & opts) Line 144	C++
```

The initial value of v is 64bit 0xff00000000000000. Then arrive [this line](https://github.com/zxing-cpp/zxing-cpp/blob/master/core/src/BitHacks.h#L70), it will become 0.

I would remove that assert. The following code seems to handle correctly 0 case, but I'm not sure, hence this issue.

Thanks!

P.S. Attached is input image that can reproduces the assert with `ZXingReader` example.
![almost_black](https://github.com/zxing-cpp/zxing-cpp/assets/6164995/51797866-d6c9-4ed1-9e69-6a7b77c1172a)

**Comment by axxel** [comment]
Nice to hear from you again after all this time :). Thanks for reporting this.
