### ISSUE TITLE
error C3688 when compiling python wheel with MSVC

### ISSUE THREAD

**Issue by asesidaa** [zxing-cpp/zxing-cpp#757]
When I try to use `pip install .` to install the python wrapper with MSVC, which compiles core, it throws error C3688 invalid literal suffix 

This is caused by files BitMatrixIO.cpp, BitMatrix.cpp and WriteBarcode.cpp contains non ascii characters, and on my system the default code page does not support these characters.

As a solution, either save these files as UTF-8 with BOM, or add [/utf-8](https://learn.microsoft.com/en-us/cpp/build/reference/utf-8-set-source-and-executable-character-sets-to-utf-8?view=msvc-170&viewFallbackFrom=vs-2019) switch in cmake with something like
```cmake
add_compile_options("$<$<C_COMPILER_ID:MSVC>:/utf-8>")
add_compile_options("$<$<CXX_COMPILER_ID:MSVC>:/utf-8>")
```

**Comment by axxel** [comment]
Surprising that the CI system did not pick this up. Does this happen only in HEAD or also with the 2.2.0 release?
