### ISSUE TITLE
Cannot decode some QRCode after fix for #709

### ISSUE THREAD

**Issue by asesidaa** [zxing-cpp/zxing-cpp#760]
After this [commit ](https://github.com/zxing-cpp/zxing-cpp/commit/6b9f16a79d1965197fb9da4a733090c1efc6c346) which fixes #709 , python wrapper with default Binarizer can no longer decode the following QRCode. 
Although it can be decoded with Binarizer.FixedThreshold, since it looks quite standard, the implementation probably can be improved somehow since it is the default.

This QRCode contains some custom encrypted data with magic header S12

![2](https://github.com/zxing-cpp/zxing-cpp/assets/26689773/fe24a090-49af-4ba8-896b-ad2450c442b3)

**Comment by axxel** [comment]
I can't reproduce your issue: the `demo_reader.py` and python module from current HEAD decode this just fine.

**Comment by asesidaa** [comment]
Here's the correct output with `binarizer=zxingcpp.Binarizer.FixedThreshold`

```
Found barcode:
 Text:    "S12<NUL><SOH><DC1> IḞéCp<DEL>JFFS<ESC>ṗ-r<U+8E>Ä9ä<EOT>N<CAN>ṫtD<U+81><DC4>ṫÿex"
 Format:   BarcodeFormat.QRCode
 Content:  ContentType.Binary
 Position: 123x123 900x123 900x900 123x900
```

**Comment by asesidaa** [comment]
Yeah, so it does not work on Windows building with MSVC but works on Linux (WSL) building with GCC

**Comment by axxel** [comment]
Arghh, that is very unpleasant news because I will have a hard time debugging this. Can you do me a favor and also test if the `ZXingReader` binary from the example directory displays this behavior (MSVC vs GCC)?

**Comment by asesidaa** [comment]
Another bad news, on windows (msvc) this works in debug build but not in release build. On Linux this works on all builds

I am pretty sure it's this algorithm since in the previous commit which does not have this new algorithm works (I use `git bisect` to find this commit). Previous commit does not have this issue (same for the version on pypi.)

**Comment by axxel** [comment]
Interesting... Have you seen my edited comment about the #define? Your git bisect makes this test almost unnecessary but not quite.

**Comment by asesidaa** [comment]
Yes, I can confirm that use new algorithm cannot detect in this case in release build, comment it out and it can detect just fine

**Comment by asesidaa** [comment]
Interesting, if I enable the generation of `thresholds_new.pnm` file in `HybridBinarizer.cpp`, it works fine

**Comment by axxel** [comment]
It seems you are on track to debug this all by yourself. Very much appreciated. 😁

**Comment by asesidaa** [comment]
So the cause is definitely the optimize of `ThresholdImage` function.
I tried two workarounds that are working, one is I surround it with [`#pragma optimize( "", off )`](https://learn.microsoft.com/en-us/cpp/preprocessor/optimize?view=msvc-170&redirectedfrom=MSDN), the other is insert something into this function, in my case a std::string and it also works

**Comment by axxel** [comment]
Oh my. This might very well turn out to be a compiler bug. :-/. To get some idea about what might go wrong, we'd need to have a look at the calculated `BitMatrix`. Could you maybe compile your release build with `-DPRINT_DEBUG`? Then execute `ZXingReader -format qrcode -noscale -noinv <image-file.jpg>`. You should then find a `qr-log.pnm` in your current directory. Could you recode this into a png (just for file-size management) and add it here?

**Comment by asesidaa** [comment]
Sure. The log file that I get for release build is completely black, while for debug build I get the original image back, so I guess something happens on parameter passing due to optimization?
![qr-log-release](https://github.com/zxing-cpp/zxing-cpp/assets/26689773/a46500d1-129b-4a15-8c60-1bf20152e8d0)
![qr-log](https://github.com/zxing-cpp/zxing-cpp/assets/26689773/5f99d1c0-b829-40b9-accd-128d3654e234)

**Comment by axxel** [comment]
Can you tell me what exactly you mean by "insert a std::string into the function"? I'm wondering what the least invasive workaround could be. I would especially want to avoid a workaround that has a significant runtime performance impact and the `#pragma optimize` one seems like it could be quite detrimental if `ThresholdBlock` gets inlined and then not vectorized.

**Comment by asesidaa** [comment]
Hmm, for some reason I cannot use std::string as workaround on my laptop. Currently the only thing works is to disable optimization for this function.

**Comment by asesidaa** [comment]
Ok, so the issue is vectorization of [this](https://github.com/zxing-cpp/zxing-cpp/blob/9ca06842ea7c565fc6dda3ba48d8e12239e33b82/core/src/HybridBinarizer.cpp#L60) loop,
If I add [`#pragma loop(no_vector)`](https://learn.microsoft.com/en-us/cpp/parallel/auto-parallelization-and-auto-vectorization?view=msvc-170#auto-vectorizer) it can produce the correct result

**Comment by asesidaa** [comment]
Ahh I go it, `ThresholdBlock` function's `threshold` should be of type `T_t`.
```c++
static void ThresholdBlock(const uint8_t* __restrict luminances, int xoffset, int yoffset, T_t threshold, int rowStride,
						   BitMatrix& matrix)
```

Looks like with `threshold` being an int MSVC is making some incorrect vectorization
