### ISSUE TITLE
PDF417 Read Issues

### ISSUE THREAD

**Issue by alanhkahn** [zxing-cpp/zxing-cpp#770]
Hello! I am currently working on an app that will validate a users age on the client side (web). I've had a decent amount of success when using your library to scan PDF417 barcodes, but there are instances where some just straight up don't scan and I'm trying to understand why. I know there are other issues about this and I've seen that you've considered reimplementing the PDF417 reader. Are there any updates to that? In the meantime, is there anything I can do to better the results? I'd appreciate any and all feedback you could provide.

Here is an example of a PDF417 barcode that will not scan.

![pdf417-fl](https://github.com/zxing-cpp/zxing-cpp/assets/15135457/967be453-39ab-4d05-98b7-3921ae805a35)

**Comment by axxel** [comment]
There is no update on the idea of reimplementing PDF417. The issue with this specific image is that the black lines are too "thick".

If you perform a dilate operation on the image, it can successfully be scanned:
![#770-dilate](https://github.com/zxing-cpp/zxing-cpp/assets/1038346/10215dff-74df-4cd9-af27-bb6afbea4089)

**Comment by duanqn** [comment]
> There is no update on the idea of reimplementing PDF417. The issue with this specific image is that the black lines are too "thick".
> 
> If you perform a dilate operation on the image, it can successfully be scanned: ![#770-dilate](https://private-user-images.githubusercontent.com/1038346/325108098-10215dff-74df-4cd9-af27-bb6afbea4089.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NDg2NDUsIm5iZiI6MTcxMzk0ODM0NSwicGF0aCI6Ii8xMDM4MzQ2LzMyNTEwODA5OC0xMDIxNWRmZi03NGRmLTRjZDktYWYyNy1iYjZhZmJlYTQwODkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjRUMDg0NTQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NThkODg2Mjg2MmIzZDI2YTUyOTkyZmM0OGZhYTk1MjJjZWIwNjg5Y2FkOTAzNDU0OTI4NDM3NjZmNzZkNzQ5NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.72NT1a-k0JyRCeopmw5zG7JTm8Ae0DTXNsQ4C1P6GK8)

Hi @axxel , can you kindly provide some code sample for the dilation? I have seen similar cases and I want to try if dilation can also fix them.

**Comment by axxel** [comment]
Dilation is a standard image processing algorithm. I simply used GIMP to perform the dilate operation with your sample image. You'll find tons of information and sample code on the web. There is also some experimental code inside `zxing-cpp` that does in part basically a dilate operation on the the already binarized data: https://github.com/zxing-cpp/zxing-cpp/blob/c4668ab9bca779a2e88ec5355f65947472c39875/core/src/BinaryBitmap.cpp#L93-L94

**Comment by alanhkahn** [comment]
I appreciate the insight and will attempt adding dilation into the mix!

**Comment by alanhkahn** [comment]
Lastly, if I wanted to use the experimental filter, do I need to do anything in particular to enable it? Thank you in advanced.

**Comment by axxel** [comment]
To enable the experimental code you need to set the cmake variable `ZXING_EXPERIMENTAL_API` to `ON` and set the `ReaderOptions::setTryDenoise(true)`. But that will (most likely) not help you with the above issue.

**Comment by alanhkahn** [comment]
Thank you! Great work on the port.
