### ISSUE TITLE
demo_cam_reader.html "front"/"back" camera selection does not work

### ISSUE THREAD

**Issue by axxel** [zxing-cpp/zxing-cpp#772]
<sup>Originally posted by **549393092** April 24, 2024</sup>
Dear,

Could your please check the demo code
https://github.com/zxing-cpp/zxing-cpp/blob/master/wrappers/wasm/demo_cam_reader.html#L135
which will receive parameter "front" and "back" to trigger camera.
However, it seems not work. Instead it works with "user" and "environment". see [MDN doc](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia).

**Comment by axxel** [comment]
@549393092 Would you care to provide a PR with the fix?

**Comment by 549393092** [comment]
@axxel I tried to fix this issue, but seems not that simple.
When I select the camera, the updateVideoStream event is triggered, however, it will not switch the camera from front to back.
Meanwhile, when the page is loaded, error occurs in the console when initialize Zxing. The error is 
```
wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
falling back to ArrayBuffer instantiation
```
Regards

**Comment by axxel** [comment]
Thanks for trying. I currently don't have time to look into this. Maybe @Sec-ant can provide some insights?

**Comment by 549393092** [comment]
@Sec-ant Thanks! 
I tried the demo, but still can not switch the camera from front to back. What browser did you use, I am using Edge.

Yes, the initialization error is gone now. Where did you download the "zxing_reader.js" and "zxing_reader.wasm", could your please try the file in this [link](https://github.com/zxing-cpp/zxing-cpp/releases/download/v2.2.0/wasm-artifacts.zip) .

Regards

**Comment by Sec-ant** [comment]
> What browser did you use, I am using Edge.

I'm using the [Kiwi browser](https://github.com/kiwibrowser/src.next/releases/tag/8822657649) on an Android 12 phone, it's a browser based on chromium.

> Where did you download the "zxing_reader.js" and "zxing_reader.wasm"

I didn't download them somewhere, I built the files locally according to [the instructions](https://github.com/zxing-cpp/zxing-cpp/tree/master/wrappers/wasm#build).

> could your please try the file in this [link](https://github.com/zxing-cpp/zxing-cpp/releases/download/v2.2.0/wasm-artifacts.zip) .

Yes they're now deployed to this link: https://662b0f714d7ac950a81f1e03--zxing-cpp-wasm-demo.netlify.app/demo_cam_reader.html

I just changed the `front`/`back` options and I can switch the cameras normally. The aspect ratio of the video is distorted, but that's another issue.

The support for [user media capabilities/constraints](https://developer.mozilla.org/en-US/docs/Web/API/Media_Capture_and_Streams_API/Constraints) can vary much on different devices, OS systems and browsers. Here is a link you can test if your device supports certain capabilities and constraints: https://live.mdnplay.dev/en-US/docs/Web/API/Media_Capture_and_Streams_API/Constraints/_sample_.Example_Constraint_exerciser.html

For example, you can try `{ "facingMode": "user" }` and `{ "facingMode": "environment" }` in the video constraints and check if the camera switches.

**Comment by 549393092** [comment]
@Sec-ant Thanks for so detailed explanation.
I tried to deploy it on github and the initialization error is gone. Because I deploy it on local with nginx originally, I guess there is some configuration issue, I will try to fix.

For the second issue, I still can't switch camera from front to back.
After some research, it works by adding one line code which is recommended by [MDN.](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia#front_and_back_camera) How do you think?
```
const updateVideoStream = function (deviceId) {
	// To ensure the camera switch, it is advisable to free up the media resources
	if (video.srcObject) video.srcObject.getTracks().forEach(track => track.stop());
	
	navigator.mediaDevices
		.getUserMedia({ video: { facingMode: deviceId }, audio: false })
		......
};
```

**Comment by Sec-ant** [comment]
> After some research, it works by adding one line code which is recommended by [MDN.](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia#front_and_back_camera) How do you think?

Sure, I think this is reasonable given that it is an advisable practice!

**Comment by 549393092** [comment]
@axxel Now this topic is completed. 
Shall I create a PR for this issue, but it seems I don't have the permission. (sorry, I never done this before)

**Comment by axxel** [comment]
Yes, please create a PR. You don't need any permission to create and submit a pull request. Please consult any of the plentiful available information online to see how that can be done on github.

**Comment by axxel** [comment]
I upgraded the online WASM samples: https://zxing-cpp.github.io/zxing-cpp/demo_cam_reader.html and switching the camera works on my phone.
