### ISSUE TITLE
Error when reading specific QR and DataMatrix codes

### ISSUE THREAD

**Issue by tweinans** [zxing-cpp/zxing-cpp#773]
Hi there,

I have been using this library in a python project for a while now without issues, but have now run into an issue of which I think it might be some kind of bug.

### Problem
It happened when trying to pass a grayscale image of a qr-code: leading to the following error message:
![image](https://github.com/zxing-cpp/zxing-cpp/assets/74539321/43b159fd-5888-4c2f-b7c7-f31bb13d4414)

>     result = zxingcpp.read_barcode(image)
>     IndexError: vector::_M_range_check: __n (which is 11261) >= this->size() (which is 10500)

First I thought it might have to do with the shape of the image (105x100), however passing another image with the same shape yielded no problems.

Figuring it might have to do with the version of zxing-cpp I was using, I upgraded from 2.0.0 to 2.2.0, which fixed it for this specific qr-code, but I soon ran into a datamatrix which had the same issue:
![image](https://github.com/zxing-cpp/zxing-cpp/assets/74539321/367d92ff-c18c-4ac6-a582-6aafe8cb62d5)
>     IndexError: vector::_M_range_check: __n (which is 5108) >= this->size() (which is 5106)

### Debugging
Unsure of what the cause was, I started manipulating the image a bit, and found out that if I change certain pixel values, the error does not occur anymore. I wrote a quick script to visualize this, where on top of the original image, red dots are scattered in place of some of the pixels. These dots are the pixel locations, where if the value is changed to something else, make the image passable without errors. Note that not all, but just one single pixel value in place of one of the red pixels need to be changed. 
![qrod_40](https://github.com/zxing-cpp/zxing-cpp/assets/74539321/22c55281-bff9-4164-92e2-8b2bf8cf8e7c) 
![dmod_40](https://github.com/zxing-cpp/zxing-cpp/assets/74539321/b5c15cdc-c5d8-42c1-8fc0-263228d86fb9)

In the images above, you can see that it has something to do with the borders/code recognition part. I noticed that these were primarily originally "white" pixels, so I did the same as above but for changing the pixel value to 200, which gave the following result where the focus was more on the dark pixels: 
![qrod_200](https://github.com/zxing-cpp/zxing-cpp/assets/74539321/54bee4a2-0ea1-493f-9be7-40692e01858a) 
![dmod_200](https://github.com/zxing-cpp/zxing-cpp/assets/74539321/4831c0c9-e81e-4436-907c-60ed657c9549)

### Steps to reproduce
To reproduce this issue, you can download the unaltered pngs of the qr and datamatrix above. 
For the QR code the error occurs when using zxing-cpp 2.0.0 and for the datamatrix when using version 2.2.0.
I use python version 3.9.10, and run on a linux machine.
```
import zxingcpp
from PIL import Image

image = Image.open(<path_to_image>)
result = zxingcpp.read_barcode(image)
```

### Solution?
I am not sure exactly where this error originates unfortunately, since I do not know how the recognition and reading of visual codes is executed under the hood, so I was hoping someone here might have a clue. Note that I do not expect these qr and dm crops to give a reading, since the quality is quite poor, however it would be great to have these kind of images return "None" as it would do with a picture of a cat or something, instead of an index error referring to a size issue, stopping the execution all together.

If you need any aditional info please let me know!

**Comment by axxel** [comment]
Thanks for putting to much effort in reporting a bug. That is highly unusual. ;).

I tried to reproduce your problem but failed. I built current HEAD, then v2.2.0 then installed the pypi.org package 2.2.0 but none of them showed the issue with neither of the two images you provided. Did you build the package yourself? Can you maybe reproduce the problem with the `ZXingReader` example binary?

**Comment by tweinans** [comment]
Unfortunately something seems to have gone wrong while saving the datamatrix picture I had send in my previous message, since when I download it now it also does not give me the above described issue. 

For the following image I have triple checked it causes the issue:
![0](https://github.com/zxing-cpp/zxing-cpp/assets/74539321/f1a20122-6cc9-4c68-b878-41bac8a7a5d1)

To make sure it was not dependent on something else, I've created a new clean virtual environment (python 3.9.10), and installed only pillow (for opening the image) and zxing-cpp (2.2.0) using pip install giving me the following:
```
Package    Version
---------- -------
pillow     10.3.0
pip        21.2.4
setuptools 58.1.0
zxing-cpp  2.2.0
```
Hopefully with this new Image you can reproduce the problem.


Concerning your final comment, I am not entirely sure what you mean, would you mind elaborating a bit on what you would want me to do exactly?

**Comment by axxel** [comment]
Thanks, your latest sample triggers the issue on my machine and the fix was rather simple. If you want to test this, you can extract a suitable python wheel for your system from one of the artifacts of [this ci build](https://github.com/zxing-cpp/zxing-cpp/actions/runs/8886385554). Please close this issue if you find it to be resolved.

**Comment by tweinans** [comment]
Thanks for the quick fix!
