### ISSUE TITLE
reading the wrong code (Interleaved2of5 format)

### ISSUE THREAD

**Issue by urishab** [zxing-cpp/zxing-cpp#775]
Reader seems to be getting confused by a pretty straightforward ITF Interleaved 2of5 code.
Reading the correct code after cropping:
![crop_15](https://github.com/zxing-cpp/zxing-cpp/assets/1208625/31cf1e92-1807-4e5b-bd3c-6130c133ebfe)

But with a single dark line it gets confused as well as with a larger image:
![crop_16](https://github.com/zxing-cpp/zxing-cpp/assets/1208625/6d116404-7495-4522-85cb-b12a95ddbeaa)
![crop_right](https://github.com/zxing-cpp/zxing-cpp/assets/1208625/b9923d3f-d765-4533-9231-37ce394cd156)

The correct code: 10602679
The wrong code: 35860313

I tested against the git head.

**Comment by urishab** [comment]
thanks for the quick answer!

**Comment by urishab** [comment]
I tried the same image with 4 online readers.
Two gave the right code and two refused to read the code.
None of them gave the wrong answer.
Also how is it possible to read it in reverse? the start and stop portions are quite distinct

**Comment by axxel** [comment]
The lack of resolution on the one side and the incentive to be as tolerant to noise/quantization errors on the other are the explanation. The start pattern is 1, 1, 1, 1, the stop pattern is 1, 1, 2. Now if encounter a width pattern of 2, 2, 3, 2. Then you want that to be accepted as both. That said, I was also surprised to see the reason why you got a wrong result.

**Comment by urishab** [comment]
I get wanting to be tolerant but in this case it's a really bad outcome. This code has no checksums or anything to guard against a bad read. literally the only thing is the start/stop guards.
I actually got multiple bad reads from this phenomenon and it's repeatable.

I think ideally scanning a barcode with "STOP_PATTERN_2" would be considered a good result and scanning with "STOP_PATTERN_1" would be considered scanning with an "error" so could still be accessed.

What do you think?

**Comment by axxel** [comment]
The spec says the wide bars are between 2x and 3x as wide as the narrow ones. But it also gives a reference decoding algorithm that is checking this property directly instead of doing this "pattern matching" with 2 different patterns which is more a relic of the past or the fact that this utility is used elsewhere.

I'll change that, which is pretty straight forward. We'll see what that does with respect to eliminating false positives.

If you have another sample or two with wrong results: feel free to post them here.

**Comment by urishab** [comment]
@axxel thanks, the fix you rolled really solved the issue
