### ISSUE TITLE
Zxing is not working with PDF417 for south african driving liecenses

### ISSUE THREAD

**Issue by pratikukheshe** [zxing-cpp/zxing-cpp#780]
Currently, I am implementing the zing(3.5.3) jar to read barcode from the images. In some of the cases, I am not getting the barcode in the image and in some cases result is not proper. I am expecting the 720 bytes in result but getting 1063 bytes. Here, is the sameple code

`

                        try {
			BufferedImage image = ImageIO.read(file);
			LuminanceSource ls = new BufferedImageLuminanceSource(image);
			BinaryBitmap bmp = new BinaryBitmap(new HybridBinarizer(ls));

			GenericMultipleBarcodeReader reader = new GenericMultipleBarcodeReader(new MultiFormatReader());

			Map<DecodeHintType, Object> decodeHints = new EnumMap<>(DecodeHintType.class);
			decodeHints.put(DecodeHintType.TRY_HARDER, Boolean.TRUE);
			decodeHints.put(DecodeHintType.POSSIBLE_FORMATS, EnumSet.of(BarcodeFormat.PDF_417));

			com.google.zxing.Result[] results1 = reader.decodeMultiple(bmp, decodeHints);
			int i = 0;
			for (com.google.zxing.Result result : results1) {
				System.out.println("Barcode " + ++i + ": " + result.getText());
				result.getResultPoints();
			//	parseData(decryptData(result.getResultPoints())) ;
			}
		} catch (Exception e) {
			System.err.println("Error: " + e.getMessage());
		}

`

**Comment by axxel** [comment]
You are using another project (search for "zxing" on GitHub).
