### ISSUE TITLE
Not clear what to do in order to build dll and then use it in my .Net Project

### ISSUE THREAD

**Issue by ShiddhamSharma** [zxing-cpp/zxing-cpp#788]
Hi,

I am trying to add zxing cpp in my .Net project.
I have added the Nuget package but it does not give me any output when I input an image with a QR Code.
I have never built a DLL file so I am not clear on how to exactly build the DLL file and how to reference it in the project.

Can anyone please share the steps to use zxingcpp in my project?

Thanks

**Comment by ShiddhamSharma** [comment]
![qr-code2](https://github.com/zxing-cpp/zxing-cpp/assets/68852041/aa74b30b-2673-4628-a42a-e530c029846d)

I am using this QR Code.
Yes, the BarcodeReader.From() returns an empty list as I don't get any error.

This is my code:
```
BarcodeReader detector = new BarcodeReader();
var img = SKBitmap.Decode("qr-code2.png").Copy(SKColorType.Gray8);

var iv = new ImageView(img.GetPixels(), img.Info.Width, img.Info.Height, ImageFormat.Lum);
var readBarcodes = new BarcodeReader()
{
    TryInvert = false,
    ReturnErrors = true,
    Formats = BarcodeFormats.QRCode
};

foreach (var b in readBarcodes.From(iv))
{
    MessageBox.Show($"{b.Format} ({b.ContentType}): {b.Text} / [{string.Join(", ", b.Bytes)}] {b.ErrorMsg}");
}
```

**Comment by axxel** [comment]
Both the image and your code look just fine. Wild guess: "qr-code2.png" is actually a different image?

If I copy your code into the [demo project](https://github.com/zxing-cpp/zxing-cpp/tree/master/wrappers/dotnet/ZXingCpp.DemoReader) and replace `MessageBox.Show` with `Console.WriteLine`, it detects your sample just fine.

You can also have a look at [this project](https://github.com/axxel/zxing-bench/tree/main/dotnet), which uses the NuGet package to see how it can be successfully incorporated.

**Comment by ShiddhamSharma** [comment]
Sadly, the qr code is the same image.

Just wanted to confirm is this the Nuget package for dotnet wrapper: https://www.nuget.org/packages/ZXingCpp/0.2.1-alpha

Also I checked both projects. In there you are giving SKBitmap as input whereas it is giving me error an I have to convert it to ImageView to send input to BarcodeReader

**Comment by axxel** [comment]
> Just wanted to confirm is this the Nuget package for dotnet wrapper: https://www.nuget.org/packages/ZXingCpp/0.2.1-alpha

Yes, it is.
 
> Also, I checked both projects. Where are you using the SKBitmapBarcodeReader Class? In there you are giving SKBitmap as input whereas it is giving me error and I have to convert it to ImageView to send input to BarcodeReader

The provided `SkBitmapBarcodeReader` extension class is just a means to comfortably pass `SKBitmap` objects to the reader. Since there is more text required, I chose to use the more direct approach of manually constructing the `ImageView` object in the README sample. Both ways are equivalent to each other.

I would suggest you clone the `zxing-bench` project and first make sure that you can successfully execute that on your setup.

**Comment by ShiddhamSharma** [comment]
I tried with zxing-bench but still getting empty list.

I am using Windows so not sure if that is the issue?

**Comment by axxel** [comment]
If you have build the complete project via `cmake` like you mentioned above, I suggest you try out the `example/ZXingReader` binary. That should definitively detect this qrcode.

I have not tried the .NET wrapper on Windows myself but if should not work at all, then I'd assume I would have heard about it before.

**Comment by ShiddhamSharma** [comment]
I had also asked my colleague to try zxing-bench out and even he was not able to get results. I suggest Windows might need a look again.

In the meantime, I will build the ZxingReader and try it out.

**Comment by ShiddhamSharma** [comment]
So I am getting results after testing on the ZxingReader executable.

Maybe something is missing in the windows build of nuget package?

**Comment by rohit-patil18** [comment]
Hi @axxel, I was trying to find QR code on the image above while testing it on the zxing-bench.

It gave me the following result:

![Capture3](https://github.com/zxing-cpp/zxing-cpp/assets/56926300/ba924520-c2cf-46d5-910c-42988ae24b12)

Here, ZxingCpp could not find the QR code but it could do so on the [Read Barcodes](https://zxing-cpp.github.io/zxing-cpp/demo_reader.html) demo site.

**Comment by axxel** [comment]
> So I am getting results after testing on the ZxingReader executable.
> 
> Maybe something is missing in the windows build of nuget package?

Could you please try the following:
1. find the `ZXing.dll` file in your installed NuGet package and remove it then execute your demo code. You should then get some kind of error instead of an empty list.
2. copy the `ZXing.dll` file that you built yourself together with the `ZXingReader.exe` into your NuGet package installation and see if that makes a difference.

**Comment by ShiddhamSharma** [comment]
> 1. find the ZXing.dll file in your installed NuGet package and remove it then execute your demo code. You should then get some kind of error instead of an empty list.

I got error: error MSB3030: Could not copy the file "C:\Users \r.patil\.nuget\packages\zxingcpp\0.2.1-alpha\runtimes\win-x64\native\ZXing.dll" because it was not found.

> 2. copy the ZXing.dll file that you built yourself together with the ZXingReader.exe into your NuGet package installation and see if that makes a difference.

Unhandled exception. System.EntryPointNotFoundException: Unable to find an entry point named 'ZXing_ReaderOptions_new' in DLL 'ZXing'.   at ZXingCpp.Dll.ZXing_ReaderOptions_new()
   at ZXingCpp.ReaderOptions..ctor()
   at ZXingCpp.BarcodeReader..ctor()
   at Program.Main() in D:\Github Desktop\zxing-bench\dotnet\Program.cs:line 171

**Comment by axxel** [comment]
That is some progress: at least we know now that there is a dll included and it gets loaded successfully. To fix the missing entry point error you need to reconfigure cmake with the following variables set:
```
-DBUILD_SHARED_LIBS=ON -DZXING_READERS=ON -DZXING_WRITERS=NEW -DZXING_EXPERIMENTAL_API=ON -DCMAKE_CXX_STANDARD=20 -DZXING_C_API=ON
```

**Comment by ShiddhamSharma** [comment]
Steps done:
1) `cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DZXING_READERS=ON -DZXING_WRITERS=NEW -DZXING_EXPERIMENTAL_API=ON -DCMAKE_CXX_STANDARD=20 -DZXING_C_API=ON`
2) `cmake --build build --config Release -j8`

During the second second step I am getting these errors and it stops while generating code:

In Barcode.cpp:
`C:\Users\s.sharma\zxing-cpp\core\src\libzint\zint.h(1,1): error C2059: syntax error: '.' [C:\Users\s.sharma\zxing-cpp\build\core\ZXing.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\include\list(23,1): error C2143: syntax error: missing ';' before
'{' [C:\Users\s.sharma\zxing-cpp\build\core\ZXing.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\include\list(23,1): error C2447: '{': missing function header (old
-style formal list?) [C:\Users\s.sharma\zxing-cpp\build\core\ZXing.vcxproj]
C:\Users\s.sharma\zxing-cpp\core\src\Barcode.cpp(206,7): error C2039: 'list': is not a member of 'std' [C:\Users\s.sharma\zxing-cpp\build\core\ZXing.vcxpro
j]
C:\Users\s.sharma\zxing-cpp\core\src\Barcode.cpp(206,7): error C7568: argument list missing after assumed function template 'list' [C:\Users\s.sharma\zxing
-cpp\build\core\ZXing.vcxproj]
C:\Users\s.sharma\zxing-cpp\core\src\Barcode.cpp(210,21): error C2672: 'std::next': no matching overloaded function found [C:\Users\s.sharma\zxing-cpp\buil
d\core\ZXing.vcxproj]
C:\Users\s.sharma\zxing-cpp\core\src\Barcode.cpp(210,48): error C3536: 'i': cannot be used before it is initialized [C:\Users\s.sharma\zxing-cpp\build\core
\ZXing.vcxproj]
C:\Users\s.sharma\zxing-cpp\core\src\Barcode.cpp(216,43): error C2672: 'ZXing::Size': no matching overloaded function found [C:\Users\s.sharma\zxing-cpp\bu
ild\core\ZXing.vcxproj]
C:\Users\s.sharma\zxing-cpp\core\src\Barcode.cpp(217,9): error C2672: 'std::all_of': no matching overloaded function found [C:\Users\s.sharma\zxing-cpp\bui
ld\core\ZXing.vcxproj]`

In WriteBarcode.cpp:
`C:\Users\s.sharma\zxing-cpp\core\src\libzint\zint.h(1,1): error C2059: syntax error: '.' [C:\Users\s.sharma\zxing-cpp\build\core\ZXing.vcxproj]
C:\Users\s.sharma\zxing-cpp\core\src\WriteBarcode.cpp(21,13): error C2906: 'std::default_delete<zint_symbol>': explicit specialization requires 'template <
>' [C:\Users\s.sharma\zxing-cpp\build\core\ZXing.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\include\xmemory(1486,42): error C2139: 'std::default_delete<zint_s
ymbol>': an undefined class is not allowed as an argument to compiler intrinsic type trait '__is_empty' [C:\Users\s.sharma\zxing-cpp\build\core\ZXing.vcxpr
oj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\include\xmemory(1486,63): error C2139: 'std::default_delete<zint_s
ymbol>': an undefined class is not allowed as an argument to compiler intrinsic type trait '__is_empty' [C:\Users\s.sharma\zxing-cpp\build\core\ZXing.vcxpr
oj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\include\xmemory(1515,10): error C2079: 'std::_Compressed_pair<_Dx,
zint_symbol *,false>::_Myval1' uses undefined struct 'std::default_delete<zint_symbol>' [C:\Users\s.sharma\zxing-cpp\build\core\ZXing.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\include\xmemory(1515,10): error C2079:         with [C:\Users\s.sh
arma\zxing-cpp\build\core\ZXing.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\include\xmemory(1515,10): error C2079:         [ [C:\Users\s.sharm
a\zxing-cpp\build\core\ZXing.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\include\xmemory(1515,10): error C2079:             _Dx=std::defaul
t_delete<zint_symbol> [C:\Users\s.sharma\zxing-cpp\build\core\ZXing.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\include\xmemory(1515,10): error C2079:         ] [C:\Users\s.sharm
a\zxing-cpp\build\core\ZXing.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\include\memory(3330,17): error C2139: 'std::default_delete<zint_sy
mbol>': an undefined class is not allowed as an argument to compiler intrinsic type trait '__is_constructible' [C:\Users\s.sharma\zxing-cpp\build\core\ZXin
g.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\include\type_traits(323,39): error C2139: 'std::default_delete<zin
t_symbol>': an undefined class is not allowed as an argument to compiler intrinsic type trait '__is_convertible_to' [C:\Users\s.sharma\zxing-cpp\build\core
\ZXing.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\include\memory(3367,83): error C2139: 'std::default_delete<zint_sy
mbol>': an undefined class is not allowed as an argument to compiler intrinsic type trait '__is_constructible' [C:\Users\s.sharma\zxing-cpp\build\core\ZXin
g.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\include\memory(3395,80): error C2139: 'std::default_delete<zint_sy
mbol>': an undefined class is not allowed as an argument to compiler intrinsic type trait '__is_assignable' [C:\Users\s.sharma\zxing-cpp\build\core\ZXing.v
cxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\include\type_traits(793,38): error C2139: 'std::default_delete<zin
t_symbol>': an undefined class is not allowed as an argument to compiler intrinsic type trait '__is_assignable' [C:\Users\s.sharma\zxing-cpp\build\core\ZXi
ng.vcxproj]
C:\Users\s.sharma\zxing-cpp\core\src\libzint\zint.h(1,1): error C2059: syntax error: '.' [C:\Users\s.sharma\zxing-cpp\build\core\ZXing.vcxproj]
C:\Users\s.sharma\zxing-cpp\core\src\WriteBarcode.cpp(149,17): error C2143: syntax error: missing ';' before '{' [C:\Users\s.sharma\zxing-cpp\build\core\ZX
ing.vcxproj]
C:\Users\s.sharma\zxing-cpp\core\src\WriteBarcode.cpp(149,17): error C2447: '{': missing function header (old-style formal list?) [C:\Users\s.sharma\zxing-
cpp\build\core\ZXing.vcxproj]
C:\Users\s.sharma\zxing-cpp\core\src\WriteBarcode.cpp(424,21): error C3861: 'SetCommonWriterOptions': identifier not found [C:\Users\s.sharma\zxing-cpp\bui
ld\core\ZXing.vcxproj]
C:\Users\s.sharma\zxing-cpp\core\src\WriteBarcode.cpp(426,2): error C2027: use of undefined type 'zint_symbol' [C:\Users\s.sharma\zxing-cpp\build\core\ZXin
g.vcxproj]
C:\Users\s.sharma\zxing-cpp\core\src\WriteBarcode.cpp(426,26): error C2065: 'BARCODE_MEMORY_FILE': undeclared identifier [C:\Users\s.sharma\zxing-cpp\build
\core\ZXing.vcxproj]
C:\Users\s.sharma\zxing-cpp\core\src\WriteBarcode.cpp(427,9): error C2027: use of undefined type 'zint_symbol' [C:\Users\s.sharma\zxing-cpp\build\core\ZXin
g.vcxproj]
C:\Users\s.sharma\zxing-cpp\core\src\WriteBarcode.cpp(429,2): error C3861: 'ZBarcode_Print': identifier not found [C:\Users\s.sharma\zxing-cpp\build\core\Z
Xing.vcxproj]
C:\Users\s.sharma\zxing-cpp\core\src\WriteBarcode.cpp(429,2): error C2027: use of undefined type 'zint_symbol' [C:\Users\s.sharma\zxing-cpp\build\core\ZXin
g.vcxproj]
C:\Users\s.sharma\zxing-cpp\core\src\WriteBarcode.cpp(429,2): error C2512: 'std::invalid_argument': no appropriate default constructor available [C:\Users\
s.sharma\zxing-cpp\build\core\ZXing.vcxproj]
C:\Users\s.sharma\zxing-cpp\core\src\WriteBarcode.cpp(431,51): error C2027: use of undefined type 'zint_symbol' [C:\Users\s.sharma\zxing-cpp\build\core\ZXi
ng.vcxproj]
C:\Users\s.sharma\zxing-cpp\core\src\WriteBarcode.cpp(431,67): error C2027: use of undefined type 'zint_symbol' [C:\Users\s.sharma\zxing-cpp\build\core\ZXi
ng.vcxproj]
C:\Users\s.sharma\zxing-cpp\core\src\WriteBarcode.cpp(445,21): error C3861: 'SetCommonWriterOptions': identifier not found [C:\Users\s.sharma\zxing-cpp\bui
ld\core\ZXing.vcxproj]
C:\Users\s.sharma\zxing-cpp\core\src\WriteBarcode.cpp(447,2): error C3861: 'ZBarcode_Buffer': identifier not found [C:\Users\s.sharma\zxing-cpp\build\core\
ZXing.vcxproj]
C:\Users\s.sharma\zxing-cpp\core\src\WriteBarcode.cpp(447,2): error C2027: use of undefined type 'zint_symbol' [C:\Users\s.sharma\zxing-cpp\build\core\ZXin
g.vcxproj]
C:\Users\s.sharma\zxing-cpp\core\src\WriteBarcode.cpp(447,2): error C2512: 'std::invalid_argument': no appropriate default constructor available [C:\Users\
s.sharma\zxing-cpp\build\core\ZXing.vcxproj]
C:\Users\s.sharma\zxing-cpp\core\src\WriteBarcode.cpp(452,18): error C2027: use of undefined type 'zint_symbol' [C:\Users\s.sharma\zxing-cpp\build\core\ZXi
ng.vcxproj]
C:\Users\s.sharma\zxing-cpp\core\src\WriteBarcode.cpp(452,38): error C2027: use of undefined type 'zint_symbol' [C:\Users\s.sharma\zxing-cpp\build\core\ZXi
ng.vcxproj]
C:\Users\s.sharma\zxing-cpp\core\src\WriteBarcode.cpp(453,14): error C2027: use of undefined type 'zint_symbol' [C:\Users\s.sharma\zxing-cpp\build\core\ZXi
ng.vcxproj]
C:\Users\s.sharma\zxing-cpp\core\src\WriteBarcode.cpp(456,46): error C3536: 'src': cannot be used before it is initialized [C:\Users\s.sharma\zxing-cpp\bui
ld\core\ZXing.vcxproj]
C:\Users\s.sharma\zxing-cpp\core\src\WriteBarcode.cpp(457,27): error C2109: subscript requires array or pointer type [C:\Users\s.sharma\zxing-cpp\build\cor
e\ZXing.vcxproj]
C:\Users\s.sharma\zxing-cpp\core\src\WriteBarcode.cpp(457,35): error C2109: subscript requires array or pointer type [C:\Users\s.sharma\zxing-cpp\build\cor
e\ZXing.vcxproj]
C:\Users\s.sharma\zxing-cpp\core\src\WriteBarcode.cpp(457,43): error C2109: subscript requires array or pointer type [C:\Users\s.sharma\zxing-cpp\build\cor
e\ZXing.vcxproj]
C:\Users\s.sharma\zxing-cpp\core\src\WriteBarcode.cpp(457,13): error C2660: 'ZXing::RGBToLum': function does not take 1 arguments [C:\Users\s.sharma\zxing-
cpp\build\core\ZXing.vcxproj]`

**Comment by ShiddhamSharma** [comment]
Good Update: So we created a new DLL file but we removed the -DZXING_WRITERS=NEW parameter and replaced it with the .nuget DLL. After this it is able to send me results correctly. Although I am right now only reading the Barcode so will let you know if writing is working or not.

Thanks for the help, but maybe should recheck the DLL for windows. I am still getting the above errors when I build with -DZXING_WRITERS=NEW parameter.

**Comment by axxel** [comment]
> `C:\Users\s.sharma\zxing-cpp\core\src\libzint\zint.h(1,1): error C2059: syntax error: '.' `

I believe this problem can be fixed by making sure the `zint` submodule is properly initialized. See my [README change](https://github.com/zxing-cpp/zxing-cpp/commit/91cf5ba5fb5d965e981d680107b1a869751ae940).

Please check if this works for you and if the resulting DLL can still produce proper results. The DLL inside the NuGet package comes from the [CI build](https://github.com/zxing-cpp/zxing-cpp/actions/runs/9165369998/job/25198653092).

You could also do me another favor and see what happens when you replace the DLL from your build with the one from the NuGet package and test if your `ZXingReader.exe` using that DLL still works.

**Comment by ShiddhamSharma** [comment]
So I tested ZxingReader.exe with the dll file I made yesterday and it worked fine.

> I believe this problem can be fixed by making sure the zint submodule is properly initialized. See my [README change](https://github.com/zxing-cpp/zxing-cpp/commit/91cf5ba5fb5d965e981d680107b1a869751ae940).

I tried this change but it still gave me the same error in zint.h
I made a change by replacing ` ../../../zint/backend/zint.h` in core/src/libzint/zint.h with `#include "../../../zint/backend/zint.h"` and it removed the error in that file. Though it is now giving error in similarly written files so will update after I update all of the other files.

**Comment by axxel** [comment]
> So I tested ZxingReader.exe with the dll file I made yesterday and it worked fine.

You told me that before already, the question was whether `ZXingReader.exe` works with the `ZXing.dll` from the NuGet Package (or alternatively from [this zip file](https://github.com/zxing-cpp/zxing-cpp/actions/runs/9165369998/artifacts/1520752365)).

> I tried this change but it still gave me the same error in zint.h I made a change by replacing ` ../../../zint/backend/zint.h` in core/src/libzint/zint.h with `#include "../../../zint/backend/zint.h"` and it removed the error in that file. Though it is now giving error in similarly written files so will update after I update all of the other files.
> 
> Update: After making changes in all the .c and .h files in libzint I was able to make the DLL and it is also working.

Thanks. You could have simply copied all the mentioned files into the libzint directory. That said, those files in there are symbolic links to the real ones. I wonder why your OS does not properly open them.

Anyway, the missing `ZXingReader` test should tell us if there is an issue with the DLL from the CI system. Hopefully that brings some insights.

**Comment by ShiddhamSharma** [comment]
Ok so no Barcode found when using nuget package dll and working when I am using my dll file

**Comment by ShiddhamSharma** [comment]
Hi
@axxel any updates?
It works fine for me after changing the .dll file so my current issue can be closed.
Just one issue to be checked is why the .dll from NuGet is not working.

**Comment by jjwillis** [comment]
I can confirm the same findings as @ShiddhamSharma. The dll that comes with NuGet package does not return any QR barcodes that I am searching for. My project is moving from the original [ZXing Library](https://github.com/zxing/zxing) to this version in an attempt to speed things up and get better results. My tests passed with the original ZXing. Once I was able compile the DLL and use it instead of the one from the NuGet package, it detected the barcodes as well. This thread was key to get this working. Thanks! Here are some details on how I got it to work in case someone else finds this helpful.
My end goal is to use this in my Visual Studio C# Windows .NET8.0 console app.

1. Verify I have installed C++ (via Visual Studio installer) and made sure C++ CMake tools for Windows was included.
2. Opened "Developer Command Prompt for VS 2022" as administrator (so CMake is in the PATH=).
3. Navigated to a work directory where I followed the readme instructions with these changes:

```
git clone https://github.com/zxing-cpp/zxing-cpp.git --recursive --single-branch --depth 1

cmake -S zxing-cpp -B zxing-cpp.release -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -A x64 -DBUILD_SHARED_LIBS=ON -DZXING_READERS=ON -DZXING_WRITERS=NEW -DZXING_EXPERIMENTAL_API=ON -DCMAKE_CXX_STANDARD=20 -DZXING_C_API=ON

cmake --build zxing-cpp.release -j8 --config Release
```
At this point the new DLLS will be in zxing-cpp.release\core\Release folder

6. Add the ZXingCpp Nuget package to my C# console app. NOTE: I had to select "Include prerelease".
7. Copy the zxing-cpp.release\core\Release\ZXing.dll compiled above, to %userprofile%\.nuget\packages\zxingcpp\0.2.1-alpha\runtimes\win-x64\native

At this point, I could utilize the the library for extracting barcodes. It has detected all barcodes in my 40+ unit tests that were designed to push the limits of QR barcode detection. Good Job!

Also note, if no barcodes found, I am applying some Despeckling and Median filters, size adjusting as a final effort when I have of poor images. Your library is so fast, this is a great improvement. I noticed you have a "TryDenoise" option you are testing with. I am going to try that out next.

**Comment by Laurnz** [comment]
For me, just additionally using shared libs and C API did the trick.

cmake -S zxing-cpp -B zxing-cpp.release -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DZXING_C_API=ON

**Comment by mapo80** [comment]
Hi guys, I didn't understand. I have the same problem but I don't know how to solve.
On .net I have always 0 barcodes.
How to solve? I've to rebuild dll? Which is the command to replace with new build?

Thanks

**Comment by mapo80** [comment]
> > So I tested ZxingReader.exe with the dll file I made yesterday and it worked fine.
> 
> You told me that before already, the question was whether `ZXingReader.exe` works with the `ZXing.dll` from the NuGet Package (or alternatively from [this zip file](https://github.com/zxing-cpp/zxing-cpp/actions/runs/9165369998/artifacts/1520752365)).
> 
> > I tried this change but it still gave me the same error in zint.h I made a change by replacing ` ../../../zint/backend/zint.h` in core/src/libzint/zint.h with `#include "../../../zint/backend/zint.h"` and it removed the error in that file. Though it is now giving error in similarly written files so will update after I update all of the other files.
> > Update: After making changes in all the .c and .h files in libzint I was able to make the DLL and it is also working.
> 
> Thanks. You could have simply copied all the mentioned files into the libzint directory. That said, those files in there are symbolic links to the real ones. I wonder why your OS does not properly open them.
> 
> Anyway, the missing `ZXingReader` test should tell us if there is an issue with the DLL from the CI system. Hopefully that brings some insights.

I've used zxing.dll file contained in the zip file you provided and everything works. I want to be sure that is the right way to solve.

Thanks

**Comment by ShiddhamSharma** [comment]
@mapo80 You will have to rebuild the DLL and then replace it with the DLL you get from the nuget package.
You can follow the steps given by @jjwillis.

> 1. Verify I have installed C++ (via Visual Studio installer) and made sure C++ CMake tools for Windows was included.
> 2. Opened "Developer Command Prompt for VS 2022" as administrator (so CMake is in the PATH=).
> 3. Navigated to a work directory where I followed the readme instructions with these changes:
> 
> ```
> git clone https://github.com/zxing-cpp/zxing-cpp.git --recursive --single-branch --depth 1
> 
> cmake -S zxing-cpp -B zxing-cpp.release -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -A x64 -DBUILD_SHARED_LIBS=ON -DZXING_READERS=ON -DZXING_WRITERS=NEW -DZXING_EXPERIMENTAL_API=ON -DCMAKE_CXX_STANDARD=20 -DZXING_C_API=ON
> 
> cmake --build zxing-cpp.release -j8 --config Release
> ```
> 
> At this point the new DLLS will be in zxing-cpp.release\core\Release folder
> 
> 6. Add the ZXingCpp Nuget package to my C# console app. NOTE: I had to select "Include prerelease".
> 7. Copy the zxing-cpp.release\core\Release\ZXing.dll compiled above, to %userprofile%.nuget\packages\zxingcpp\0.2.1-alpha\runtimes\win-x64\native

@axxel I think this will work as a temporary solution for now but you can check if anything is wrong in the pipeline.

**Comment by mapo80** [comment]
> @mapo80 You will have to rebuild the DLL and then replace it with the DLL you get from the nuget package. You can follow the steps given by @jjwillis.
> 
> > 1. Verify I have installed C++ (via Visual Studio installer) and made sure C++ CMake tools for Windows was included.
> > 2. Opened "Developer Command Prompt for VS 2022" as administrator (so CMake is in the PATH=).
> > 3. Navigated to a work directory where I followed the readme instructions with these changes:
> > 
> > ```
> > git clone https://github.com/zxing-cpp/zxing-cpp.git --recursive --single-branch --depth 1
> > 
> > cmake -S zxing-cpp -B zxing-cpp.release -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -A x64 -DBUILD_SHARED_LIBS=ON -DZXING_READERS=ON -DZXING_WRITERS=NEW -DZXING_EXPERIMENTAL_API=ON -DCMAKE_CXX_STANDARD=20 -DZXING_C_API=ON
> > 
> > cmake --build zxing-cpp.release -j8 --config Release
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > At this point the new DLLS will be in zxing-cpp.release\core\Release folder
> > 
> > 6. Add the ZXingCpp Nuget package to my C# console app. NOTE: I had to select "Include prerelease".
> > 7. Copy the zxing-cpp.release\core\Release\ZXing.dll compiled above, to %userprofile%.nuget\packages\zxingcpp\0.2.1-alpha\runtimes\win-x64\native
> 
> @axxel I think this will work as a temporary solution for now but you can check if anything is wrong in the pipeline.

Ok thanks for you answer, very useful.
I want to understand if will be release on nuget a newer version to solve this issue.

Thanks.

**Comment by eric80739** [comment]
@jjwillis may you please provide the dll? I failed to compile by following those steps.
Getting error:
'Cannot transcode invalid UTF-8 JSON text to UTF-16 string.'
by running:
cmake --build zxing-cpp.release -j8 --config Release

> I can confirm the same findings as @ShiddhamSharma. The dll that comes with NuGet package does not return any QR barcodes that I am searching for. My project is moving from the original [ZXing Library](https://github.com/zxing/zxing) to this version in an attempt to speed things up and get better results. My tests passed with the original ZXing. Once I was able compile the DLL and use it instead of the one from the NuGet package, it detected the barcodes as well. This thread was key to get this working. Thanks! Here are some details on how I got it to work in case someone else finds this helpful. My end goal is to use this in my Visual Studio C# Windows .NET8.0 console app.
> 
> 1. Verify I have installed C++ (via Visual Studio installer) and made sure C++ CMake tools for Windows was included.
> 2. Opened "Developer Command Prompt for VS 2022" as administrator (so CMake is in the PATH=).
> 3. Navigated to a work directory where I followed the readme instructions with these changes:
> 
> ```
> git clone https://github.com/zxing-cpp/zxing-cpp.git --recursive --single-branch --depth 1
> 
> cmake -S zxing-cpp -B zxing-cpp.release -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -A x64 -DBUILD_SHARED_LIBS=ON -DZXING_READERS=ON -DZXING_WRITERS=NEW -DZXING_EXPERIMENTAL_API=ON -DCMAKE_CXX_STANDARD=20 -DZXING_C_API=ON
> 
> cmake --build zxing-cpp.release -j8 --config Release
> ```
> 
> At this point the new DLLS will be in zxing-cpp.release\core\Release folder
> 
> 6. Add the ZXingCpp Nuget package to my C# console app. NOTE: I had to select "Include prerelease".
> 7. Copy the zxing-cpp.release\core\Release\ZXing.dll compiled above, to %userprofile%.nuget\packages\zxingcpp\0.2.1-alpha\runtimes\win-x64\native
> 
> At this point, I could utilize the the library for extracting barcodes. It has detected all barcodes in my 40+ unit tests that were designed to push the limits of QR barcode detection. Good Job!
> 
> Also note, if no barcodes found, I am applying some Despeckling and Median filters, size adjusting as a final effort when I have of poor images. Your library is so fast, this is a great improvement. I noticed you have a "TryDenoise" option you are testing with. I am going to try that out next.

**Comment by Laurnz** [comment]
@eric80739 Use the following method to get the DLL https://github.com/zxing-cpp/zxing-cpp/issues/821#issuecomment-2325347156

**Comment by axxel** [comment]
There is (finally) a new release available: https://www.nuget.org/packages/ZXingCpp/0.2.2-alpha. This includes the DLL from the latest windows CI build and I expect this to work now based on earlier feedback. I'd appreciate if someone could actually confirm that.

**Comment by eric80739** [comment]
@axxel  @Laurnz Thank you for your help!
I downloaded the latest version of the update, and after testing on my images, it was able to correctly read both DataMatrix and QR codes!
