### ISSUE TITLE
CMake Error when installing Python wrapper because of missing libzint

### ISSUE THREAD

**Issue by markusfisch** [zxing-cpp/zxing-cpp#793]
The Python wrapper fails to install on a fresh copy because CMake cannot find libzint.

Steps to reproduce:
```
$ git clone https://github.com/zxing-cpp/zxing-cpp.git
$ cd zxing-cpp/wrappers/python
$ python3 setup.py install --user
…
CMake Error at …/zxing-cpp/core/CMakeLists.txt:532 (target_sources):
  Cannot find source file:

    src/libzint/2of5.c
                                                               
```

**Comment by axxel** [comment]
Yes, please see my recent update to the README.md: https://github.com/zxing-cpp/zxing-cpp/commit/91cf5ba5fb5d965e981d680107b1a869751ae940

**Comment by markusfisch** [comment]
Ah! Totally missed that 🙈 Thank you for the quick answer! 👍 

In case someone encounters this error after cleaning an already existing copy (just like I did), here's the command to update the libzint submodule:
```
$ git submodule update --init --recursive
```
