### ISSUE TITLE
ModuleNotFoundError: No module named 'zxingcpp'

### ISSUE THREAD

**Issue by sminkwitz** [zxing-cpp/zxing-cpp#806]
Hey i am on a aarch64 system and built the module successfully with the setup.py. When i check if the module is in my python environment every thing is okay.... but when i try to import the module into a python file and try to run it, it says that there is no module...

Is there any help or does someone have the same issue?

Thanks!

**Comment by axxel** [comment]
Can you try to copy the `zxingcpp.[...].so` file into the same directory as your python script and try again?

**Comment by sminkwitz** [comment]
Hey axxel, thanks for you fast reply! I don't have such a file inside my site-packages folder... i have a folder called zxing_cpp-2.2.0-py3.8-linux-aarch64.egg, inside this folder a is a other folder called EGG-INFO and three .so files libZXing.so, libZXing.so.2.2.1 and libZXing.so.3. i tried to copy those three files in the same directory as my python script is but with the same result.

**Comment by axxel** [comment]
If I execute `python setup.py build` in `wrappers/python` I get a subdirectory `build/lib.linux-x86_64-cpython-312` which contains exactly one file `zxingcpp.cpython-312-x86_64-linux-gnu.so` and that is the python module.

**Comment by sminkwitz** [comment]
Yes on a normal x86 computer this is the case but on my aarch64 system i get after building this folder zxing_cpp-2.2.0-py3.8-linux-aarch64.egg :|

**Comment by axxel** [comment]
Can you paste the complete output of the `python setup.py build` command?

**Comment by sminkwitz** [comment]
I found a solution: I downloaded the zxing-cpp-2.1.0.tar.gz from pypi and built in with this setup.py with the command python setup.py install. Now i got the zxingcpp.cpython-38-aarch64-linux-gnu.so and it is working :)

**Comment by axxel** [comment]
Ok. And if you use the latest release [2.2.0](https://files.pythonhosted.org/packages/a7/8f/77828ef6e7bcad2ed17da58a4af833fce52e2afb6e72214e0403fa0ef197/zxing-cpp-2.2.0.tar.gz) it does not work? If so, could you please provide the output of the `python setup build` command to allow me to get some insight into what is wrong?

**Comment by sminkwitz** [comment]
Also the latest release works fine! What i did before was cloning the git repo then moving into the folder and run this command: python /home/multi/zxing-cpp/wrappers/python/setup.py install

(by the way is there any documentation how to handle the (result.position output to draw bounding boxes)) ?

Then the output was this:

running install
/home/multi/barcodeTrail/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/home/multi/barcodeTrail/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
writing zxing_cpp.egg-info/PKG-INFO
writing dependency_links to zxing_cpp.egg-info/dependency_links.txt
writing top-level names to zxing_cpp.egg-info/top_level.txt
reading manifest file 'zxing_cpp.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'zxing_cpp.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-aarch64/egg
running install_lib
running build_ext
-- Checking for module 'stb'
--   No package 'stb' found
INFO: Qt (Gui/Multimedia/Quick) not found, skipping Qt examples
-- Configuring done
CMake Warning (dev) in example/CMakeLists.txt:
  AUTOGEN: No valid Qt version found for target ZXingOpenCV.  AUTOMOC and
  AUTORCC disabled.  Consider adding:

    find_package(Qt<QTVERSION> COMPONENTS Core)

  to your CMakeLists.txt file.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /home/multi/zxing-cpp/build/temp.linux-aarch64-cpython-38
[ 94%] Built target ZXing
[ 98%] Built target ZXingWriter
[ 98%] Built target ZXingReader
[100%] Built target ZXingOpenCV
creating build/bdist.linux-aarch64/egg
copying build/lib.linux-aarch64-cpython-38/libZXing.so.3 -> build/bdist.linux-aarch64/egg
copying build/lib.linux-aarch64-cpython-38/libZXing.so -> build/bdist.linux-aarch64/egg
copying build/lib.linux-aarch64-cpython-38/libZXing.so.2.2.1 -> build/bdist.linux-aarch64/egg
creating build/bdist.linux-aarch64/egg/EGG-INFO
copying zxing_cpp.egg-info/PKG-INFO -> build/bdist.linux-aarch64/egg/EGG-INFO
copying zxing_cpp.egg-info/SOURCES.txt -> build/bdist.linux-aarch64/egg/EGG-INFO
copying zxing_cpp.egg-info/dependency_links.txt -> build/bdist.linux-aarch64/egg/EGG-INFO
copying zxing_cpp.egg-info/not-zip-safe -> build/bdist.linux-aarch64/egg/EGG-INFO
copying zxing_cpp.egg-info/top_level.txt -> build/bdist.linux-aarch64/egg/EGG-INFO
writing build/bdist.linux-aarch64/egg/EGG-INFO/native_libs.txt
creating 'dist/zxing_cpp-2.2.0-py3.8-linux-aarch64.egg' and adding 'build/bdist.linux-aarch64/egg' to it
removing 'build/bdist.linux-aarch64/egg' (and everything under it)
Processing zxing_cpp-2.2.0-py3.8-linux-aarch64.egg
creating /home/multi/barcodeTrail/lib/python3.8/site-packages/zxing_cpp-2.2.0-py3.8-linux-aarch64.egg
Extracting zxing_cpp-2.2.0-py3.8-linux-aarch64.egg to /home/multi/barcodeTrail/lib/python3.8/site-packages
Adding zxing-cpp 2.2.0 to easy-install.pth file

Installed /home/multi/barcodeTrail/lib/python3.8/site-packages/zxing_cpp-2.2.0-py3.8-linux-aarch64.egg
Processing dependencies for zxing-cpp==2.2.0
Finished processing dependencies for zxing-cpp==2.2.0

**Comment by axxel** [comment]
I don't know if that makes any difference but you are supposed to be inside the `wrappers/python` folder and then simply execute `pyhton setup.py build`. If you could confirm that this works even in you git cloned working copy that would be nice. You may also just close the issue as resolved if you don't find the time for that.
