### ISSUE TITLE
Master branch fails to scan QR code (working in release)

### ISSUE THREAD

**Issue by xhruso00** [zxing-cpp/zxing-cpp#813]
While building the library I found this issue. QR code attached.

![scaledMedianLowBlurImage_3](https://github.com/user-attachments/assets/7bdfb9e3-8fd1-4ae4-8023-fdbffdcf3432)

```
    NSURL *URL = [[NSBundle mainBundle] URLForResource:@"scaledMedianLowBlurImage_3" withExtension:@"png"];
    UIImage *image = [UIImage imageWithContentsOfFile:[URL path]];
    ;
    ZXIBarcodeReader *reader = [[ZXIBarcodeReader alloc] init];
    NSArray<ZXIResult *>*results = [reader readCGImage:[image CGImage] error:nil];
    NSLog(@"%@", results);
```

If I use the release version of library it will scan successfully. (letter "a")

**Comment by xhruso00** [comment]
The compiled binary ZXingReader fails to recognize it regardless version.

**Comment by axxel** [comment]
Sorry for the delayed response. Live...

First I thought your issue must be a consequence of [this change](https://github.com/zxing-cpp/zxing-cpp/commit/6b9f16a79d1965197fb9da4a733090c1efc6c346). But disabling the new algorithm does not make the problem go away (while it does change the binarized content towards the right direction).

That said, there is quick solution to your specific problem: use a different binarizer, like the `GlobalHistogram` or the `FixedThreshold` one. E.g. calling `ZXingReader \#813.png -binarizer global` works for me.

**Comment by axxel** [comment]
I consider this solved...
