### ISSUE TITLE
UPC-A fails to scan

### ISSUE THREAD

**Issue by xhruso00** [zxing-cpp/zxing-cpp#814]
I have a PDF file (Poster image) with UPC-A code. 

The colored version completely fails to scan PNG version of it regardless if it's rasterized for retina (2x scale transform). Isolated barcode is detected only if the PDF is rasterized at 2x resolution.

![cgImage_colored_retina](https://github.com/user-attachments/assets/09e01a9b-f177-4328-bfa8-ebf652b3f004)

![cgImage_transparent_retina](https://github.com/user-attachments/assets/54a89327-8057-426a-a5f3-39804f6424c9)

[problematic_colored_barcode.pdf](https://github.com/user-attachments/files/16436786/problematic_colored_barcode.pdf)

[problematic_transparent_barcode.pdf](https://github.com/user-attachments/files/16436785/problematic_transparent_barcode.pdf)

![cgImage_transparent_non_retina](https://github.com/user-attachments/assets/47eb77dd-d41c-4409-9bf1-f4d518be340b)

**Comment by axxel** [comment]
I believe this is mainly a matter of insufficient resolution. In this particular case you get lucky if you use the `FixedThreshold` binarizer (e.g. `ZXingReader -binarizer fixed <your first image.png>`).

When you look at the screenshot below of an 800% zoom of part of the barcode, you see that the small bars are around 1.6 pixels wide. That is a bad number. 1.0 pixels would work, 2.0 would work as well. Starting at around 4 pixels per module (smallest bar) I would expect any fractional number should also work (like 4.5 pixels).

![Screenshot from 2024-09-08 22-35-17](https://github.com/user-attachments/assets/9c085a9a-91aa-4f52-a7bd-3664a8532226)

**Comment by axxel** [comment]
Closing for lack of feedback / nothing to be done inside zxing-cpp here.
