### ISSUE TITLE
PDF417 encoding problem with ASCII character '0x1E' or 'RS'

### ISSUE THREAD

**Issue by ted944** [zxing-cpp/zxing-cpp#815]
I'm having problem generating PDF417 2D barcode with a string that has the value '0x1E' in it. 
Here is an example string: 40 0d 0a 1e 0d 0a 41 4e 53 49  
I generated a PDF417 2D barcode, using either binary or ASCII encoding, the scanned output is this: 00 00 1e 0a 41 4e 53 49

If I changed the input '0x1e' to something else, like '0x0a', then the output PDF417 2Dbarcode will be correct. 

Could this be a bug in the encoding code? 

Thanks for your help.

**Comment by axxel** [comment]
If there is an issue with the 'old' PDF417 encoder, it will likely not get fixed. There is a new libzint based writer back-end that most certainly will not have this issue. Please have a look at https://github.com/zxing-cpp/zxing-cpp/discussions/739.

To configure your build to use the new API and backend pass `-DZXING_WRITERS=NEW -DZXING_EXPERIMENTAL_API=ON -DZXING_USE_ZINT=ON` to your cmake configure command line.

**Comment by axxel** [comment]
Did switching to the new zint backend solve your problem?

**Comment by axxel** [comment]
Closed for lack of feedback from the OP.
