### ISSUE TITLE
.NET wrapper from 0.2.1-alpha nuget pkg is not decoding QR codes at all (tested on windows)

### ISSUE THREAD

**Issue by MarsRover75** [zxing-cpp/zxing-cpp#821]
Initialization Code
```
ZXingCpp.BarcodeReader ZXcpp = new() {
	//Formats = ZXingCpp.BarcodeFormats.QRCode,
	Formats = ZXingCpp.BarcodeFormats.Any,
	//MaxNumberOfSymbols = 2,
	ReturnErrors = true,
	TryRotate = true,
	TryInvert = true,
	TryHarder = true,
	IsPure = false,
	TextMode = ZXingCpp.TextMode.Plain,
};

```
Getting qrFrame.ImgMat from Emgu.Cv videocapture (code omitted), converting to gray
`CvInvoke.CvtColor(qrFrame.ImgMat, locals.GrayMat, Emgu.CV.CvEnum.ColorConversion.Bgr2Gray);
`
Usage code:
```
ZXingCpp.ImageView imageView = new(
	locals.GrayMat.DataPointer; 
	locals.GrayMat.Width, locals.GrayMat.Height, 
	ZXingCpp.ImageFormat.Lum);
List<ZXingCpp.Barcode> res_cpp = ZXcpp.From(imageView);
```
I DO GET some EAN13 barcodes read but NO QR results (even with errors).
Tried with unprocessed (BGR) image - same luck
```
ZXingCpp.ImageView imageView = new(
	qrFrame.ImgMat.DataPointer, 
	locals.GrayMat.Width, locals.GrayMat.Height, 
	ZXingCpp.ImageFormat.BGR);
```
But if I **_use the same locals.GrayMat_** with ZXing.Net I'm getting perfectly decoded QRs:
```
ZXing.EmguCV.BarcodeReader zxing = new();
zxing.Options.PossibleFormats = [ ZXing.BarcodeFormat.QR_CODE ];
var res = zxing.Decode(locals.GrayMat.GetRawData(), 
	locals.GrayMat.Width, locals.GrayMat.Height,
	ZXing.RGBLuminanceSource.BitmapFormat.Gray8);
```

**Comment by MarsRover75** [comment]
UPD:
Works perfectly on Ubuntu 22.04, must be something wrong with the native windows dll in the nuget package.

**Comment by axxel** [comment]
Yes, there is an issue with the dll included in the package (which I still have not fixed...). Please see #810 for details and a local fix.

**Comment by MarsRover75** [comment]
> Yes, there is an issue with the dll included in the package (which I still have not fixed...). Please see #810 for details and a local fix.

Unfortunately [binaries mentioned there](https://github.com/zxing-cpp/zxing-cpp/issues/810#issuecomment-2236810300) are no longer available

**Comment by MarsRover75** [comment]
OK, I finally managed to build ZXing.dll for Windows x64 **on Windows machine** with proper C API exports and it works whith a wrapper from nuget 0.2.1-alpha.

STEP 1: (straight from readme)
`git clone https://github.com/zxing-cpp/zxing-cpp.git --recursive --single-branch --depth 1`

STEP 1a: (**this one is crucial**):
for **all** symlinks in `zxing-cpp\core\src\libzint` (including fonts subfolder) replace them with original files from `zxing-cpp\zint\backend` 
This is important, because at some point some (or all) symlinks might get broken during the next steps.
DO NOT put any extra files there, only replace those that are symlinks with their link targets.
I just made a simple Powershell two-liner for that which I didn't save  ).

STEPS 2 & 3:
```
cmake -S zxing-cpp -B zxing-cpp.release -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DZXING_READERS=ON -DZXING_WRITERS=NEW -DZXING_EXPERIMENTAL_API=ON -DCMAKE_CXX_STANDARD=20 -DZXING_C_API=ON -A x64
cmake --build zxing-cpp.release -j8 --config Release --target install

```
then replace `\.nuget\packages\zxingcpp\0.2.1-alpha\runtimes\win-x64\native\ZXing.dll` in your nuget package cache with what you just built (`zxing-cpp.release\core\Release\ZXing.dll`).

Or add a custom step to your csproj to always copy this dll to wherever you need it.

Good luck.

**Comment by axxel** [comment]
Sorry that you had to jump through all those hoops, just to get a working DLL file. Could you give the `windows-latest-exp-artifacts` from the [latest CI run](https://github.com/zxing-cpp/zxing-cpp/actions) a quick try and see if the contained DLL still works?

**Comment by MarsRover75** [comment]
Hi, I confirm that dll from `Artifact download URL: https://github.com/zxing-cpp/zxing-cpp/actions/runs/10673513153/artifacts/1883648928` works on Windows.

> Sorry that you had to jump through all those hoops, just to get a working DLL file
I actually enjoy this kind of troubleshooting ;)

**Comment by axxel** [comment]
There is (finally) a new release available: https://www.nuget.org/packages/ZXingCpp/0.2.2-alpha. This includes the DLL from the latest windows CI build and I expect this to work now based on earlier feedback. I'd appreciate if someone could actually confirm that.

**Comment by MarsRover75** [comment]
> I'd appreciate if someone could actually confirm that.

It does work in my Windows environment, thanks!
