### ISSUE TITLE
Android wrapper Snapshot releases automatically published from master to Maven Central

### ISSUE THREAD

**Issue by nift4** [zxing-cpp/zxing-cpp#824]
Hi,

I'd really appreciate if the latest master state was uploaded to Maven Central as -SNAPSHOT release. I can't use the last released version because it lacks x86/x86_64 libraries which was fixed in master, but building zxing-cpp and then properly propagating the output to a multi-module project required major surgery of the CI scripts, which would be resolved if there were snapshot releases.

Thanks in advance, and thanks for maintaining this library :)

**Comment by axxel** [comment]
It would help a lot in making this happen (sooner than later) if you could provide a PR ;).

**Comment by nift4** [comment]
https://github.com/zxing-cpp/zxing-cpp/pull/827

**Comment by axxel** [comment]
Thanks for your work on this. I decided to do things a little differently and thought it would be faster to just commit something instead of asking you to modify your PR. There should be a 2.2.0-SNAPSHOT version available now.

One question regarding convention: I would have expected that the x.y.z-SNAPSHOT build is released prior to the final x.y.z release, so the current one should actually be called 2.3.0-SNAPSHOT?

Can you confirm that the 2.2.0-SNAPSHOT is working and actually contains what you were looking for?

**Comment by nift4** [comment]
> One question regarding convention: I would have expected that the x.y.z-SNAPSHOT build is released prior to the final x.y.z release, so the current one should actually be called 2.3.0-SNAPSHOT?

To be honest, I don't know, but it would make sense to me. I'm fine with either, anyway.

> Can you confirm that the 2.2.0-SNAPSHOT is working and actually contains what you were looking for?

I can confirm I can download it from Gradle (after adding the snapshot repo), build an APK with it and the resulting APK contains the x86 libraries I was looking for. The APK works fine :D https://github.com/nift4/PhoneVR/commit/c9a7408ea1daf1852dd90e41c3c2da4d4be020a7 (the red checkmark is a known issue and unrelated to this)

Big thank you for your efforts, I very much appreciate it!

**Comment by axxel** [comment]
> To be honest, I don't know, but it would make sense to me. I'm fine with either, anyway.

Or maybe even better (because easier to implement, for example) would be to have no prefix at all if that is possible, simply `SNAPSHOT`, which would always refer to `HEAD` in git speech.

Thanks for you contribution and testing effort.

**Comment by nift4** [comment]
> Or maybe even better (because easier to implement, for example) would be to have no prefix at all if that is possible, simply SNAPSHOT, which would always refer to HEAD in git speech.

I think Maven Central and the ecosystem do not really support that, quoting Maven Central docs (emphasis mine):

> We provide the option to publish artifacts using the **-SNAPSHOT suffix** in case that you need to do any test on your publishing process, but once it is released there is no possibility to change it. Please check the [Can I change (modify, delete, update) a component on Central?](https://central.sonatype.org/faq/can-i-change-a-component/) FAQ for more details.
