### ISSUE TITLE
implementation("io.github.zxing-cpp:kotlin-native:2.2.1") Not exists

### ISSUE THREAD

**Issue by adrienbusin** [zxing-cpp/zxing-cpp#835]
Hello, 

I would try to use Kotlin wrapper but it's not published on mavenCentral yet. 
The doc says to add "implementation("io.github.zxing-cpp:kotlin-native:2.2.1")" but it doesn't exist. 

Can you please tell me if a version exists with this wrapper ? Or can you please publish it ? 

Thanks a lot

**Comment by axxel** [comment]
The documentation is indeed wrong at this time as there is no published 'release' version of kotlin native available, yet. But there is a `SNAPSHOT` version available, see [here](https://github.com/zxing-cpp/zxing-cpp/issues/800#issuecomment-2337492471).

**Comment by axxel** [comment]
If that works for you, please close the issue. :)
