### ISSUE TITLE
.Net wrapper issue

### ISSUE THREAD

**Issue by husam-ebish** [zxing-cpp/zxing-cpp#840]
I am unable to start the .Net wrapper due to the following issue:

![image](https://github.com/user-attachments/assets/0734cd54-7d87-4a04-9ca1-071f10e433a9)

Did I miss any configurations?

![image](https://github.com/user-attachments/assets/7ac3bde9-95bc-4486-8d93-0f51b9e59969)

**Comment by axxel** [comment]
I suggest you install the `ZXingCpp` [nuget package](https://www.nuget.org/packages/ZXingCpp/), which comes with the native DLL included:
```
dotnet add package ZXingCpp
```
