### ISSUE TITLE
Invalid DataMatrix Code Generated for URLs

### ISSUE THREAD

**Issue by yangyu2010** [zxing-cpp/zxing-cpp#843]
I am encountering an issue when generating DataMatrix QR codes using the online demo writer available at https://zxing-cpp.github.io/zxing-cpp/demo_writer.html.

**Issue Description:**
When I input certain URLs (such as `https://youtu.be/kqLRRNOpe8U?si=w-kASttui3kK2pRC`) to generate a DataMatrix QR code, the resulting code is invalid and cannot be scanned or recognized. However, using the same URL on other websites' QR code generators results in a valid and functional DataMatrix QR code.

**Steps to Reproduce:**
1. Go to https://zxing-cpp.github.io/zxing-cpp/demo_writer.html
2. Select `DataMatrix` format.
3. Enter the URL `https://youtu.be/kqLRRNOpe8U?si=w-kASttui3kK2pRC` in the text box.
4. Generate the QR code.
5. Attempt to scan the QR code with a standard QR code scanner.

Is there something I'm doing wrong? It seems there might be a problem with how URLs are encoded into DataMatrix codes specifically.

![Xnip2024-09-30_17-45-09](https://github.com/user-attachments/assets/8a0f771f-52f6-4b68-8644-ad4ca9aba628)

**Comment by axxel** [comment]
The DataMatrix symbol you generated in your sample is perfectly valid. The fact that you were talking about "DataMatrix QR Codes" makes me believe that you are not aware of the fact that DataMatrix and QRCodes are 2 different symbologies. If you want to generate QRCodes, then select `QR Code` in the Format dropdown, which results in this:
![#843-qrcode](https://github.com/user-attachments/assets/ee50f440-e1f7-4969-b4eb-71de885f66cd)
