### ISSUE TITLE
Switch to a PEP 517 build system for the python wrapper

### ISSUE THREAD

**Issue by anthonyryan1** [zxing-cpp/zxing-cpp#848]
From a distro packaging perspective, the current python wrapper setuptools solution has a problem no matter which how I try to use it.

Right now, if I build the python bindings with cmake instead of setuptools, I'm missing the python metadata.

If I build it with setuptools, my cmake state and variables get overwritten. Binaries are stripped when that's not desired and cmake variables like VERSION_INFO are not passed correctly.

Is there any chance we could switch to a standardized PEP 517 backend for building the python wrapper?

For example [meson-python](https://pypi.org/project/meson-python/) which is the main, stable, PEP 517 build system I'm currently familiar with.

There's also [py-build-cmake](https://pypi.org/project/py-build-cmake/) but I'm not certain it's production ready at this time.

**Comment by axxel** [comment]
> Right now, if I build the python bindings with cmake instead of setuptools, I'm missing the python metadata.

Can you elaborate what you mean?

A quick googling brought me [this](https://stackoverflow.com/a/71080793/2088798). So it seems `setuptools` is not per se the wrong or outdated approach. I don't care much about the python part of the module building process as long as the tools involved support using cmake to build the core library. I will not merge something that does the same job and will have to be maintained separately.

**Comment by axxel** [comment]
Is it fair to assume that you are not interested in pursuing this any further?

**Comment by anthonyryan1** [comment]
The issue of cmake variables not being respected still stands, but after a couple hours of research, I still don't know the best way forward.

I'm content to close this issue until someone suggests a good way forward to fix the cmake variables, and I'll re-open it if it ever occurs to me.

**Comment by axxel** [comment]
Thanks for bringing me up to speed with your state of mind. Maybe till later then...
