### ISSUE TITLE
[Question] BadImageFormatException thrown by ZXing_CreatorOptions_new

### ISSUE THREAD

**Issue by blauertee** [zxing-cpp/zxing-cpp#850]
I'm trying to port the .net wrapper to netstandard2.0. 

The function `ZXing_CreatorOptions_new` throws a `BadImageFormatException`. This is independet of the actual data in the `format` argument. I'm not sure how this can happen since there is no actual Image data handled which could be invalid. `ZXing_CreatorOptions_new` is just a constructor for a struct right? So what's going on?

Thank's in Advance!!

**Comment by axxel** [comment]
The term "BadImageFormat" appears nowhere in the code base. Also your are talking about a "C-function", that does not through exceptions. I suspect this is something C# related and has nothing to do with `ZXing_CreatorOptions_new`, meaning all other functions will probably result in the same behavior.

**Comment by blauertee** [comment]
Yes you're right that is indeed confusing. The Exception thrown (System.BadImageFormat) is a C# Builtin exception, but it is definitely thrown (if the debugger works) by this line `var tmp = ZXing_CreatorOptions_new(format);`

where `ZXing_CreatorOptions_new` is defined as a raw dll binding (so no throw statement there either):

```
[DllImport(DllName)]
public static extern IntPtr ZXing_CreatorOptions_new(BarcodeFormat format);
```

And the Stack trace suggests that the error originates from the DLL as well:

Name | Value
 -- | --
 StackTrace | "   at ZXingCpp.Dll.ZXing_CreatorOptions_new(BarcodeFormats format)\r\n   at ZXingCpp.CreatorOptions..ctor(BarcodeFormats format) in [...]\\ZXingCpp\\ZXingCpp.cs:line 642\r\n   at ZXingCpp.CreatorOptions.op_Implicit(BarcodeFormats f) in [...]\\dotnet\\ZXingCpp.Tests\\UnitTest1.cs:line 65"

But ofc it makes no sense for a C Function to throw a C# `System.BadImageFormatExeption`.  (As far as I know)

If anyone has any Ideas I'd be grateful <3

**Comment by axxel** [comment]
Did you build the native `ZXing.dll` yourself? Can you confirm that the ZXingCpp nuget package works as is?

**Comment by blauertee** [comment]
I extracted the DLL from the nuget package, since I can not install it in the regular way because the nugget does not target netstandard2.0. I'm trying to port the Nuget to netstandard2.0
