### ISSUE TITLE
Can't detect QR code

### ISSUE THREAD

**Issue by VietHoang24** [zxing-cpp/zxing-cpp#851]
Issue Description:

I have been using a library to scan QR codes, but currently, the library cannot recognize my QR code, even though it was working fine before. After checking, I discovered that after starting the camera, the library tries to connect to the API but encounters an error. As a result, the QR code cannot be detected.

API 

```
curl 'https://fastly.jsdelivr.net/npm/zxing-wasm@1.1.3/dist/reader/zxing_reader.wasm' \
  -H 'sec-ch-ua: "Not A(Brand";v="99", "Google Chrome";v="121", "Chromium";v="121"' \
  -H 'Referer: https://app.qa2024stg.upft.jp/' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua-platform: "Linux"' \
  --compressed
```

![image](https://github.com/user-attachments/assets/c3913ee0-ad51-43b9-b5c9-00352e05eb39)

**Comment by Sec-ant** [comment]
This is not a zxing-cpp issue, I suggest reading https://github.com/Sec-ant/zxing-wasm?tab=readme-ov-file#notes or discussing it under https://github.com/gruhn/vue-qrcode-reader/issues/456
