### ISSUE TITLE
ITF Barcode Recognition Fails Due to minCharCount Limit of 6 Characters

### ISSUE THREAD

**Issue by mslichao** [zxing-cpp/zxing-cpp#853]
Hi, I have an ITF barcode with content "2024" that can't be recognized by zxing-cpp. I found that this is because the ITF reader has a minCharCount=6 limit (https://github.com/zxing-cpp/zxing-cpp/blob/master/core/src/oned/ODITFReader.cpp#L18).

In our case, there are many ITF barcodes with fewer than 6 characters. Is it possible to make this variable configurable when running the reader?

**Comment by axxel** [comment]
The value 6 was chosen to prevent lots of false positives to appear. What is the `minCharCount` of your application? Can you post a sample image of such a barcode? I am hesitant to add more parameters to the API as this causes a lot of maintainance work across all the wrappers. If possible, I'd like to find solutions that work out of the box.

**Comment by mslichao** [comment]
I saw discussions mentioning that ITF doesn't have a checksum, and limiting the `minCharCount` can help prevent false positives.

In our case, we’ve implemented a separate solution to detect and crop the barcode before sending it to zxing-cpp for recognition, which helps suppress false positives during the detection step. Unfortunately, I cannot share the original images from our customer.

Our customer's ITF barcodes contain 4 characters, though I am unsure if they have any shorter barcodes.

If there were a configurable option to control the minimum supported character count, we could fine-tune the recognition process based on our customer's data, potentially improving accuracy.

Thank you very much for your support!

**Comment by axxel** [comment]
Well, if you pre-crop the images before sending it to `zxing-cpp`, can you maybe provide a sample of such a cropped image? You can crop it until there is nothing other than the barcode itself left, which should make it sharable (you mentioned the content "2024" already). This way I could have a look at the resolution and quality of the scan.

**Comment by mslichao** [comment]
![1515](https://github.com/user-attachments/assets/41e8a7eb-473e-4e95-b53d-d22608e99acb)
This is the cropped image we sent to zxingcpp, the content of this barcode is `1515`
