### ISSUE TITLE
No harder option for Python

### ISSUE THREAD

**Issue by adamponi** [zxing-cpp/zxing-cpp#854]
Good day,
I see that the harder option is missing for Python.

In other languages, this option is available:

Python:
https://github.com/zxing-cpp/zxing-cpp/blob/fc42827d422978829fdef8c8438ce5c5c0c7cda1/wrappers/python/zxing.cpp#L42

Rust:
https://github.com/zxing-cpp/zxing-cpp/blob/fc42827d422978829fdef8c8438ce5c5c0c7cda1/wrappers/rust/examples/demo_reader.rs#L26

Code C:
https://github.com/zxing-cpp/zxing-cpp/blob/fc42827d422978829fdef8c8438ce5c5c0c7cda1/core/src/ZXingC.h#L232
https://github.com/zxing-cpp/zxing-cpp/blob/fc42827d422978829fdef8c8438ce5c5c0c7cda1/core/src/ReaderOptions.h#L54

Is this a bug or intended behavior?

**Comment by axxel** [comment]
That is intended. `TryHarder` is always enabled for the python code. The idea being that disabling is only really interesting in real-time mobile applications to speed up the detection while sacrificing success rate. Do you have a specific need to disable it?

**Comment by adamponi** [comment]
You are right. I see that this topic has been discussed before.

https://github.com/zxing-cpp/zxing-cpp/pull/444

Generally, I wanted to enable the tryHarder option because on my 200 Mpx photo it was not possible to read all the barcodes.

I wonder how I could improve the feeling indicator. From what I see, setBinarizer could probably help with this, but I don't really know what it does.

I am also looking for other ways to increase the reading indicator.

As for your question, the only idea that comes to my mind is if there was a need to decode video in real time from a 4k 30 or 60 FPS stream. But I am not currently using this scenario.

**Comment by adamponi** [comment]
For my part, I can only suggest adding this option as enabled by default to maintain consistency with the rest of the code.

**Comment by axxel** [comment]
> Generally, I wanted to enable the tryHarder option because on my 200 Mpx photo it was not possible to read all the barcodes.

Please understand that `TryHarder` is `true` by default in Python (and everywhere else). Detecting multiple linear barcodes in a 200Mpx image might indeed fail. If you want to experiment, please change the following line:
https://github.com/zxing-cpp/zxing-cpp/blob/fc42827d422978829fdef8c8438ce5c5c0c7cda1/core/src/oned/ODReader.cpp#L98
to simply `int rowStep = 1;`. Does that help your case? Note that the runtime will increase substantially for your 200MPx image.

**Comment by adamponi** [comment]
This change actually helped increase the number of codes read. I have a data set with 73 codes. Previously it found 67 pieces. After the change you gave me it found 71. What else can I do to have 100% reading, i.e. 73 codes read out of all 73 codes? Only two are missing

**Comment by adamponi** [comment]
I mean I did:
zxing-cpp/core/src/oned/ODReader.cpp
int rowStep = 1;

**Comment by axxel** [comment]
To get an idea what the issue is with the remaining 2, I would need to see them.

**Comment by adamponi** [comment]
Unfortunately I can't share these photos.

But thank you very much for your help.

Do you know how to run a benchmark with zxing-cpp in BinaryEye?

**Comment by axxel** [comment]
> Do you know how to run a benchmark with zxing-cpp in BinaryEye?

No, @markusfisch will know about that, I guess.
