### ISSUE TITLE
Unresolvable QR code

### ISSUE THREAD

**Issue by monkeycc** [zxing-cpp/zxing-cpp#856]
![6](https://github.com/user-attachments/assets/c3b388a9-e30b-45a3-8882-f3b0374c20a6)
Unresolvable QR code

```python
import cv2, zxingcpp

img = cv2.imread('1.jpg')
barcodes = zxingcpp.read_barcodes(img)
for barcode in barcodes:
	print('Found barcode:'
		f'\n Text:    "{barcode.text}"'
		f'\n Format:   {barcode.format}'
		f'\n Content:  {barcode.content_type}'
		f'\n Position: {barcode.position}')
if len(barcodes) == 0:
	print("Could not find any barcode.")
```
QR code generation website
https://cli.im/text

**Comment by axxel** [comment]
The problem is the dark background, which makes it a anon-conforming QRCode. A valid QRCode symbol as to be surrounded by white pixels. If you crop the dark background away, it works just fine:

![#856](https://github.com/user-attachments/assets/a7af0055-f7fc-4539-ad7f-6805961583e5)
