### ISSUE TITLE
Compiling zxing with msvc

### ISSUE THREAD

**Issue by Xennor** [zxing-cpp/zxing-cpp#863]
I compiled zxing-cpp successfully with the msvc compiler but after including it in my own program it does not compile. 
The standard library **bit** was not included in the **Bithacks.h** file.

![2024-10-24_16-54](https://github.com/user-attachments/assets/547c964b-40c0-48e9-a944-546b742fae29)

After some searching I found out that the msvc compiler sets ___cplusplus_ to _199711L_ per default. 
The solution is to set the compiler option **/Zc:__cplusplus** ([see here](https://devblogs.microsoft.com/cppblog/msvc-now-correctly-reports-__cplusplus/)).

Maybe this could be mentioned in the documentation or checked differently?

Additional Information:

- MSVC Version 19.40.33816
- C++ Standard 20

**Comment by axxel** [comment]
First of all, it should compile without the `<bit>` header. Can you post the error message (preferably as text) that you get without setting `/Zc:__cplusplus`?

Second: can you check if replacing the `#if __has_include(<bit>) ...` line with the following line fixes your compile issue?
```c++
#if __has_include(<bit>) &&  (__cplusplus > 201703L || _MSVC_LANG > 201703L)
```

**Comment by Xennor** [comment]
If I compile it without the **/Zc:__cplusplus** I get no member errors (in BitHacks.h):
```
error C2039: "countl_zero" is no member of "std". (line 42)
error C2039: "countr_zero" is no member of  "std". (line 86)
error C2039: "popcount" is no member of  "std". (line 142)
error C3861: "popcount": identifier not found. (line 142)
```
The **__cpp_lib_bitops** is defined but the **__cplusplus** variable is wrong as described before.

Your solution works perfectly ([predefined macros](https://learn.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-170))! Therefore **/Zc:__cplusplus** is not needed anymore.

```cpp
#if __has_include(<bit>) &&  (__cplusplus > 201703L || _MSVC_LANG > 201703L)
```

**Comment by axxel** [comment]
Could you do the me the favor and check if the following code also works for you without /Zc:__cplusplus?
```c++
#if __has_include(<bit>) && __cplusplus > 201703L
#include <bit>
#if __cplusplus > 201703L && defined(__ANDROID__) // NDK 25.1.8937393 has the implementation but fails to advertise it
#define __cpp_lib_bitops 201907L
#endif
#else
#undef __cpp_lib_bitops
#endif
```
