### ISSUE TITLE
Does ZXing support reading rotated barcodes

### ISSUE THREAD

**Issue by shuchao97** [zxing-cpp/zxing-cpp#865]
Thank you for the open-source project. Does ZXing support reading rotated barcodes? I tested it by taking a picture of a barcode rotated 45 degrees relative to the horizontal direction, and after multiple tests, I found that this barcode could not be recognized. I am using ZXing version 1.2.

**Comment by axxel** [comment]
Whether or not a 45° rotated barcode can be detected depends on the barcode. Which type do you want to scan?

You mentioned 'ZXing version 1.2'. That is so old and also the name of this project is `zxing-cpp` or `ZXing-C++`, so maybe you are talking about something else entirely.

**Comment by axxel** [comment]
Closed for lack of feedback from OP.
