### ISSUE TITLE
Image border seems to be considered as a quiet zone (Interleaved 2of5)

### ISSUE THREAD

**Issue by synedra-mpe** [zxing-cpp/zxing-cpp#869]
When trying to detect this Interleaved 2of5 barcode, which has no quiet zones in the image

![barcode](https://github.com/user-attachments/assets/6ae02f17-6cf1-426a-bb03-e3e282056f6e)

I get the correct result `3012627384` using [1].

When trying to scan this barcode with a camera and moving the camera from left to right, wrong results are produced, which have truncated the the last digit pairs, eg. `301262` or `30126273`.

The reason for this seems to be, that the shape of the stop code itself is occurring in the barcode and the stop-code is only distinguishable if there is a quite zone after it, which seems to be assumed if there is the right image border instead of a real quiet zone/white space.

Is there a way to enforce _real_ quiet zone to be enforced?

[1] https://zxing-cpp.github.io/zxing-cpp/demo_reader.html
[2] https://zxing-cpp.github.io/zxing-cpp/demo_cam_reader.html

**Comment by axxel** [comment]
There is currently no option to enforce this. If you can compile the code, you can try a quick workaround by removing [those characters](https://github.com/zxing-cpp/zxing-cpp/blob/22adcab8bc1ecf8222452e05b6dd42380282966c/core/src/oned/ODITFReader.cpp#L72C8-L72C30). If this works for you, let me know.

**Comment by synedra-mpe** [comment]
> If you can compile the code, you can try a quick workaround by removing [those characters](https://github.com/zxing-cpp/zxing-cpp/blob/22adcab8bc1ecf8222452e05b6dd42380282966c/core/src/oned/ODITFReader.cpp#L72C8-L72C30). If this works for you, let me know.

Did the mentioned change in `ODITFReader.cpp` and compiled wasm and tested it using mobile Safari.
The issue could not be reproduced, as seen in the screen recording. 

https://github.com/user-attachments/assets/5427f646-2967-4b24-b872-848461da6189

**Comment by axxel** [comment]
The acceptance of a symbol with missing whitespace at the image border is to support the relatively common situation where people try to scan a cropped image or a generated one with no or very small quiet zones. A possible solution could be to accept a truncated quiet zone only when truncated on both ends.

Is the workaround you tested sufficient for you needs at the moment?

**Comment by synedra-mpe** [comment]
> The acceptance of a symbol with missing whitespace at the image border is to support the relatively common situation where people try to scan a cropped image or a generated one with no or very small quiet zones. A possible solution could be to accept a truncated quiet zone only when truncated on both ends.

Sounds like an interesting approach to solve this problem.
On the one hand, I think changing the behavior would break many user applications, on the other hand, I think it should at least be possible to have the information about the presence of quiet zones in the result object.

> Is the workaround you tested sufficient for you needs at the moment?

Yes, but do you mean that I should fork this project with the workaround and then also build my own version of https://github.com/Sec-ant/zxing-wasm?

**Comment by axxel** [comment]
> think it should at least be possible to have the information about the presence of quiet zones in the result object.

That is an interesting idea. I would consider this to be one those niche applications that fit the JSON channel idea discussed in #862.

> but do you mean that I should fork this project

Only in the short term... I'll come up with a heuristic along the line of what I wrote above (sometime next week). I expect that to to actually break hardly any user code if at all.

**Comment by synedra-mpe** [comment]
Glad to hear there is a plan for all these issues in #862. Will link this issue as a comment there.
Something like 
`"endQuietZoneDetected": "true"`,
`"fullIsoCompliant: "true"`,
`"endQuietZoneLength": "10"` or
`"cropped": "true"`.

Thanks for all your efforts btw.

**Comment by synedra-mpe** [comment]
Thanks a lot for the fix! Just testet it and the usecase seems to be perfectly fixed.

**Comment by axxel** [comment]
Danke für die Rückmeldung und Frohes Neues... :)

**Comment by synedra-mpe** [comment]
![Image](https://github.com/user-attachments/assets/29a88046-53e4-4372-b17f-7facd1e2781e)
Just came up with this ITF barcode. Unfortunately it is possible to  only get `78901234` as a result, when moving the camera from right to left.
Can be reproduced, suing ttps://zxing-cpp.github.io/zxing-cpp/demo_cam_reader.html
Is there a way to also fix this - [11d12b5](https://github.com/zxing-cpp/zxing-cpp/commit/11d12b577ec12afdf9a36528aaad531a525f01d8) seems to only have fixed the case, when the right quiet zone is truncated.

**Comment by axxel** [comment]
As you can see from the comment, I originally intended the code to do what it (hopefully) does now. I believe this should fix the issue but I have not tested this particular sample. Please let me know if this works for you.

**Comment by synedra-mpe** [comment]
> As you can see from the comment, I originally intended the code to do what it (hopefully) does now. I believe this should fix the issue but I have not tested this particular sample. Please let me know if this works for you.

Thanks for the quick response. Tested the fix, and was not able to reproduce the issue, mentioned in https://github.com/zxing-cpp/zxing-cpp/issues/869#issuecomment-2830261819. So it seems to work now as expected.
